'use client';
import { useState, type ReactNode } from 'react';
import { calciumClearance, fib4, gepGrade, hyperglycemicCriteria, lipidCalculations, volumeDoubling, washout } from '../../lib/clinical-calculations';

const sources = {
  lipids: ['ADLM 2024 · pomiar lipidów', 'https://academic.oup.com/jalm/article/9/5/1040/7717178'],
  liver: ['EASL–EASD–EASO 2024 · MASLD', 'https://www.sciencedirect.com/science/article/pii/S0168827824003295'],
  nen: ['IARC/WHO · klasyfikacja NEN', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6265262/'],
  prrt: ['EMA · Lutathera, informacje o produkcie', 'https://www.ema.europa.eu/en/medicines/human/EPAR/lutathera'],
  diabetes: ['Konsensus ADA/EASD 2024 · DKA/HHS', 'https://doi.org/10.2337/dci24-0032'],
  calcium: ['ESE PARAT 2021 · różnicowanie FHH', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8789028/'],
  adrenal: ['ESE 2023 · incidentaloma', 'https://academic.oup.com/ejendo/article/189/1/G1/7198474'],
  weight: ['NIDDK · Body Weight Planner', 'https://www.niddk.nih.gov/bwp'],
} as const;
export function Workbench({ title, children, source }: { title: string; children: ReactNode; source?: keyof typeof sources }) {
  return <section className="clinical-workbench"><span className="eyebrow">PRACOWNIA INTERPRETACJI</span><h3>{title}</h3>{children}{source && <p className="workbench-source"><a href={sources[source][1]} target="_blank" rel="noreferrer">{sources[source][0]}</a> · sprawdzono zakres ćwiczenia 11.09.2026 · bez recenzji klinicznej</p>}</section>;
}
export function NumberField({label,value,set,min=0,max=1000,step=1}:{label:string;value:number;set:(n:number)=>void;min?:number;max?:number;step?:number}) {
  return <label>{label}<input type="number" value={Number.isNaN(value)?'':value} min={min} max={max} step={step} onChange={e=>set(e.target.value===''?NaN:Number(e.target.value))}/></label>;
}
const n = (v: number | null, digits=1) => v === null || !Number.isFinite(v) ? '—' : v.toFixed(digits);
export function Reason({question,children}:{question:string;children:ReactNode}) {
  return <details className="workbench-reason"><summary>{question}</summary><div>{children}</div></details>;
}
export function LipidWorkbench() {
  const [tc,T]=useState(240),[hdl,H]=useState(45),[tg,G]=useState(320);
  const r=lipidCalculations(tc,hdl,tg);
  return <Workbench title="LDL: dwa wzory, granice zastosowania" source="lipids"><div className="workbench-inputs"><NumberField label="TC (mg/dl)" value={tc} set={T}/><NumberField label="HDL-C (mg/dl)" value={hdl} set={H}/><NumberField label="TG (mg/dl)" value={tg} set={G} max={2000}/></div><div className="workbench-results" aria-live="polite"><p>Friedewald <strong>{n(r.friedewald)} mg/dl</strong></p><p>Sampson <strong>{n(r.sampson)} mg/dl</strong></p><p>Nie-HDL <strong>{n(r.nonHdl)} mg/dl</strong></p></div><p>Friedewald: TC − HDL − TG/5. Sampson: TC/0,948 − HDL/0,971 − (TG/8,56 + TG × nie-HDL/2140 − TG²/16100) − 9,44.</p><p>„—” oznacza nieprawidłowe dane lub wynik poza zakresem: Friedewald wymaga TG &lt;400, Sampson TG ≤800 mg/dl. Ujemnego wyniku nie zamieniamy w zero.</p><Reason question="Dlaczego wiek 65 lat lub sama cukrzyca nie ustala celu LDL?"><p>Ryzyko wymaga pełnej oceny, m.in. ASCVD, uszkodzenia narządowego i czasu trwania cukrzycy. SCORE2, SCORE2-OP i SCORE2-Diabetes mają odrębne populacje i dane wejściowe. Nie wyliczamy zastępczego „SCORE2” z kilku suwaków.</p><a href="https://www.escardio.org/guidelines/practice-tools/cvd-prevention-toolbox/score-risk-charts/" target="_blank" rel="noreferrer">Oficjalne narzędzia ESC</a></Reason></Workbench>;
}
export function FibrosisWorkbench() {
  const [age,A]=useState(54),[ast,S]=useState(62),[alt,L]=useState(58),[plt,P]=useState(180);
  const f=fib4(age,ast,alt,plt),low=age>65?2:1.3;
  const risk=f===null?'Brak wyniku':age<35?'Ograniczona trafność poniżej 35 lat':f<low?'Niskie ryzyko':f<=2.67?'Wymaga drugiego etapu oceny':'Wysokie ryzyko — wymaga dalszej oceny';
  return <Workbench title="FIB‑4: przesiew, a nie stopień włóknienia" source="liver"><div className="workbench-inputs"><NumberField label="Wiek (lata)" value={age} set={A} min={18} max={100}/><NumberField label="AST (U/l)" value={ast} set={S}/><NumberField label="ALT (U/l)" value={alt} set={L}/><NumberField label="Płytki (10⁹/l)" value={plt} set={P}/></div><p className="workbench-result" aria-live="polite">FIB‑4 = {n(f,2)} · {risk}</p><p>Wiek × AST / (płytki × √ALT). Próg niskiego ryzyka: {low.toFixed(1)}. Wynik nie rozpoznaje F0–F4 i nie służy ocenie ostrej choroby.</p><Reason question="Jaki jest kolejny krok przy podwyższonym wyniku?"><p>Ocena drugim testem, np. elastografią lub ELF, zgodnie z kontekstem i ścieżką MASLD. Niski wynik nie wyklucza wszystkich przypadków zaawansowanego włóknienia.</p></Reason></Workbench>;
}
export function CalciumWorkbench() {
  const [uc,U]=useState(4),[sc,S]=useState(11),[ucr,C]=useState(120),[scr,R]=useState(.9);
  const r=calciumClearance(uc,scr,sc,ucr);
  return <Workbench title="CCCR: wynik z pomiarów, nie z wybranego rozpoznania" source="calcium"><div className="workbench-inputs"><NumberField label="Ca w moczu (mg/dl)" value={uc} set={U} step={.1}/><NumberField label="Ca całkowity w surowicy (mg/dl)" value={sc} set={S} step={.1}/><NumberField label="Kreatynina w moczu (mg/dl)" value={ucr} set={C}/><NumberField label="Kreatynina w surowicy (mg/dl)" value={scr} set={R} step={.1}/></div><p className="workbench-result" aria-live="polite">CCCR = {n(r,4)}</p><p>(Ca mocz × kreatynina surowica) / (Ca surowica × kreatynina mocz). Próbki powinny pochodzić z odpowiadającej sobie zbiórki i pobrania. Wynik jest bez jednostki.</p><Reason question="CCCR <0,01: czy to już rozpoznanie FHH?"><p>Nie. Wyniki FHH i PHPT nakładają się. Interpretuj PTH, wywiad rodzinny, witaminę D, funkcję nerek, tiazydy i podaż wapnia; w uzasadnionych sytuacjach rozważ genetykę. Sama wartość nie kwalifikuje ani nie dyskwalifikuje z operacji.</p></Reason><Reason question="Czy można przeliczyć wapń całkowity na zjonizowany?"><p>Nie ma stałego przelicznika. Ca zjonizowany wymaga pomiaru z uwzględnieniem pH i pobrania. Korekta o albuminę jest przybliżeniem Ca całkowitego, szczególnie zawodnym w ciężkiej chorobie i PChN.</p></Reason></Workbench>;
}
export function AdrenalImagingWorkbench() {
  const [native,N]=useState(20),[enhanced,E]=useState(100),[delayed,D]=useState(40),[homogeneous,H]=useState(true);
  const r=washout(native,enhanced,delayed);
  return <Workbench title="TK nadnercza: obliczenie i granice washout" source="adrenal"><div className="workbench-inputs"><NumberField label="Bez kontrastu (HU)" value={native} set={N} min={-100}/><NumberField label="Po kontraście (HU)" value={enhanced} set={E}/><NumberField label="Faza opóźniona (HU)" value={delayed} set={D} min={-100}/></div><label><input type="checkbox" checked={homogeneous} onChange={e=>H(e.target.checked)}/> Zmiana jednorodna</label><p className="workbench-result" aria-live="polite">APW {n(r?.absolute??null)}% · RPW {n(r?.relative??null)}%</p><p>APW = 100 × (E−D)/(E−N); RPW = 100 × (E−D)/E. Potrzebny jest właściwy protokół czasowy TK. Nieprawidłowe fazy lub brak wzmocnienia dają „—”; wyników nie przycinamy do 0–100%.</p><p>{homogeneous&&native<=10?'Jednorodna zmiana ≤10 HU odpowiada łagodnej zmianie w ocenie obrazowej ESE 2023. Ocenę hormonalną rozpatruje się osobno.':'Brak kryterium jednorodnej zmiany ≤10 HU. Dalsza ocena zależy od pełnego obrazu, wymiaru, wywiadu i hormonów.'}</p><Reason question="APW ≥60% / RPW ≥40%: czy gwarantuje łagodność?"><p>Nie. To tradycyjne progi o ograniczonej jakości dowodów; podobny washout może występować w innych guzach. Nie stosuj go do automatycznego rozpoznania ani jako zamiennika oceny niejednorodnej zmiany.</p></Reason></Workbench>;
}
export function DiabetesEmergencyWorkbench() {
  const [g,G]=useState(250),[na,N]=useState(136),[u,U]=useState(7),[k,K]=useState(4),[ph,P]=useState(7.2),[h,H]=useState(14),[pot,B]=useState(4),[known,Q]=useState(true);
  const r=hyperglycemicCriteria(g,na,u,k,ph,h,known);
  return <Workbench title="DKA i HHS: zbierz wszystkie kryteria" source="diabetes"><div className="workbench-inputs"><NumberField label="Glukoza (mg/dl)" value={g} set={G} max={1500}/><NumberField label="Na zmierzony (mmol/l)" value={na} set={N} max={200}/><NumberField label="Mocznik (mmol/l, nie BUN)" value={u} set={U} step={.1}/><NumberField label="β-hydroksymaślan (mmol/l)" value={k} set={K} step={.1}/><NumberField label="pH" value={ph} set={P} min={6} max={8} step={.01}/><NumberField label="HCO₃ (mmol/l)" value={h} set={H}/><NumberField label="Potas (mmol/l)" value={pot} set={B} step={.1} max={10}/></div><label><input type="checkbox" checked={known} onChange={e=>Q(e.target.checked)}/> Wcześniej rozpoznana cukrzyca</label><div className="workbench-results" aria-live="polite"><p>DKA <strong>{r?(r.dka?'Kryteria spełnione':'Nie wszystkie kryteria'):'Brak danych'}</strong></p><p>HHS <strong>{r?(r.hhs?'Kryteria spełnione':r.mixed?'Cechy obrazu mieszanego':'Nie wszystkie kryteria'):'Brak danych'}</strong></p><p>Osmolalność obliczona <strong>{n(r?.effective??null)} efektywna / {n(r?.total??null)} całkowita (mOsm/kg)</strong></p></div><p>Efektywna: 2 × Na + glukoza/18; całkowita: dodatkowo mocznik w mmol/l. DKA: cukrzyca lub glukoza ≥200, ketony ≥3 i pH &lt;7,3 lub HCO₃ &lt;18. HHS wymaga glukozy ≥600, hiperosmolalności i braku istotnej ketonemii/kwasicy.</p><p>{!Number.isFinite(pot)?'Brakuje oznaczenia potasu.':pot<3.5?'K <3,5 mmol/l: w leczeniu DKA najpierw uzupełnia się potas; insulinę odracza się do wzrostu K >3,5.':'Potas wymaga seryjnych pomiarów: wartość wyjściowa nie opisuje zapasów ustrojowych.'}</p><Reason question="Dlaczego nie wybieramy z góry płynu hipotonicznego ani dawki insuliny?"><p>Płyny, tempo podaży i insulinę dobiera się do krążenia, nerek, wieku, potasu i zmian osmolalności. Początkowo zwykle stosuje się krystaloid izotoniczny lub zbilansowany. Ćwiczenie sprawdza kryteria, nie generuje zleceń.</p></Reason></Workbench>;
}
export function NenGradeWorkbench() {
  const [ki,K]=useState(65),[mit,M]=useState(4),[diff,D]=useState<'well'|'poor'|'unknown'>('well'),[site,S]=useState<'digestive'|'lung'>('digestive');
  return <Workbench title="NEN: zróżnicowanie ≠ proliferacja" source="nen"><div className="workbench-inputs"><NumberField label="Ki‑67 (%)" value={ki} set={K} max={100} step={.1}/><NumberField label="Mitozy / 2 mm²" value={mit} set={M}/><label>Morfologia<select value={diff} onChange={e=>D(e.target.value as typeof diff)}><option value="well">Dobrze zróżnicowana</option><option value="poor">Słabo zróżnicowana</option><option value="unknown">Brak oceny</option></select></label><label>Narząd<select value={site} onChange={e=>S(e.target.value as typeof site)}><option value="digestive">Układ pokarmowy / trzustka</option><option value="lung">Płuco</option></select></label></div><p className="workbench-result" aria-live="polite">{gepGrade(ki,mit,diff,site)}</p><Reason question="Dlaczego Ki‑67 65% nie musi oznaczać NEC?"><p>NET G3 zachowuje dobre zróżnicowanie. Rozpoznanie NEC wymaga morfologii; sama martwica lub próg 55% nie wystarcza. Dla dobrze zróżnicowanych GEP-NET przy rozbieżności indeksów przyjmuje się wyższy stopień. Rakowiaki płuca mają odrębne zasady.</p></Reason><Reason question="Czy SSTR+, eGFR i MGMT wystarczą do wyboru leczenia?"><p>Nie. Potrzebne są m.in. lokalizacja, stadium, dynamika, heterogenność wychwytu, rezerwa szpiku, ocena nerek zgodna z ChPL i cele terapii. MGMT nie wylicza indywidualnego procentu odpowiedzi na CAPTEM. Profilaktyka oktreotydem nie gwarantuje braku przełomu okołooperacyjnego.</p></Reason></Workbench>;
}
export function PrrtWorkbench() {
  const [activity,A]=useState(7.4),[coefficient,C]=useState(.6),[prior,P]=useState(8);
  const valid=[activity,coefficient,prior].every(x=>Number.isFinite(x)&&x>=0);
  return <Workbench title="PRRT: aktywność ≠ dawka pochłonięta" source="prrt"><div className="workbench-inputs"><NumberField label="Podana aktywność (GBq)" value={activity} set={A} max={20} step={.1}/><NumberField label="Współczynnik z dozymetrii (Gy/GBq)" value={coefficient} set={C} max={10} step={.01}/><NumberField label="Suma wcześniejszych dawek na narząd (Gy)" value={prior} set={P} max={100} step={.1}/></div><p className="workbench-result" aria-live="polite">Dawka w tym cyklu: {n(valid?activity*coefficient:null)} Gy · suma {n(valid?prior+activity*coefficient:null)} Gy</p><p>Wartości początkowe to fikcyjny przykład rachunkowy. Współczynnik musi pochodzić z indywidualnej dozymetrii danego narządu; nie da się wyznaczyć go z samego eGFR. Nie wolno zakładać, że jest taki sam w każdym cyklu.</p><Reason question="Czy aminokwasy automatycznie podnoszą dopuszczalny limit dawki?"><p>Lizyna i arginina zmniejszają wychwyt nerkowy. Nie działają jak przełącznik bezpiecznego progu 23 → 28 Gy. Ocenia się protokół, dozymetrię, funkcję nerek, szpik i wcześniejsze leczenie; widget nie wydaje kwalifikacji.</p></Reason></Workbench>;
}
export function WeightWorkbench() {
  const [w,W]=useState(105),[end,E]=useState(95),[height,H]=useState(170);
  const valid=[w,end,height].every(x=>Number.isFinite(x)&&x>0),bmi=valid?w/(height/100)**2:null;
  return <Workbench title="Masa ciała: oceniaj zaobserwowaną zmianę" source="weight"><div className="workbench-inputs"><NumberField label="Masa początkowa (kg)" value={w} set={W} step={.1}/><NumberField label="Masa kontrolna (kg)" value={end} set={E} step={.1}/><NumberField label="Wzrost (cm)" value={height} set={H} min={50} max={250}/></div><p className="workbench-result" aria-live="polite">BMI początkowe {n(bmi)} kg/m² · utrata masy {n(valid?100*(w-end)/w:null)}%</p><p>Ujemny procent oznacza przyrost. BMI nie mierzy składu ciała. Odnotuj czas obserwacji, tolerancję, odżywienie i wyniki metaboliczne.</p><Reason question="Dlaczego nie prognozujemy masy po samym wyborze leku lub operacji?"><p>Średni efekt w badaniu nie jest odpowiedzią konkretnej osoby. Zmiany wydatku energetycznego, apetytu, dawki, czasu i przestrzegania leczenia są złożone. Stały mnożnik procentowy nie jest modelem Halla. Ćwiczenie liczy faktyczną zmianę, a źródło prowadzi do modelu NIDDK.</p></Reason></Workbench>;
}
export function TumorGrowthWorkbench() {
  const [a,A]=useState(20),[b,B]=useState(25),[days,D]=useState(180);
  return <Workbench title="Kinetyka guza: średnica a objętość" source="nen"><div className="workbench-inputs"><NumberField label="Średnica początkowa (mm)" value={a} set={A}/><NumberField label="Średnica kontrolna (mm)" value={b} set={B}/><NumberField label="Odstęp (dni)" value={days} set={D}/></div><p className="workbench-result">Czas podwojenia objętości: {n(volumeDoubling(a,b,days),0)} dni</p><p>Założenia: kula, porównywalne pomiary, stały wzrost wykładniczy; DT = Δt × ln2 / ln((d₂/d₁)³). „—”: brak wzrostu albo nieprawidłowe dane. To nie prognoza dalszego przebiegu.</p><Reason question="Czy jedna średnica wystarcza do RECIST 1.1?"><p>Nie. Ocenia się sumę zmian docelowych, właściwe odniesienie (baseline lub nadir), zmiany niedocelowe i nowe ogniska. Sam Ki‑67 również nie wyznacza czasu podwojenia.</p></Reason></Workbench>;
}
