export interface LatexFormulaPreset {
  id: string;
  title: string;
  module: 'tarczyca' | 'przysadka' | 'nadnercza' | 'przytarczyce' | 'cukrzyca' | 'gonady' | 'nen' | 'otylosc';
  tex: string;
  description: string;
}

export const ENDO_FORMULA_PRESETS: LatexFormulaPreset[] = [
  {
    id: 'lt4_css',
    title: 'Stężenie stacjonarne lewotyroksyny (Css)',
    module: 'tarczyca',
    tex: 'C_{ss} = \\frac{F \\cdot D}{V_d \\cdot k_e \\cdot \\tau}',
    description: 'Zależność stężenia stacjonarnego od dawki D, dostępności F, objętości Vd i stałej eliminacji ke.',
  },
  {
    id: 't4_ke_half',
    title: 'Stała eliminacji i czas półtrwania T4',
    module: 'tarczyca',
    tex: 'k_e = \\frac{\\ln(2)}{t_{1/2}} \\approx \\frac{0{,}693}{7\\text{ dni}} \\approx 0{,}099\\text{ d}^{-1}',
    description: 'Kinetyka pierwszego rzędu eliminacji tyroksyny przy t1/2 = 7 dni.',
  },
  {
    id: 'spina_gt',
    title: 'Wskaźnik SPINA-GT (wydolność tarczycy)',
    module: 'tarczyca',
    tex: '\\hat{G}_T = \\frac{\\beta_T (D_T + [TSH])(1 + K_{41}[TBG] + K_{42}[TTR])[FT_4]}{\\alpha_T [TSH]}',
    description: 'Maksymalna teoretyczna zdolność sekrecyjna gruczołu tarczowego wyprowadzona z modelu Michaelisa-Menten.',
  },
  {
    id: 'goodwin_oscillator',
    title: 'Układ oscylatora Goodwina (sprzężenie ujemne)',
    module: 'przysadka',
    tex: '\\begin{cases} \\frac{dX}{dt} = \\frac{a}{1 + k Z^n} - b X \\\\[6pt] \\frac{dY}{dt} = c X - d Y \\\\[6pt] \\frac{dZ}{dt} = e Y - f Z \\end{cases}',
    description: 'Nieliniowy model pulsacyjności przysadkowej: GnRH (X), gonadotropina (Y) i steroid obwodowy (Z).',
  },
  {
    id: 'edelman_equation',
    title: 'Równanie Edelmana (natremia osoczowa)',
    module: 'przysadka',
    tex: '[Na^+]_{osocze} = \\frac{Na_e + K_e}{\\text{TBW}}',
    description: 'Fizykochemiczny bilans sodu i potasu wymiennego w stosunku do całkowitej wody ustrojowej (TBW).',
  },
  {
    id: 'adrogue_madias',
    title: 'Wzór Adrogué-Madiasa (korekta hiponatremii)',
    module: 'przysadka',
    tex: '\\Delta [Na^+] = \\frac{[Na^+]_{\\text{infuzja}} + [K^+]_{\\text{infuzja}} - [Na^+]_{osocze}}{\\text{TBW} + 1}',
    description: 'Przewidywany przyrost stężenia sodu w surowicy po infuzji 1 litra płynu infuzyjnego.',
  },
  {
    id: 'free_water_clearance',
    title: 'Klirens wolnej wody (CH2O)',
    module: 'przysadka',
    tex: 'C_{H_2O} = V \\cdot \\left(1 - \\frac{U_{osm}}{P_{osm}}\\right)',
    description: 'Ilość wolnej wody traconej lub zatrzymywanej przez nerki w diagnostyce moczówki i SIADH.',
  },
  {
    id: 'cah_michaelis',
    title: 'Kinetyka Michaelisa-Menten w deficycie CYP21A2',
    module: 'nadnercza',
    tex: 'V = \\frac{V_{max} \\cdot [S]}{K_m + [S]} = \\frac{k_{cat} [E]_{tot} \\cdot [17\\text{-OHP}]}{K_m + [17\\text{-OHP}]}',
    description: 'Szybkość hydroksylacji C-21 w zależności od aktywności resztkowej enzymu i akumulacji 17-OHP.',
  },
  {
    id: 'lineweaver_burk',
    title: 'Podwójne odwrotności Lineweavera-Burka',
    module: 'nadnercza',
    tex: '\\frac{1}{V} = \\frac{K_m}{V_{max}} \\cdot \\frac{1}{[S]} + \\frac{1}{V_{max}}',
    description: 'Linearyzacja kinetyki enzymatycznej — spadek Vmax przesuwa punkt przecięcia 1/Vmax ku górze.',
  },
  {
    id: 'arr_ratio',
    title: 'Wskaźnik aldosteron-renina (ARR)',
    module: 'nadnercza',
    tex: 'ARR = \\frac{\\text{PAC}}{\\text{PRA}} = \\frac{\\text{PAC}}{\\frac{\\text{DRC}}{8{,}2}} > 30 \\quad \\left[\\frac{\\text{ng/dl}}{\\text{ng/ml/h}}\\right]',
    description: 'Screening w kierunku pierwotnego hiperaldosteronizmu przy jednoczesnym warunku PAC > 10 ng/dl.',
  },
  {
    id: 'casr_hill_equation',
    title: 'Równanie Hilla dla supresji PTH przez CaSR',
    module: 'przytarczyce',
    tex: 'PTH([Ca^{2+}]) = PTH_{min} + \\frac{PTH_{max} - PTH_{min}}{1 + \\left(\\frac{[Ca^{2+}]}{EC_{50}}\\right)^{n_H}}, \\quad n_H \\approx 3{,}8',
    description: 'Stroma sigmoida kooperatywności receptora CaSR. Set-point EC50 wynosi fizjologicznie 1,21 mmol/L.',
  },
  {
    id: 'cccr_clearance_ratio',
    title: 'Klirens wapniowo-kreatyninowy (CCCR / FeCa)',
    module: 'przytarczyce',
    tex: 'CCCR = \\frac{Cl_{Ca}}{Cl_{Cr}} = \\frac{U_{Ca} \\cdot S_{Cr}}{S_{Ca} \\cdot U_{Cr}}',
    description: 'Różnicowanie FHH (CCCR < 0,01) od pierwotnej nadczynności przytarczyc PHPT (CCCR > 0,02).',
  },
  {
    id: 'qtc_formulas',
    title: 'Korekcja QT: Wzór Bazetta i Fridericia',
    module: 'przytarczyce',
    tex: 'QTc_{Bazett} = \\frac{QT}{\\sqrt{RR}}, \\qquad QTc_{Fridericia} = \\frac{QT}{\\sqrt[3]{RR}} \\quad (RR \\text{ w sekundach})',
    description: 'Wzór Fridericia zapobiega fałszywemu przeszacowaniu odstępu QT w hipokalcemii z tachykardią.',
  },
  {
    id: 'hydroxyapatite_bone',
    title: 'Stechiometria krystalizacji hydroksyapatytu',
    module: 'przytarczyce',
    tex: '10\\,Ca^{2+} + 6\\,HPO_4^{2-} + 2\\,H_2O \\longrightarrow Ca_{10}(PO_4)_6(OH)_2 \\downarrow + 8\\,H^+',
    description: 'Gwałtowny spadek Ca2+ i PO4 w zespole głodnych kości (HBS) po operacji przytarczyc.',
  },
  {
    id: 'bergman_minimal_model',
    title: 'Minimal Model Bergmana (dynamika glukoza-insulina)',
    module: 'cukrzyca',
    tex: '\\begin{cases} \\frac{dG}{dt} = -(p_1 + X)G + p_1 G_b \\\\[6pt] \\frac{dX}{dt} = -p_2 X + p_3 (I - I_b) \\end{cases}',
    description: 'Układ nieliniowych równań różniczkowych modelujący klirens glukozy i aktywność insuliny śródtkankowej.',
  },
  {
    id: 'homa_ir_index',
    title: 'Wskaźnik insulinooporności HOMA-IR',
    module: 'cukrzyca',
    tex: '\\text{HOMA-IR} = \\frac{G_0 \\cdot I_0}{22{,}5} \\quad (G_0 \\text{ [mmol/l]}, I_0 \\text{ [}\\mu\\text{U/ml]})',
    description: 'Ilościowy wskaźnik insulinooporności na czczo; wartość > 2,5 wskazuje na istotną oporność tkanek.',
  },
  {
    id: 'isf_rule_1800',
    title: 'Współczynnik wrażliwości na insulinę (ISF — Reguła 1800)',
    module: 'cukrzyca',
    tex: '\\text{ISF} = \\frac{1800}{\\text{TDD}} \\quad \\left[\\frac{\\text{mg/dl}}{\\text{j.}}\\right] \\qquad \\text{lub} \\qquad \\text{ISF} = \\frac{100}{\\text{TDD}} \\quad \\left[\\frac{\\text{mmol/l}}{\\text{j.}}\\right]',
    description: 'Przewidywany spadek glikemii po podaniu 1 jednostki insuliny szybkodziałającej w bolusie.',
  },
  {
    id: 'icr_rule_500',
    title: 'Wskaźnik węglowodanowo-insulinowy (ICR — Reguła 500)',
    module: 'cukrzyca',
    tex: '\\text{ICR} = \\frac{500}{\\text{TDD}} \\quad \\left[\\frac{\\text{g węglowodanów}}{\\text{j. insuliny}}\\right]',
    description: 'Liczba gramów węglowodanów zrównoważona przez 1 jednostkę insuliny prandialnej.',
  },
  {
    id: 'katz_sodium',
    title: 'Skorygowane stężenie sodu w hiperglikemii (wzór Katza)',
    module: 'cukrzyca',
    tex: '[Na^+]_{\\text{skorygowany}} = [Na^+] + 0{,}016 \\cdot (G - 100) \\quad (G \\text{ w mg/dl})',
    description: 'Korekta rzekomej hiponatremii wywołanej przesunięciem wody z komórek do hiperosmolalnego osocza.',
  },
  {
    id: 'anion_gap_dka',
    title: 'Luka anionowa w kwasicy ketonowej (Anion Gap)',
    module: 'cukrzyca',
    tex: '\\text{AG} = [Na^+] - \\left([Cl^-] + [HCO_3^-]\\right) > 12\\,\\text{mmol/l}',
    description: 'Wskaźnik kwasicy metabolicznej ze zwiększoną luką anionową (HAGMA) w przebiegu DKA.',
  },
  {
    id: 'effective_osmolality_hhs',
    title: 'Efektywna osmolalność osocza w zespole HHS',
    module: 'cukrzyca',
    tex: 'P_{\\text{osm, eff}} = 2\\,[Na^+] + \\frac{G\\text{ [mg/dl]}}{18} > 320\\,\\text{mOsm/kg H}_2\\text{O}',
    description: 'Kryterium rozpoznania zespołu hiperglikemiczno-hiperosmolarnego (HHS); nie uwzględnia swobodnie dyfundującego mocznika.',
  },
  {
    id: 'vermeulen_quadratic',
    title: 'Równanie kwadratowe Vermeulena (wolny testosteron)',
    module: 'gonady',
    tex: 'a [T_{\\text{free}}]^2 + b [T_{\\text{free}}] + c = 0 \\quad \\Longrightarrow \\quad [T_{\\text{free}}] = \\frac{-b + \\sqrt{b^2 - 4ac}}{2a}',
    description: 'Analityczne rozwiązanie prawa działania mas dla równowagi testosteronu z SHBG (Ks) i albuminą (Ka).',
  },
  {
    id: 'fai_formula',
    title: 'Wskaźnik wolnych androgenów (FAI)',
    module: 'gonady',
    tex: '\\text{FAI} = \\frac{100 \\times T_{\\text{total}} [\\text{nmol/l}]}{\\text{SHBG} [\\text{nmol/l}]}',
    description: 'Przybliżony wskaźnik frakcji biodostępnej androgenów; traci liniowość przy SHBG < 15 lub > 85 nmol/l.',
  },
  {
    id: 'gnrh_pulse_delay_ode',
    title: 'Generator pulsów GnRH (delay ODE)',
    module: 'gonady',
    tex: '\\frac{dx}{dt} = \\frac{V_0}{1 + \\left(\\frac{y(t-\\tau)}{K_i}\\right)^n} - k_x x(t)',
    description: 'Pulsacyjność GnRH (x) wynikająca z bifurkacji Hopfa przy opóźnionym ujemnym sprzężeniu testosteronu (y).',
  },
  {
    id: 'cyp19a1_aromatization',
    title: 'Stechiometria aromatyzacji CYP19A1',
    module: 'gonady',
    tex: '\\text{Androstendion} + 3\\,\\text{NADPH} + 3\\,\\text{H}^+ + 3\\,\\text{O}_2 \\longrightarrow \\text{Estron} + \\text{HCOOH} + 3\\,\\text{NADP}^+ + 4\\,\\text{H}_2\\text{O}',
    description: 'Trzy kolejne utlenienia grupy C19 z eliminacją mrówczanu HCOOH i aromatyzacją pierścienia A do fenolu.',
  },
  {
    id: 'prrt_mird_dose',
    title: 'Dozymetria nerkowa PRRT (MIRD)',
    module: 'nen',
    tex: 'D_{\\text{kidney}} = \\tilde{A} \\cdot S = \\int_0^{\\infty} A(t)\\,dt \\cdot S \\le 23\\text{ Gy (lub } 28\\text{ Gy z Arg/Lys)}',
    description: 'Całka aktywności kumulowanej lutetu-177 i współczynnik geometryczny S określające limit tolerancji miąższu nerkowego.',
  },
  {
    id: 'tumor_doubling_time',
    title: 'Czas podwojenia objętości guza (Tumor Doubling Time)',
    module: 'nen',
    tex: 'DT = \\frac{\\Delta t \\cdot \\ln 2}{\\ln(V_2 / V_1)} = \\frac{\\Delta t \\cdot \\ln 2}{3 \\cdot \\ln(d_2 / d_1)}',
    description: 'Matematyczny czas potrzebny na podwojenie masy guza neuroendokrynnego obliczony ze średnic d1 i d2 w badaniach obrazowych.',
  },
  {
    id: 'tryptophan_serotonin_pathway',
    title: 'Kaskada biosyntezy serotoniny i 5-HIAA',
    module: 'nen',
    tex: '\\text{L-Tryptofan} \\xrightarrow[\\text{BH}_4]{\\text{TPH1}} 5\\text{-HTP} \\xrightarrow[\\text{PLP}]{\\text{AADC}} \\text{Serotonina (5-HT)} \\xrightarrow[\\text{FAD}]{\\text{MAO-A}} 5\\text{-HIAA}',
    description: 'Enzymatyczny szlak przekształcenia tryptofanu w komórkach rakowiaka pod wpływem hydroksylazy TPH1 i rozpadu do kwasu 5-HIAA.',
  },
  {
    id: 'recist_pd_threshold',
    title: 'Kryterium progresji RECIST 1.1 dla zmian tarczowych',
    module: 'nen',
    tex: '\\Delta \\sum D = \\frac{\\sum D_{\\text{aktualne}} - \\sum D_{\\text{nadir}}}{\\sum D_{\\text{nadir}}} \\cdot 100\\% \\ge +20\\% \\quad (\\text{oraz } \\ge 5\\text{ mm bezwzględnie})',
    description: 'Procentowy wzrost sumy największych wymiarów ognisk mierzalnych kwalifikujący do progresji choroby i zmiany linii leczenia.',
  },
  {
    id: 'hall_energy_balance',
    title: 'Model dynamiczny wydatku energetycznego Halla',
    module: 'otylosc',
    tex: '\\frac{d(\\text{BW})}{dt} = \\frac{\\text{EI}(t) - \\text{EE}(\\text{BW}, t)}{\\rho_{\\text{eff}}}, \\quad \\text{EE} = \\text{BMR}_0 + \\alpha \\cdot \\Delta \\text{BW} + \\beta \\cdot \\text{EI}',
    description: 'Równanie różniczkowe bilansu masy ciała uwzględniające nieliniowy spadek BMR i termogenezę adaptacyjną.',
  },
  {
    id: 'friedewald_sampson',
    title: 'Formuła Friedewalda i Sampsona (LDL-C)',
    module: 'otylosc',
    tex: '\\text{LDL-C}_{\\text{Friedewald}} = \\text{TC} - \\text{HDL-C} - \\frac{\\text{TG}}{5} \\quad (\\text{dla TG} < 400\\text{ mg/dl})',
    description: 'Estymacja cholesterolu frakcji LDL w oparciu o stężenie VLDL-C szacowane jako TG/5.',
  },
  {
    id: 'bariatric_ewl_tbwl',
    title: 'Wskaźniki ubytku masy ciała: %EWL i %TBWL',
    module: 'otylosc',
    tex: '\\%EWL = \\frac{W_0 - W_t}{W_0 - W_{\\text{ideal}}} \\cdot 100\\%, \\qquad \\%TBWL = \\frac{W_0 - W_t}{W_0} \\cdot 100\\%',
    description: 'Miary skuteczności procedur bariatrycznych (%EWL: nadmiar masy, %TBWL: całkowita masa wyjściowa).',
  },
  {
    id: 'fib4_nafld_index',
    title: 'Wskaźnik zwłóknienia wątroby FIB-4',
    module: 'otylosc',
    tex: '\\text{FIB-4} = \\frac{\\text{Wiek [lata]} \\cdot \\text{AST [U/l]}}{\\text{Płytki krwi [}10^9\\text{/l]} \\cdot \\sqrt{\\text{ALT [U/l]}}}',
    description: 'Nieinwazyjny wskaźnik zaawansowanego zwłóknienia wątroby w przebiegu MASLD/MASH (odcięcie: < 1,30 oraz > 2,67).',
  },
];


export const QUICK_SYMBOLS = [
  { label: 'ułamek', tex: '\\frac{a}{b}' },
  { label: 'dC/dt', tex: '\\frac{dC}{dt}' },
  { label: '√x', tex: '\\sqrt{x}' },
  { label: '∛x', tex: '\\sqrt[3]{x}' },
  { label: 'lim', tex: '\\lim_{x \\to 0}' },
  { label: '∫ całka', tex: '\\int_{0}^{\\infty} f(t)\\,dt' },
  { label: 'α', tex: '\\alpha' },
  { label: 'β', tex: '\\beta' },
  { label: 'θ', tex: '\\theta' },
  { label: 'λ', tex: '\\lambda' },
  { label: 'Δ', tex: '\\Delta' },
  { label: 'Ca²', tex: '[Ca^{2+}]' },
  { label: 'Vmax', tex: 'V_{max}' },
  { label: 'Km', tex: 'K_m' },
  { label: 'Css', tex: 'C_{ss}' },
  { label: 't½', tex: 't_{1/2}' },
  { label: 'ĜT', tex: '\\hat{G}_T' },
  { label: '→', tex: '\\longrightarrow' },
  { label: '↓', tex: '\\downarrow' },
  { label: '≈', tex: '\\approx' },
];
