'use client';
import { useState } from 'react';
import { NumberField, Reason, Workbench } from './clinical-workbench';

const f=(v:number)=>Number.isFinite(v)?v.toFixed(2):'—';
export function ThyroidWorkbench() {
  const [t,T]=useState(2.1),[t4,F]=useState(15.2),[pattern,P]=useState('primary');
  const scenarios:Record<string,[string,string,string]>={
    primary:['Pierwotna niedoczynność','Uszkodzenie tarczycy → spadek FT4 → wzrost TSH','Przysadka odpowiada na brak sprzężenia. W pierwotnej niedoczynności TSH zwykle służy do kontroli leczenia; odpowiedź jest opóźniona.'],
    central:['Centralna niedoczynność','Zaburzenie przysadki/podwzgórza → nieadekwatny sygnał → spadek FT4','Prawidłowe lub nieznacznie podwyższone TSH nie wyklucza centralnej niedoczynności. Oceniaj FT4 i inne osie, w tym kortyzol przed substytucją tarczycową.'],
    graves:['Graves–Basedow','TRAb pobudza TSHR → wzrost syntezy → spadek TSH','Tiamazol hamuje syntezę. Nie opróżnia natychmiast zapasów hormonu; TSH może długo pozostawać niskie.'],
    thyroiditis:['Zapalenie destrukcyjne','Uszkodzenie pęcherzyka → uwolnienie zapasów → spadek TSH','Tyreotoksykoza nie zawsze oznacza zwiększoną syntezę. Tyreostatyk nie blokuje uwalniania już wytworzonych zapasów.'],
  };
  return <Workbench title="Oś HPT: przewidź kierunek, sprawdź mechanizm"><label>Scenariusz<select value={pattern} onChange={e=>P(e.target.value)}>{Object.entries(scenarios).map(([key,v])=><option key={key} value={key}>{v[0]}</option>)}</select></label><p className="workbench-result" aria-live="polite">{scenarios[pattern][1]}</p><Reason key={pattern} question="Wyjaśnij konsekwencję dla diagnostyki lub leczenia"><p>{scenarios[pattern][2]}</p></Reason><div className="workbench-inputs"><NumberField label="TSH zmierzone (mIU/l)" value={t} set={T} step={.01}/><NumberField label="FT4 zmierzone (pmol/l)" value={t4} set={F} step={.1}/></div><p>Indeks Jostela: ln(TSH) + 0,1345 × FT4 = {t>0&&t4>0?f(Math.log(t)+.1345*t4):'—'}. To wskaźnik badawczy, bez automatycznej diagnozy.</p><p>Nie przeliczamy dawki LT4/tiamazolu na FT4. Interpretacja wymaga zakresów laboratorium, czasu pobrania, leków, ciąży i stanu klinicznego.</p><p><a href="https://www.eurothyroid.com/guidelines/eta_guidelines.html" target="_blank" rel="noreferrer">ETA — wytyczne tarczycowe</a> · <a href="https://pubmed.ncbi.nlm.nih.gov/19226261/" target="_blank" rel="noreferrer">Jostel i wsp. 2009 — TSH index</a></p></Workbench>;
}
export function WaterWorkbench() {
  const [v,V]=useState(3),[u,U]=useState(100),[p,P]=useState(290);
  const valid=Number.isFinite(v)&&v>=0&&Number.isFinite(u)&&u>=0&&Number.isFinite(p)&&p>0;
  return <Workbench title="Woda: klirens osmolalny a wolnej wody"><div className="workbench-inputs"><NumberField label="Diureza (l/dobę)" value={v} set={V} step={.1}/><NumberField label="Osmolalność moczu (mOsm/kg)" value={u} set={U}/><NumberField label="Zmierzona osmolalność osocza (mOsm/kg)" value={p} set={P}/></div><p className="workbench-result" aria-live="polite">Cₒₛₘ: {valid?f(v*u/p):'—'} l/dobę · C_H₂O: {valid?f(v*(1-u/p)):'—'} l/dobę</p><p>Cₒₛₘ = V × Uₒₛₘ/Pₒₛₘ; C_H₂O = V − Cₒₛₘ. Stosujemy standardowe przybliżenie gęstości moczu do 1 kg/l.</p><Reason question="Czy dodatni klirens rozpoznaje niedobór wazopresyny?"><p>Nie. Oznacza wydalanie moczu hipotonicznego względem osocza; różnicowanie obejmuje polidypsję, niedobór i oporność na AVP. Ten wzór nie jest klirensem wody wolnej od elektrolitów, do którego potrzebne są Na i K w moczu. Diureza osmotyczna nie oznacza automatycznie dodatniego C_H₂O.</p></Reason><p>Nie wyliczamy tempa korekcji sodu ani dawki desmopresyny; wymagają seryjnych pomiarów i oceny ryzyka.</p></Workbench>;
}
export function InsulinMathWorkbench() {
  const [g,G]=useState(90),[i,I]=useState(10),[fast,F]=useState(true);
  const valid=fast&&Number.isFinite(g)&&g>0&&Number.isFinite(i)&&i>0;
  return <Workbench title="HOMA‑1: znaczenie warunków pobrania"><div className="workbench-inputs"><NumberField label="Glukoza na czczo (mg/dl)" value={g} set={G}/><NumberField label="Insulina na czczo (µU/ml)" value={i} set={I} step={.1}/></div><label><input type="checkbox" checked={fast} onChange={e=>F(e.target.checked)}/> Stabilny stan na czczo, bez egzogennej insuliny</label><p className="workbench-result">HOMA‑IR {valid?f(g*i/405):'—'} · HOMA‑B {valid&&g/18>3.5?f(20*i/(g/18-3.5)):'—'}%</p><p>HOMA‑IR = G × I / 405; HOMA‑B = 20 × I / (G/18 − 3,5). Brak wyniku HOMA‑B przy G ≤63 mg/dl. Nie ma jednego uniwersalnego progu HOMA‑IR dla wszystkich populacji i oznaczeń.</p><Reason question="Czy to model Bergmana albo kalkulator bolusa?"><p>Nie. Model Bergmana wymaga dynamicznych danych i estymacji parametrów. HOMA opisuje stan podstawowy. Reguły 500/TDD i 1800/TDD są punktami wyjścia do indywidualnej oceny; bez aktywnej insuliny, trendu, wysiłku i kontekstu nie wyznaczają bezpiecznego bolusa. Większe ICR w g/j. oznacza mniej insuliny na tę samą ilość węglowodanów.</p></Reason><Reason question="Dlaczego cztery godziny wykresu nie są raportem AGP?"><p>Krótki, syntetyczny posiłek nie określa GMI ani długoterminowego wyrównania. Ocena CGM zwykle wymaga około 14 dni z co najmniej 70% dostępnych danych, reprezentatywnych dla codzienności. Hipoglikemie ocenia się również indywidualnie.</p></Reason><p><a href="https://www.dtu.ox.ac.uk/homacalculator/" target="_blank" rel="noreferrer">Oxford — HOMA i ograniczenia</a> · <a href="https://doi.org/10.2337/dci19-0028" target="_blank" rel="noreferrer">Konsensus CGM 2019</a></p></Workbench>;
}
export function MechanismWorkbench({system}:{system:'pituitary'|'adrenal'|'nen'|'bone'}) {
  const [selected,S]=useState(0);
  const content={
    pituitary:[['Dopamina i PRL','Dopamina —| laktotrofy → prolaktyna','Przerwanie dopaminergicznego hamowania może podnieść PRL. Wielkość guza nie wylicza stężenia; uwzględnij leki, makroprolaktynę i efekt haka.'],['GH / IGF‑1','Pulsacyjne GH → wątroba i tkanki → IGF‑1 —| oś','Pojedyncze GH jest zmienne. Interpretuj IGF‑1 względem wieku i metody; dalsze testy dobierz do pytania klinicznego. Kallmann dotyczy GnRH, nie izolowanego braku pulsów GH.'],['Niedoczynność wieloosiowa','Przysadka → ACTH / TSH / LH–FSH → gruczoły obwodowe','Oceń hormony tropowe razem z obwodowymi. Przy podejrzeniu niedoboru ACTH uwzględnij zabezpieczenie osi kortyzolowej przed LT4.']],
    adrenal:[['Kortyzol','CRH → ACTH → kortyzol —| CRH / ACTH','Pierwotny niedobór kortyzolu podnosi ACTH; niedobór centralny daje ACTH nieadekwatne. W centralnym niedoborze aldosteron bywa zachowany.'],['Aldosteron','Renina → angiotensyna II → aldosteron → retencja Na, wydalanie K','ARR zależy od oznaczenia reniny: aktywność (ng/ml/h) i stężenie bezpośrednie (mIU/l) mają inne progi. Nie przenoś progu 20–30 między jednostkami. Oceniaj też sam aldosteron, K, leki i warunki pobrania.'],['Guz chromochłonny','Katecholaminy → receptory α / β → krążenie','W przygotowaniu do planowej operacji blokada β bez odpowiedniego zabezpieczenia α może być niebezpieczna. Suwak wydzielania nie przewiduje ciśnienia.'],['Przełom nadnerczowy','Niedobór kortyzolu + stres → zagrożenie krążenia','Pilne postępowanie kliniczne obejmuje hydrokortyzon i płyny; leczenia nie opóźnia się dla potwierdzenia rozpoznania. Pomiary hemodynamiki i elektrolitów zastępują fikcyjne przyrosty po litrze płynu.']],
    nen:[['Tryptofan','Tryptofan → serotonina → 5‑HIAA','Zwiększona synteza serotoniny może ograniczać dostępność tryptofanu dla szlaku niacyny. Nie cała pozostała pula trafia do niacyny; nie da się wyliczyć flushingów lub 5‑HIAA z suwaka procentowego.'],['SSTR','Ekspresja SSTR → wiązanie analogu / radiopeptydu','Ekspresja i heterogenność w obrazowaniu są częścią oceny. Powinowactwo in vitro nie zastępuje kwalifikacji klinicznej ani dozymetrii.'],['MEN','Wariant patogenny → narządy zagrożone → nadzór','MEN1: przytarczyce, przysadka i NET trzustkowo-dwunastnicze. MEN2: RET, rak rdzeniasty i guz chromochłonny; PHPT może towarzyszyć MEN2A. Termin interwencji zależy od wariantu i pełnej oceny.']],
    bone:[['CaSR','Ca zjonizowany → CaSR —| PTH','Wzrost Ca hamuje PTH, a obniżenie Ca je pobudza przy zachowanej czynności gruczołów. Ilustracyjna krzywa nie odtwarza wyniku pacjenta.'],['Nerki','PTH → fosfaturia + synteza kalcytriolu','W PChN odpowiedź zależy od rezerwy nefronów; nie wolno mechanicznie ekstrapolować modelu zdrowych nerek.'],['Głodne kości','Spadek PTH po operacji → wychwyt minerałów przez kości','ALP może wskazywać nasilony obrót, ale sama nie wyznacza ciężkości ani liczby ampułek wapnia. Oceniaj seryjnie Ca, P, Mg, objawy i EKG.']],
  }[system];
  return <Workbench title="Połącz mechanizm z decyzją"><div className="atlas-presets">{content.map((item,index)=><button className="secondary" key={item[0]} aria-pressed={selected===index} onClick={()=>S(index)}>{item[0]}</button>)}</div><p className="workbench-result" aria-live="polite">{content[selected][1]}</p><Reason key={selected} question="Co z tego wynika w praktyce?">{content[selected][2]}</Reason></Workbench>;
}
