'use client';
import {useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,Check,CheckCircle2,Layers3,ClipboardCheck,ChartNoAxesCombined,ChevronRight} from 'lucide-react';
import {lessons,questions,flashcards,type Question} from '@/lib/course';
import {sampleQuestions} from '@/lib/learning';
import type {useLearning} from '@/lib/use-learning';
import {QuestionOptions,Runner} from './course-ui';
import type {Route} from './content-views';
type Learning=ReturnType<typeof useLearning>;
type Navigation=(route:Route)=>void;
export function CardsView({learning,go}:{learning:Learning;go:Navigation}){
 const {state,loading,saving,pending}=learning;const blocked=saving||loading||pending.length>0;
 const [queue,setQueue]=useState<string[]|null>(null);const [index,setIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [filter,setFilter]=useState('all');const [rated,setRated]=useState(false);const eventId=useRef('');
 const due=flashcards.filter(c=>state.reviews[c.id]&&new Date(state.reviews[c.id].dueAt)<=new Date());const fresh=flashcards.filter(c=>!state.reviews[c.id]);const card=queue?flashcards.find(c=>c.id===queue[index]):undefined;
 function start(){setQueue([...due,...fresh].filter(c=>filter==='all'||c.lessonId===filter).map(c=>c.id));setIndex(0);setFlipped(false);setRated(false);eventId.current=crypto.randomUUID();}
 async function rate(remembered:boolean){if(!card||blocked||rated)return;setRated(true);await learning.record('review',card.id,{remembered},eventId.current);}
 function next(){setIndex(i=>i+1);setFlipped(false);setRated(false);eventId.current=crypto.randomUUID();}
 return <div className="reading"><div className="page-heading"><p className="eyebrow">MNIEJ WKUWANIA, WIĘCEJ PAMIĘTANIA</p><h1>Wiedza, która zostaje</h1><p>Odpowiedz w myślach, odkryj kartę i oceń, czy pamiętasz.</p></div>{!queue?<section className="panel cards-start"><Layers3 size={40}/><h2>Twoja kolejka powtórek</h2><div className="review-stats"><span><strong>{due.length}</strong>do powtórki</span><span><strong>{fresh.length}</strong>nowych</span><span><strong>{60-fresh.length}</strong>rozpoczętych</span></div><label className="field">Temat<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Cała tarczyca</option>{lessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label><button className="primary" onClick={start} disabled={loading}>Rozpocznij sesję<ArrowRight size={17}/></button><p className="small">Kolejne powtórki po 1, 3, 7, 14 i 30 dniach. „Nie pamiętam” przywraca odstęp jednego dnia.</p></section>:card?<><div className="runner-progress"><span>Fiszka {index+1} z {queue.length}</span><button className="text-button" onClick={()=>setQueue(null)}>Zakończ sesję</button></div><div className="flashcard"><span className="eyebrow">{lessons.find(l=>l.id===card.lessonId)?.title}</span><Layers3 size={25}/><h2>{card.front}</h2>{flipped?<div className="card-answer" aria-live="polite"><p>{card.back}</p></div>:<button className="secondary" onClick={()=>setFlipped(true)}>Odkryj odpowiedź</button>}</div>{flipped&&(rated?<div className="card-rating"><p role="status">{pending.some(e=>e.id===eventId.current)?'Ocena czeka na zapis. Ponów zapis powyżej.':saving?'Zapisywanie…':'Ocena dodana. Kolejny termin ustalony.'}</p><button className="primary" disabled={blocked} onClick={next}>Następna fiszka<ArrowRight size={16}/></button></div>:<div className="card-rating"><button className="secondary" disabled={blocked} onClick={()=>void rate(false)}>Nie pamiętam</button><button className="primary" disabled={blocked} onClick={()=>void rate(true)}><Check size={17}/>Pamiętam</button></div>)}<button className="text-button" onClick={()=>go(`lesson/${card.lessonId}`)}>Wróć do lekcji i źródeł<ArrowUpRight size={15}/></button></>:<section className="panel empty-state"><CheckCircle2 size={42}/><h2>{queue.length?'Sesja zakończona':'Na dziś wszystko'}</h2><p>{queue.length?'Dobra praca. Terminy kolejnych powtórek znajdziesz poniżej.':'W tym temacie nie ma teraz nowych ani zaległych kart.'}</p><button className="secondary" onClick={()=>setQueue(null)}>Wybierz temat</button></section>}{Object.keys(state.reviews).length>0&&<section className="panel schedule-list"><h2>Najbliższe powtórki</h2>{Object.entries(state.reviews).sort((a,b)=>a[1].dueAt.localeCompare(b[1].dueAt)).slice(0,10).map(([id,r])=><div key={id}><span>{flashcards.find(c=>c.id===id)?.front??id}</span><time dateTime={r.dueAt}>{new Date(r.dueAt).toLocaleDateString('pl-PL')}</time></div>)}</section>}</div>
}
export function ExamView({learning,onActive}:{learning:Learning;onActive:(v:boolean)=>void}){
 const [bank,setBank]=useState<Question[]|null>(null);const [attempt,setAttempt]=useState(0);const running=useRef(false);
 const setActive=useRef((v:boolean)=>{running.current=v;onActive(v)}).current;
 return bank?<><Runner key={attempt} bank={bank} title="Tarczyca — egzamin końcowy" mode="exam" blocked={learning.saving||learning.loading||learning.pending.length>0} onActive={setActive} onFinish={(payload,id)=>learning.record('exam','tarczyca',payload,id)}/><div className="reading"><button className="text-button" onClick={()=>{if(running.current&&!window.confirm('Opuścić egzamin i utracić obecne odpowiedzi?'))return;setBank(null);onActive(false);}}>Wróć do ustawień egzaminu</button></div></>:<div className="reading"><div className="page-heading"><p className="eyebrow">SPRAWDŹ CAŁY MODUŁ</p><h1>Połącz wszystkie kropki</h1><p>Egzamin z tarczycy — sprawdź, co już rozumiesz, a do czego warto wrócić.</p></div><section className="panel exam-start"><div className="exam-icon"><ClipboardCheck size={37}/></div><h2>Gotowość do praktyki</h2><div className="exam-facts"><span><strong>30</strong>pytań z banku 60</span><span><strong>1</strong>poprawna odpowiedź</span><span><strong>Bez limitu</strong>czasu</span></div><ul><li>Pytania są losowane bez powtórzeń.</li><li>Możesz wracać do pytań i zmieniać wybory.</li><li>Wyjaśnienia zobaczysz dopiero po zakończeniu.</li><li>Wynik służy samoocenie; nie jest certyfikatem kompetencji.</li></ul><button className="primary" disabled={learning.loading} onClick={()=>{setBank(sampleQuestions(questions,30));setAttempt(k=>k+1);}}>Rozpocznij egzamin<ArrowRight size={18}/></button></section></div>
}
export function ResultsView({learning,go}:{learning:Learning;go:Navigation}){const [id,setId]=useState<string|null>(null);const attempt=learning.state.attempts.find(a=>a.id===id);return <><div className="page-heading"><p className="eyebrow">ZOBACZ SWÓJ POSTĘP</p><h1>Każda próba czegoś uczy</h1><p>{learning.user?'Historia Twoich ćwiczeń na koncie.':'Historia tej sesji gościa. Po odświeżeniu strony zostanie usunięta.'}</p></div>{attempt?<div className="reading"><button className="text-button" onClick={()=>setId(null)}><ArrowLeft size={16}/>Wszystkie wyniki</button><h2>{String(attempt.payload.title)}</h2><p>{Number(attempt.payload.correct)} / {Number(attempt.payload.total)} · {Number(attempt.payload.percent)}% · Wersja materiału {attempt.content_version}</p>{Array.isArray(attempt.payload.questions)&&(attempt.payload.questions as (Question&{selected:number})[]).map((q,i)=><section key={q.id} className="panel question-review"><p className="eyebrow">PYTANIE {i+1}</p><h3>{q.prompt}</h3><QuestionOptions question={q} selected={q.selected} reveal onSelect={()=>{}}/><button className="text-button" onClick={()=>go(`lesson/${q.lessonId}`)}>Powtórz temat i zobacz źródła<ArrowRight size={15}/></button></section>)}</div>:learning.state.attempts.length?<div className="results-list">{[...learning.state.attempts].reverse().map(a=><button key={a.id} className="result-row" onClick={()=>setId(a.id)}><span className="stat-icon teal"><ChartNoAxesCombined size={22}/></span><span><strong>{String(a.payload.title)}</strong><small>{a.kind==='exam'?'Egzamin':a.kind==='case'?'Przypadek':'Quiz'} · {new Date(a.created_at).toLocaleString('pl-PL')}</small></span><span className="result-score">{Number(a.payload.percent)}%<small>{Number(a.payload.correct)}/{Number(a.payload.total)}</small></span><ChevronRight size={19}/></button>)}</div>:<section className="panel empty-state"><ChartNoAxesCombined size={43}/><h2>Pierwszy wynik jeszcze przed Tobą</h2><p>Rozwiąż quiz po lekcji, przypadek lub egzamin.</p><button className="primary" onClick={()=>go('quiz/fizjologia')}>Rozwiąż pierwszy quiz<ArrowRight size={17}/></button></section>}</>}
