import type {GonadCaseDraft} from './cases-gonads-types.ts';
type Choice=[string,string];
const step=(context:string,prompt:string,a:Choice,b:Choice,c:Choice)=>({context,prompt,options:[a,b,c].map(([text,explanation])=>({text,explanation}))});
export const gahtCases:GonadCaseDraft[]=[
{id:'case-gaht-cpa-review-v2',lessonId:'gonady-trans-feminizujaca',title:'CPA i podwyższona prolaktyna: czego jeszcze brakuje?',patient:'Kobieta transpłciowa, 32 lata; jądra obecne',difficulty:'Zaawansowany',intro:'Fikcyjny przypadek. Estradiol przezskórny i CPA od 6 miesięcy. Kontrola wykazała PRL 72 ng/ml (zakres laboratorium 5–25). Pacjentka nie zgłasza zaburzeń widzenia.',steps:[
step('Brak ostrego bólu głowy. Nie zebrano pełnego wywiadu lekowego.','Co uzupełnić najpierw?',['Objawy, inne leki, warunki pobrania i historię ekspozycji na CPA','To pozwala ocenić znaczenie wyniku i potrzebę dalszej diagnostyki.'],['Rozpoznać oponiaka na podstawie PRL','PRL nie jest markerem oponiaka; taka decyzja myli dwa różne problemy.'],['Uznać PRL za nieistotną bez wywiadu','Można przeoczyć inną przyczynę lub objawy wymagające diagnostyki.']),
step('T 28 ng/dl, E2 145 pg/ml. Jedna próbka PRL jest podwyższona.','Jak opisać ten zestaw?',['Cele T/E2 są zgodne z typowym punktem odniesienia, PRL wymaga osobnej oceny','Osiągnięcie celu steroidów nie zamyka monitorowania bezpieczeństwa.'],['Prawidłowe T/E2 wykluczają działania niepożądane','Wyniki steroidów nie wykluczają hiperprolaktynemii.'],['PRL dowodzi nieskutecznej feminizacji','To nie jest miernik efektów feminizujących.']),
step('Pacjentka pyta, czy wynik oznacza guz mózgu.','Jaka interpretacja jest uzasadniona?',['Możliwy wpływ leków; wynik nie ustala samodzielnie etiologii','Potwierdzenie i dalsza diagnostyka zależą od objawów, trwałości i skali odchylenia.'],['Pewny prolactinoma','Nie można ustalić tego z samego wyniku w kontekście leków.'],['Pewny oponiak','Oponiak nie jest rozpoznawany przez oznaczenie PRL.']),
step('Po uzupełnieniu danych lekarz ocenia dalszy plan.','Jakie podejście jest właściwe?',['Ponowna ocena CPA, ekspozycji skumulowanej i alternatyw; plan kontroli PRL','Oddziela korzyść z blokady, hiperprolaktynemię i ryzyko oponiaka.'],['Zwiększyć CPA wyłącznie po to, by T był równy zero','Brak takiego celu; zwiększenie ekspozycji może dodać ryzyka.'],['Zastąpić estradiol etynyloestradiolem','Nie zaleca się etynyloestradiolu w GAHT.']),
]},
{id:'case-gaht-hct-review-v2',lessonId:'gonady-trans-maskulinizujaca',title:'Wysoki hematokryt: ekspozycja czy inna przyczyna?',patient:'Mężczyzna transpłciowy, 26 lat; jajniki i macica obecne',difficulty:'Zaawansowany',intro:'Fikcyjny przypadek. Testosteron iniekcyjny od 14 miesięcy. Hct 54,8%. Pacjent chrapie, odczuwa senność w dzień; bez duszności i bólu w klatce piersiowej.',steps:[
step('Nie ustalono schematu iniekcji ani czasu ostatniego pobrania.','Co zbadać w wywiadzie?',['Preparat, dawkę, czas pobrania, palenie i objawy bezdechu','Pozwala ocenić nadmierną ekspozycję i pozahormonalne przyczyny.'],['Wyłącznie czas od rozpoczęcia tranzycji','Pomija farmakokinetykę i inne przyczyny erytrocytozy.'],['Wyłącznie poziom estradiolu','Nie wyjaśnia pełnego obrazu Hct.']),
step('T pobrano przed kolejną iniekcją; Hct jest powtarzalnie wysoki.','Jak interpretować wynik?',['Wysoki Hct wymaga oceny i interwencji, z uwzględnieniem szczytów T i innych przyczyn','Nie można obliczyć indywidualnego ryzyka zakrzepicy z jednej wartości.'],['Wynik T w dołku wyklucza wysokie szczyty','Dołek nie opisuje szczytu ekspozycji.'],['Hct jest wystarczającym rozpoznaniem czerwienicy prawdziwej','Erytrocytoza ma wiele przyczyn.']),
step('W wywiadzie występują objawy sugerujące bezdech.','Jak sformułować problem?',['Erytrocytoza podczas terapii T, możliwy udział bezdechu; wymaga różnicowania','Nie przypisujemy wszystkich odchyleń wyłącznie GAHT.'],['Pewne powikłanie wyłącznie od testosteronu','Inne czynniki mogą współistnieć.'],['Brak problemu, skoro nie ma objawów zakrzepicy','Bezobjawowość nie zwalnia z reakcji na Hct.']),
step('Należy zaplanować interwencję i kontrole.','Która strategia jest uzasadniona?',['Dostosowanie ekspozycji lub drogi podania, ocena bezdechu i kontrola morfologii; flebotomia według wskazań','Postępowanie jest indywidualne i obejmuje przyczynę, nie tylko liczbę.'],['Zawsze upust bez diagnostyki i bez korekty ekspozycji','Może pominąć przyczynę nawrotów.'],['Częstsze podawanie niezmienionej dawki pojedynczej','Zwiększa ekspozycję łączną i może pogorszyć problem.']),
]},
{id:'case-gaht-orchiectomy-v2',lessonId:'gaht-gonadektomia',title:'Po orchiektomii: które sprzężenie nadal działa?',patient:'Kobieta transpłciowa, 41 lat; po obustronnej orchiektomii',difficulty:'Podstawowy',intro:'Fikcyjny przypadek. Osoba dotychczas przyjmowała estradiol i lek hamujący gonadotropiny. Po operacji chce omówić dalsze leczenie.',steps:[
step('Obie gonady usunięte, przysadka sprawna.','Co zmieniło się bezpośrednio?',['Zniknęło gonadalne źródło hormonów i gamet','Nie znika działanie receptorów ani nadnerczy.'],['Przysadka przestała istnieć funkcjonalnie','Usunięcie gonad nie usuwa przysadki.'],['Zniknęła cała aromataza','Pozostaje aromatyzacja obwodowa.']),
step('Nie znamy jeszcze wyników po operacji ani objawów.','Co jest potrzebne do oceny substytucji?',['Wywiad, leki, odpowiednio pobrane badania i ocena ryzyka kostnego','Sama operacja nie wyznacza dawki.'],['Wyłącznie fakt orchiektomii','Nie określa indywidualnej ekspozycji.'],['Stały przelicznik dawki przed operacją','Nie ma uniwersalnego przelicznika.']),
step('Pacjentka pyta o dalszą blokadę gonadotropin.','Co wyjaśnić?',['Supresja LH nie ograniczy produkcji w usuniętych jądrach','Wskazanie do leku trzeba ponownie ocenić.'],['Wyższe LH odtworzy gonady','Nie odtwarza usuniętej tkanki.'],['Nadnercza całkowicie przejmą produkcję jąder','Taka kompensacja nie jest fizjologiczną regułą.']),
step('Celem jest utrzymanie efektów i zdrowia.','Jak planować dalszą terapię?',['Ponownie ocenić blokadę i zapewnić adekwatną, indywidualną substytucję','Unikamy zarówno zbędnej blokady, jak i niedoboru.'],['Odstawić wszystkie hormony bez oceny','Może powstać długotrwały niedobór steroidów.'],['Zawsze podwoić dawkę estradiolu','Brak podstaw do automatycznej zmiany.']),
]},
{id:'case-gaht-amenorrhea-v2',lessonId:'gaht-plodnosc',title:'Brak miesiączki nie jest testem płodności',patient:'Osoba niebinarna, 29 lat; macica i jajniki zachowane',difficulty:'Podstawowy',intro:'Fikcyjny przypadek. Testosteron od roku, brak miesiączki od 8 miesięcy. Pojawiły się plamienia; możliwa ekspozycja prowadząca do ciąży.',steps:[
step('Pacjent uważa, że T jest antykoncepcją.','Co wyjaśnić?',['Owulacja i ciąża mogą być możliwe mimo amenorrhei','T nie jest metodą antykoncepcji.'],['Osiem miesięcy amenorrhei dowodzi bezpłodności','Nie mierzy to rezerwy ani owulacji.'],['Prawidłowy T wyklucza owulację','Cel laboratoryjny nie gwarantuje antykoncepcji.']),
step('Nowe plamienia, zachowane narządy, możliwa ciąża.','Co uwzględnić w ocenie?',['Test ciążowy i dalszą ocenę zależną od objawów','Nie pomijamy ciąży na podstawie GAHT.'],['Wyłącznie E2 dla potwierdzenia aromatyzacji','Może opóźnić rozpoznanie innej przyczyny.'],['Wyłącznie LH jako test ciążowy','LH nie zastępuje testu ciążowego.']),
step('Nie ma jeszcze rozstrzygających wyników.','Jak nazwać problem?',['Nowe krwawienie wymagające różnicowania','Przyczyna nie wynika z samego objawu.'],['Pewna nadmierna aromatyzacja','To hipoteza, nie rozpoznanie.'],['Pewny zanik endometrium','Nie można go ustalić bez oceny.']),
step('Po wyjaśnieniu krwawienia trzeba omówić dalszą profilaktykę.','Co zaplanować?',['Antykoncepcję według potrzeb oraz opiekę nad zachowanymi narządami','Plan zależy od anatomii, preferencji i przeciwwskazań.'],['Wyłącznie zwiększenie T dla antykoncepcji','T nie staje się zatwierdzoną antykoncepcją.'],['Obowiązkowe usunięcie gonad','To nie jest rutynowe rozwiązanie tego problemu.']),
]},
];
