import type { Question } from './course.ts';
import { pituitaryCases } from './cases-pituitary.ts';
import { adrenalCases } from './cases-adrenals.ts';
type Choice=[string,string];
type StepDraft=[string,string,Choice,Choice];
export type ClinicalCase={id:string;lessonId:string;title:string;patient:string;difficulty:'Podstawowy'|'Zaawansowany';intro:string;steps:(Question&{context:string;stage:string})[]};
const step=(context:string,prompt:string,correct:Choice,wrong:Choice):StepDraft=>[context,prompt,correct,wrong];
const make=(lessonId:string,title:string,patient:string,difficulty:ClinicalCase['difficulty'],intro:string,steps:StepDraft[]):ClinicalCase=>({id:`case-${lessonId}`,lessonId,title,patient,difficulty,intro,steps:steps.map(([context,prompt,correct,wrong],i)=>({id:`case-${lessonId}-${i+1}`,lessonId,stage:['Objawy','Badania','Rozpoznanie','Postępowanie'][i],context,prompt,answer:i%2,options:(i%2?[wrong,correct]:[correct,wrong]).map(([text,explanation])=>({text,explanation}))}))});
const thyroidCases:ClinicalCase[]=[
make('fizjologia','Wynik, który nie pasuje','Kobieta, 28 lat','Podstawowy','Podczas kontroli wykryto podwyższone całkowite T4. Pacjentka dobrze się czuje.',[
step('Tętno 72/min, bez drżenia i spadku masy ciała. Stosuje doustną antykoncepcję estrogenową.','Co warto uwzględnić?',['Wpływ estrogenów na białka wiążące','Wzrost TBG może zwiększyć całkowite T4.'],['Pewny przełom tarczycowy','Brak objawów dekompensacji; sam wynik nie rozpoznaje przełomu.']),
step('TSH 1,8 mIU/l (0,4–4,0), FT4 16 pmol/l (12–22).','Co wynika z badań?',['Prawidłowa czynność w tym kontekście','TSH i wolne T4 mieszczą się w zakresie.'],['Jawna pierwotna nadczynność','Oczekiwalibyśmy niskiego TSH i zwiększonej frakcji wolnej.']),
step('Całkowite T4 pozostaje zwiększone przy prawidłowym TSH i FT4.','Jak najlepiej wyjaśnić rozbieżność?',['Większa pula hormonu związanego','Spójne z większą ilością TBG.'],['Brak syntezy hormonów','Nie tłumaczy wyników ani obrazu klinicznego.']),
step('Nie ma objawów alarmowych ani nieprawidłowości badania tarczycy.','Jakie postępowanie jest uzasadnione?',['Wyjaśnić wynik bez wdrażania tyreostatyku','Nie wykazano nadprodukcji wymagającej leczenia.'],['Rozpocząć tiamazol na podstawie całkowitego T4','Może niepotrzebnie zahamować prawidłową czynność.'])]),
make('diagnostyka','TSH w normie to za mało','Mężczyzna, 46 lat','Zaawansowany','Pacjent po operacji guza przysadki zgłasza senność i nietolerancję zimna.',[
step('Objawy narastają od kilku tygodni. TSH z poprzedniego badania było prawidłowe.','Czy samo TSH zamyka diagnostykę?',['Nie, potrzebne FT4 i ocena osi przysadkowych','Uszkodzona przysadka może nie zwiększać TSH adekwatnie.'],['Tak, tarczyca jest na pewno sprawna','Może to przeoczyć niedoczynność centralną.']),
step('FT4 7 pmol/l (12–22), TSH 1,1 mIU/l (0,4–4,0), wynik potwierdzono.','Jak oceniasz TSH?',['Nieadekwatne do niskiego FT4','W sprawnej osi należałoby oczekiwać wzrostu TSH.'],['Dowodzi eutyreozy','Nie uwzględnia stężenia FT4 i choroby przysadki.']),
step('Nie ma ciężkiej choroby ogólnoustrojowej ani znanej interferencji.','Co jest najbardziej prawdopodobne?',['Niedoczynność centralna','Wywiad i para wyników wspierają to rozpoznanie.'],['Hashimoto rozpoznane wyłącznie z TSH','TSH nie jest wysokie, a etiologia przysadkowa jest istotna.']),
step('Rozważasz substytucję hormonów tarczycy.','Co należy zabezpieczyć?',['Ocenić i w razie potrzeby leczyć niedobór kortyzolu','Współistniejąca niewydolność nadnerczy zmienia bezpieczeństwo substytucji.'],['Od razu zwiększać LT4 aż TSH spadnie do zera','TSH nie jest właściwym celem kontroli w tej sytuacji.'])]),
make('niedoczynnosc','Zmęczenie ma przyczynę','Kobieta, 52 lata','Podstawowy','Pacjentka zgłasza zaparcia, suchość skóry i narastającą nietolerancję zimna.',[
step('Tętno 58/min, objawy od kilku miesięcy, bez zaburzeń świadomości.','Jaki pierwszy kierunek diagnostyki?',['TSH i FT4','Pozwalają sprawdzić podejrzenie niedoczynności.'],['Radiojod bez badań','Nie jest badaniem pierwszego wyboru ani uzasadnionym leczeniem.']),
step('TSH 24 mIU/l (0,4–4,0), FT4 6 pmol/l (12–22).','Czy zaburzenie jest subkliniczne?',['Nie, jest jawne','FT4 jest obniżone.'],['Tak, każde wysokie TSH oznacza postać subkliniczną','Postać subkliniczna wymaga prawidłowego FT4.']),
step('Anty-TPO dodatnie, bez operacji lub radiojodu w wywiadzie.','Jaka przyczyna jest prawdopodobna?',['Autoimmunizacyjna niedoczynność','Przeciwciała wspierają tę etiologię.'],['Autonomiczny guzek z nadczynnością','Nie pasuje do niskiego FT4 i wysokiego TSH.']),
step('Pacjentka jest stabilna; nie ma choroby wieńcowej w wywiadzie.','Jaki plan leczenia?',['Indywidualnie dobrana LT4 i kontrola po osiągnięciu równowagi','Uzupełnia niedobór i pozwala dostosować dawkę.'],['Tiamazol i kontrola jutro','Hamowałby syntezę przy istniejącym niedoborze.'])]),
make('hashimoto','Przeciwciała bez niedoboru','Kobieta, 33 lata','Podstawowy','Anty-TPO wykryto podczas badań. Pacjentka pyta, czy musi już przyjmować hormony.',[
step('Nie jest w ciąży, nie planuje jej obecnie. Bez dolegliwości i wyczuwalnego wola.','Co rozstrzyga o czynności gruczołu?',['TSH i FT4 wraz z kontekstem','Przeciwciała określają autoimmunizację, a nie rezerwę hormonalną.'],['Samo miano anty-TPO','Nie wyznacza stopnia niedoboru.']),
step('TSH 2,2 mIU/l (0,4–4,0), FT4 17 pmol/l (12–22).','Jak interpretować ten zestaw?',['Eutyreoza z dodatnimi przeciwciałami','Nie ma biochemicznej jawnej niedoczynności.'],['Jawna niedoczynność','FT4 nie jest obniżone.']),
step('Pacjentka obawia się, że wysoka liczba przeciwciał oznacza ciężką chorobę hormonalną.','Jak to wyjaśnisz?',['Autoimmunizacja i czynność to różne aspekty','Możliwa jest prawidłowa produkcja mimo przeciwciał.'],['Przeciwciała oznaczają pewny rak','Nie są markerem takiego rozpoznania.']),
step('Nie ma dodatkowych wskazań do leczenia.','Co zaproponujesz?',['Obserwację czynności i ocenę nowych objawów','Nie ma automatycznego wskazania do LT4 z powodu samego anty-TPO.'],['Wysokie dawki jodu do wyzerowania przeciwciał','To nieuzasadniona i potencjalnie szkodliwa strategia.'])]),
make('nadczynnosc','Kołatanie u starszego pacjenta','Mężczyzna, 71 lat','Zaawansowany','Nowe migotanie przedsionków, spadek masy ciała i wole guzkowe.',[
step('Tętno niemiarowe 112/min, krążeniowo stabilny, bez gorączki i splątania.','Co należy uwzględnić?',['Tyreotoksykozę jako możliwy czynnik arytmii','Starsza osoba nie musi mieć typowego pobudzenia.'],['Wykluczyć tarczycę z powodu wieku','Może prowadzić do przeoczenia odwracalnego czynnika.']),
step('TSH <0,01 mIU/l (0,4–4,0), FT4 29 pmol/l (12–22), guzki w USG.','Jak uzupełnić ocenę przyczyny?',['Rozważyć scyntygrafię i ocenę TRAb','Pomaga rozróżnić autonomię i Gravesa.'],['Oznaczyć tylko anty-TPO i zakończyć','Nie określi autonomicznej czynności guzków.']),
step('Scyntygrafia pokazuje niejednorodne obszary autonomicznego wychwytu, TRAb ujemne.','Co najbardziej pasuje?',['Wole wieloguzkowe toksyczne','Wyniki wskazują na autonomiczne obszary produkcji.'],['Zapalenie destrukcyjne','Typowo nie daje takiego wzorca autonomicznego wychwytu.']),
step('Potwierdzono nadprodukcję hormonów.','Jak zaplanować dalszą opiekę?',['Leczenie nadczynności i równoległa ocena kardiologiczna','Trzeba uwzględnić arytmię i opcje leczenia docelowego.'],['Sam lek na tętno kończy leczenie przyczyny','Kontrola objawu nie usuwa autonomii.'])]),
make('graves','Nie tylko tarczyca','Kobieta, 39 lat','Zaawansowany','Chudnięcie, drżenie rąk, uczucie piasku pod powiekami i palenie papierosów.',[
step('Widoczne rozlane wole i objawy oczne.','Co trzeba zbadać równolegle?',['Czynność tarczycy i stan oczu','Orbitopatia wymaga odrębnej oceny.'],['Tylko masę ciała','Nie określa etiologii ani zagrożenia wzroku.']),
step('TSH <0,01 mIU/l (0,4–4,0), FT4 36 pmol/l (12–22), TRAb dodatnie.','Co wspiera ta kombinacja?',['Gravesa-Basedowa','Przeciwciała receptorowe i tyreotoksykoza są spójne.'],['Pierwotną niedoczynność','FT4 jest podwyższone, TSH zahamowane.']),
step('Pacjentka opisuje nowe pogorszenie ostrości i rozpoznawania barw.','Jak oceniasz pilność?',['Pilna ocena zagrożenia wzroku','Możliwa neuropatia wzrokowa wymaga szybkiej diagnostyki.'],['Rutynowa kontrola za rok','Opóźnienie może mieć nieodwracalne konsekwencje.']),
step('Potrzebne jest leczenie nadczynności i specjalistyczna ocena orbitopatii.','Co uwzględnić w planie?',['Rzucenie palenia i dobór terapii do aktywności orbitopatii','Ryzyko oczne wpływa na wybór leczenia.'],['Radiojod zawsze, bez oceny oczu','Może pogorszyć przebieg orbitopatii.'])]),
make('zapalenia','Bolesna szyja po infekcji','Kobieta, 44 lata','Podstawowy','Ból z przodu szyi promieniuje do żuchwy. Dwa tygodnie wcześniej infekcja dróg oddechowych.',[
step('Tarczyca bolesna, niewielkie kołatanie, stan ogólny stabilny.','Co jest prawdopodobną hipotezą?',['Podostre zapalenie tarczycy','Ból po infekcji jest typową wskazówką.'],['Każdy ból tarczycy oznacza raka','Istnieją częstsze przyczyny zapalne.']),
step('TSH 0,03 mIU/l (0,4–4,0), FT4 27 pmol/l (12–22), CRP 48 mg/l (<5).','Jak połączyć wyniki?',['Tyreotoksykoza w przebiegu zapalenia','Wskaźniki zapalne i bolesność wspierają destrukcję.'],['Jawna niedoczynność','FT4 jest wysokie, nie niskie.']),
step('USG bez ropnia, TRAb ujemne; lekarz potwierdza zapalenie podostre.','Skąd nadmiar hormonów?',['Z uszkodzonych pęcherzyków','Uwalniane są zapasy, a nie wyłącznie nowa synteza.'],['Z nadmiaru TSH','TSH jest zahamowane.']),
step('Nie ma przeciwwskazań do leczenia przeciwzapalnego.','Jaka strategia odpowiada mechanizmowi?',['Leczenie przeciwzapalne, objawowe i kontrola kolejnych faz','Trzeba także obserwować rozwój niedoczynności.'],['Rutynowo długotrwały tyreostatyk','Nie hamuje uwalniania zgromadzonych hormonów.'])]),
make('guzki','Przypadkowe znalezisko','Kobieta, 57 lat','Podstawowy','W badaniu szyi stwierdzono guzek. Pacjentka nie ma objawów nadczynności.',[
step('Bez chrypki i duszności, bez rodzinnego raka tarczycy.','Co obejmuje pierwsza ocena?',['TSH oraz USG tarczycy i węzłów szyi','Oceniamy czynność i strukturę.'],['Natychmiastowe rozpoznanie raka','Sam guzek nie wystarcza.']),
step('TSH 1,6 mIU/l (0,4–4,0), guzek 18 mm, EU-TIRADS 5, węzły bez podejrzanych cech.','Czy przekracza typowy próg ETA 2023 dla tej kategorii?',['Tak, próg wynosi >10 mm','Ryzyko i rozmiar przemawiają za BACC.'],['Nie, biopsja dopiero od 5 cm','Nie odpowiada progom ETA.']),
step('Nie wykonano jeszcze biopsji.','Co możesz już stwierdzić?',['Zmiana wymaga diagnostyki cytologicznej','Wysokie ryzyko USG nie jest jeszcze histologicznym rozpoznaniem raka.'],['Na pewno rak rdzeniasty','USG nie określa takiego typu.']),
step('Pacjentka rozumie cel diagnostyki.','Jaki następny krok?',['BACC pod kontrolą USG i dalszy plan według wyniku','To pozwala doprecyzować ryzyko.'],['LT4 w dużej dawce zamiast oceny guzka','Nie zastępuje właściwej diagnostyki.'])]),
make('nowotwory','Kalcytonina zmienia ścieżkę','Mężczyzna, 42 lata','Zaawansowany','W diagnostyce guzka uzyskano wynik sugerujący raka rdzeniastego.',[
step('Ojciec był operowany z powodu raka rdzeniastego.','Co wnosi wywiad rodzinny?',['Podejrzenie dziedzicznego zespołu związanego z RET','Rodzina wymaga uwzględnienia w ocenie genetycznej.'],['Nie ma żadnego znaczenia','Może przeoczyć dziedziczne ryzyko.']),
step('Podwyższona kalcytonina, cytologia wspiera raka rdzeniastego.','Jaki kierunek dalszej oceny?',['Specjalistyczna kwalifikacja onkologiczna i genetyczna','To odmienna ścieżka od typowego raka pęcherzykowego.'],['Kontrola samego anty-TPO','Nie ocenia tego nowotworu.']),
step('Potwierdzono patogenny wariant RET związany z MEN2.','Które współistnienie ma znaczenie przed operacją?',['Guz chromochłonny','Należy go wykluczyć przed planowym zabiegiem.'],['Wyłącznie podwyższone TBG','Nie jest kluczowym zagrożeniem MEN2.']),
step('Zespół planuje dalsze leczenie.','Które stwierdzenie jest prawidłowe?',['Radiojod nie jest rutynową terapią raka rdzeniastego','Komórki C mają inne właściwości niż komórki pęcherzykowe.'],['Każdy rak tarczycy leczy się identycznie','Pomija biologię i typ nowotworu.'])]),
make('ciaza','Dodatni test ciążowy','Kobieta, 30 lat','Zaawansowany','Pacjentka z leczoną niedoczynnością jest w 6. tygodniu ciąży.',[
step('Regularnie przyjmuje LT4. Pyta, czy odstawienie leku ochroni dziecko.','Jak odpowiesz?',['Nie odstawiać automatycznie; szybko ustalić kontrolę i leczenie','Hormony są potrzebne, a zapotrzebowanie może wzrosnąć.'],['Odstawić do końca ciąży','Może wywołać niedobór hormonów.']),
step('Uzyskano TSH i FT4. Laboratorium podaje zakresy dla trymestru i metody.','Z czym porównać wyniki?',['Z odpowiednimi zakresami ciążowymi','Ciąża zmienia interpretację oznaczeń.'],['Wyłącznie ze stałą normą dla wszystkich dorosłych','Może prowadzić do błędnej kwalifikacji.']),
step('TSH przekracza zakres ciążowy, FT4 jest poniżej zakresu tej metody.','Co jest najbardziej istotne?',['Niedostateczna substytucja wymagająca szybkiej oceny','Zestaw wskazuje na niedobór w tym kontekście.'],['Pewny Graves-Basedow','Obraz nie wskazuje na nadprodukcję.']),
step('Pacjentka jest stabilna, ma kontakt z lekarzem prowadzącym.','Jaki plan jest odpowiedni?',['Dostosowanie LT4 i częstsza kontrola w ciąży','Leczenie i monitorowanie wymagają aktualizacji.'],['Radiojod','Jest przeciwwskazany i nie leczy tego niedoboru.'])]),
make('leki','Serce i tarczyca','Mężczyzna, 65 lat','Zaawansowany','Pacjent stosujący amiodaron zgłasza spadek masy ciała i pogorszenie tolerancji wysiłku.',[
step('Amiodaron włączono z powodu poważnej arytmii.','Co uwzględnić w pierwszej ocenie?',['Możliwą dysfunkcję tarczycy i stan serca','Oba układy wpływają na pilność postępowania.'],['Uznać lek za obojętny dla tarczycy','Amiodaron może wywołać różne zaburzenia.']),
step('TSH <0,01 mIU/l (0,4–4,0), FT4 42 pmol/l (12–22), FT3 8 pmol/l (3,1–6,8).','Co potwierdzają wyniki?',['Jawną tyreotoksykozę','Hormony są podwyższone, a TSH zahamowane.'],['Eutyreozę','Wyniki wykraczają poza podane zakresy.']),
step('Gruczoł wcześniej niezmieniony, brak zwiększonego unaczynienia; zespół rozpoznaje AIT typu 2.','Jaki mechanizm dominuje?',['Destrukcja tkanki','Odpowiada typowi 2, choć możliwe są postacie mieszane.'],['Wyłącznie nadprodukcja w autonomicznych guzkach','To bliższe typowi 1.']),
step('Kardiolog ocenia ryzyko przerwania amiodaronu.','Co jest właściwą zasadą?',['Wspólna decyzja i leczenie dopasowane do mechanizmu AIT','W typie 2 istotną rolę mają glikokortykosteroidy.'],['Samodzielne odstawienie wszystkich leków sercowych','Może narazić pacjenta na ciężką arytmię.'])]),
make('stany-nagle','Dyżur: gorączka i splątanie','Kobieta, 48 lat','Zaawansowany','Pacjentka z nadczynnością przerwała leczenie. Od dwóch dni gorączkuje.',[
step('Temperatura 39,5°C, tętno 154/min, splątanie, duszność.','Jaki jest priorytet?',['ABC i natychmiastowa pomoc szpitalna','To możliwa dekompensacja z zagrożeniem życia.'],['Planowa wizyta za miesiąc','Nie odpowiada pilności stanu.']),
step('Zespół pobiera TSH, FT4/FT3, elektrolity i badania w kierunku zakażenia.','Czy stabilizacja musi czekać na komplet wyników?',['Nie, działania prowadzi się równolegle','Opóźnienie leczenia niestabilności jest niebezpieczne.'],['Tak, bez wyników nie wolno pomagać','Ocena i zabezpieczenie ABC nie mogą czekać.']),
step('Potwierdzono tyreotoksykozę, występują zaburzenia świadomości i krążenia.','Co jest najbardziej niepokojące?',['Przełom tarczycowy wyzwolony możliwą infekcją','Liczy się zespół objawów i dekompensacja narządowa.'],['Bezobjawowa subkliniczna nadczynność','Przeczy temu ciężki stan kliniczny.']),
step('Pacjentka trafia pod intensywny nadzór.','Jakie postępowanie odpowiada sytuacji?',['Leczenie wielokierunkowe i czynnika wyzwalającego','Konieczna jest specjalistyczna kontrola hormonalna i narządowa.'],['Sam doustny beta-bloker bez oceny krążenia','Nie wystarcza, a w niewydolności serca wymaga ostrożności.'])]),
];

export const cases: ClinicalCase[] = [
  ...thyroidCases,
  ...pituitaryCases,
  ...adrenalCases,
];
