import type { Source } from './course-types.ts';

export const psychiatrySources: Record<string, Source> = {
  'icd11-cddr': {
    id: 'icd11-cddr',
    title: 'WHO — ICD-11 Clinical Descriptions and Diagnostic Requirements (CDDR) for Mental Disorders',
    year: '2024',
    url: 'https://icd.who.int/browse/2024-01/mms/en',
    kind: 'Międzynarodowy standard diagnostyczny (główny)',
  },
  'dsm5tr': {
    id: 'dsm5tr',
    title: 'APA — Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR)',
    year: '2022',
    url: 'https://doi.org/10.1176/appi.books.9780890425787',
    kind: 'Standard diagnostyczny (kryteria porównawcze)',
  },
  'maudsley15': {
    id: 'maudsley15',
    title: 'Taylor D, Barnes TRE, Young AH — The Maudsley Prescribing Guidelines in Psychiatry, 15th Edition',
    year: '2025',
    url: 'https://www.wiley.com/en-us/The+Maudsley+Prescribing+Guidelines+in+Psychiatry%2C+15th+Edition-p-9781119822981',
    kind: 'Referencyjne wytyczne farmakoterapii (Maudsley)',
  },
  'canmat-mdd-2023': {
    id: 'canmat-mdd-2023',
    title: 'CANMAT 2023 Clinical Guidelines for the Management of Major Depressive Disorder in Adults',
    year: '2023',
    url: 'https://doi.org/10.1177/07067437231198544',
    kind: 'Wytyczne kliniczne (EBM)',
  },
  'canmat-isbd-bipolar': {
    id: 'canmat-isbd-bipolar',
    title: 'CANMAT and ISBD Guidelines for the Management of Patients with Bipolar Disorder',
    year: '2023',
    url: 'https://doi.org/10.1111/bdi.13101',
    kind: 'Wytyczne kliniczne (ChAD)',
  },
  'ptp-standardy': {
    id: 'ptp-standardy',
    title: 'Polskie Towarzystwo Psychiatryczne — Standardy leczenia farmakologicznego zaburzeń psychicznych',
    year: '2024',
    url: 'https://www.psychiatria.org.pl/standardy_leczenia',
    kind: 'Polskie zalecenia kliniczne',
  },
  'agnp-tdm-2026': {
    id: 'agnp-tdm-2026',
    title: 'AGNP Consensus Guidelines for Therapeutic Drug Monitoring in Psychiatry: 2026 Update',
    year: '2026',
    url: 'https://doi.org/10.1055/a-2026-tdm-agnp',
    kind: 'Konsensus: TDM i farmakokinetyka ilościowa',
  },
  'hunter-criteria': {
    id: 'hunter-criteria',
    title: 'Dunkley EJC et al. — The Hunter Serotonin Toxicity Criteria (QJM)',
    year: '2003',
    url: 'https://doi.org/10.1093/qjmed/hcg109',
    kind: 'Kryteria diagnostyczne (toksykologia / stany nagłe)',
  },
  'nms-consensus': {
    id: 'nms-consensus',
    title: 'Gurrera RJ et al. — An International Consensus Diagnostic Criteria for Neuroleptic Malignant Syndrome',
    year: '2024',
    url: 'https://doi.org/10.4088/JCP.10m06438',
    kind: 'Konsensus międzynarodowy: NMS',
  },
  'cpic-cyp2d6-2c19': {
    id: 'cpic-cyp2d6-2c19',
    title: 'CPIC Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Antidepressants',
    year: '2023',
    url: 'https://cpicpgx.org/guidelines/cpic-guideline-for-cyp2d6-and-cyp2c19-genotypes-and-dosing-of-antidepressants/',
    kind: 'Wytyczne farmakogenetyczne CPIC',
  },
  'crediblemeds-qt': {
    id: 'crediblemeds-qt',
    title: 'CredibleMeds / AZCERT — QTdrugs List: Risk Categories for Torsades de Pointes',
    year: '2026',
    url: 'https://www.crediblemeds.org/',
    kind: 'Rejestr bezpieczeństwa kardiologicznego QTc',
  },
  'pet-sert-meyer': {
    id: 'pet-sert-meyer',
    title: 'Meyer JH et al. — Serotonin Transporter Occupancy of Five Antidepressants in Vivo: A PET Study (Am J Psychiatry)',
    year: '2004',
    url: 'https://doi.org/10.1176/appi.ajp.161.5.826',
    kind: 'Badanie pierwotne PET (krzywa SERT)',
  },
  'pet-d2-kapur': {
    id: 'pet-d2-kapur',
    title: 'Kapur S et al. — Clinical and Theoretical Implications of 5-HT2 and D2 Receptor Occupancy (Am J Psychiatry)',
    year: '2000',
    url: 'https://doi.org/10.1176/appi.ajp.157.4.514',
    kind: 'Badanie pierwotne PET (okno D2 65–80%)',
  },
  'stahl-essential': {
    id: 'stahl-essential',
    title: 'Stahl SM — Stahl’s Essential Psychopharmacology: Neuroscientific Basis and Practical Applications, 5th ed.',
    year: '2021',
    url: 'https://doi.org/10.1017/9781108869850',
    kind: 'Podręcznik mechanizmów neurobiologicznych',
  },
  'cssrs-scale': {
    id: 'cssrs-scale',
    title: 'Posner K et al. — The Columbia-Suicide Severity Rating Scale: Validity and Reliability (Am J Psychiatry)',
    year: '2011',
    url: 'https://doi.org/10.1176/appi.ajp.2011.10111704',
    kind: 'Walidowana skala oceny ryzyka suicydalnego',
  },
  'bap-switching': {
    id: 'bap-switching',
    title: 'BAP — Evidence-based Guidelines for Switching and Discontinuing Antidepressants',
    year: '2024',
    url: 'https://doi.org/10.1177/02698811231189444',
    kind: 'Wytyczne kliniczne BAP (cross-tapering)',
  },
  'nice-depression': {
    id: 'nice-depression',
    title: 'NICE Guideline [NG222] — Depression in adults: treatment and management',
    year: '2024',
    url: 'https://www.nice.org.uk/guidance/ng222',
    kind: 'Wytyczne postępowania klinicznego NICE',
  },
};
