import { type DraftLesson, q } from './course-types.ts';

export const draftDiabetesPart1: DraftLesson[] = [
  {
    id: 'cukrzyca-fizjologia',
    title: 'Wyspy trzustkowe i biosynteza insuliny',
    subtitle: 'Komórki beta, proinsulina, peptyd C i sprzężenie glukoza-insulina',
    group: 'Fundamenty i diagnostyka',
    minutes: 14,
    goals: [
      'Wyjaśnisz proces biosyntezy, dojrzewania i sekrecji insuliny oraz peptydu C.',
      'Opiszesz rolę transportera GLUT2/GLUT1 i kanałów potasowych K-ATP w komórce beta.',
    ],
    sections: [
      {
        title: 'Fabryka w wyspach Langerhansa',
        text: 'Insulina powstaje w komórkach beta wysp trzustkowych jako preproinsulina. Po odcięciu sekwencji sygnałowej w siateczce śródplazmatycznej proinsulina trafia do aparatu Golgiego, gdzie endopeptydazy PC1/3 i PC2 oraz karboksypeptydaza E wycinają 31-aminokwasowy peptyd C. Insulina (łańcuch A i B połączone dwoma mostkami dwusiarczkowymi) oraz peptyd C są magazynowane w ziarnistościach wydzielniczych w stosunku ekwimolarnym 1:1.',
      },
      {
        title: 'Mechanizm sprzężenia glukoza-sekrecja',
        text: 'Wzrost stężenia glukozy we krwi prowadzi do jej napływu do komórki beta przez transportery glukozy. Glukokinaza (heksokinaza IV) pełni rolę „sensora glukozy” o wysokim Km (~5–8 mmol/L). Glikoliza i fosforylacja oksydacyjna zwiększają stosunek ATP/ADP, co zamyka wrażliwe na ATP kanały potasowe (K-ATP, podjednostki Kir6.2/SUR1). Depolaryzacja błony otwiera napięciowozależne kanały wapniowe (VDCC), a napływ Ca2+ wyzwala egzocytozę ziarnistości z insuliną.',
      },
      {
        title: 'Peptyd C jako okno na funkcję komórek beta',
        text: 'W przeciwieństwie do insuliny, która podlega w 50–70% efektowi pierwszego przejścia i degradacji w wątrobie, peptyd C nie jest wychwytywany przez hepatocyty i ma dłuższy czas półtrwania (~30 min vs 4–6 min dla insuliny). Oznaczenie stężenia peptydu C (na czczo lub po stymulacji glukagonem/posiłkiem) jest złotym standardem oceny rezerwy wydzielniczej komórek beta, niepodatnym na zafałszowanie przez podawaną podskórnie insulinę egzogenną.',
      },
    ],
    table: {
      headers: ['Czynnik', 'Wpływ na sekrecję insuliny', 'Mechanizm molekularny'],
      rows: [
        ['Glukoza', 'Silne pobudzenie', 'Wzrost ATP/ADP -> zamknięcie K-ATP -> napływ Ca2+'],
        ['GLP-1 i GIP (inkretyny)', 'Pobudzenie zależne od glukozy', 'Aktywacja receptora GLP-1R -> wzrost cAMP -> PKA/Epac2'],
        ['Pochodne sulfonylomocznika', 'Pobudzenie niezależne od glukozy', 'Bezpośrednie zablokowanie podjednostki SUR1 kanału K-ATP'],
        ['Somatostatyna i adrenalina', 'Silne hamowanie', 'Aktywacja receptorów Gi / alfa-2-adrenergicznych -> spadek cAMP'],
      ],
    },
    advanced:
      'Sekrecja insuliny ma charakter dwufazowy: faza pierwsza (szybkie uwolnienie zapasów z ziarnistości podbłonowych w 5–10 min) zanika wcześnie w cukrzycy typu 2. Druga faza to powolne, zależne od trwającej syntezy uwalnianie insuliny. Brak pierwszej fazy jest najwcześniejszym markerem laboratoryjnym dysfunkcji komórek beta w dożylnym teście tolerancji glukozy (IVGTT).',
    summary:
      'Insulina i peptyd C wydzielają się ekwimolarnie w odpowiedzi na metabolizm glukozy zamykający kanały K-ATP. Peptyd C mierzy rzeczywistą endogenną rezerwę trzustkową.',
    sourceIds: ['ptd_guidelines', 'ada_standards', 'insulin_biochem'],
    questions: [
      q('W jakim stosunku molowym insulina i peptyd C są uwalniane z komórki beta?',
        ['1:1 (ekwimolarnie)', 'Obie cząsteczki powstają z rozszczepienia pojedynczej proinsuliny w ziarnistościach wydzielniczych.'],
        ['2:1 na korzyść insuliny', 'Na każdą cząsteczkę insuliny powstaje dokładnie jeden peptyd C.'],
        ['Zmiennym, zależnym od poziomu glukozy', 'Stosunek w ziarnistościach jest stały; zmienia się jedynie późniejszy klirens wątrobowy.']),
      q('Dlaczego stężenie peptydu C lepiej odzwierciedla czynność komórek beta niż stężenie insuliny?',
        ['Nie podlega istotnemu klirensowi pierwszego przejścia w wątrobie i nie reaguje krzyżowo z insuliną egzogenną', 'Wątroba wychwytuje ponad połowę wydzielonej insuliny, ale omija peptyd C.'],
        ['Ma krótszy czas półtrwania i szybciej reaguje na bodźce', 'Peptyd C ma czas półtrwania dłuższy (~30 min), a nie krótszy od insuliny.'],
        ['Jest wydzielany wyłącznie przy braku glukozy', 'Peptyd C wydziela się równolegle z insuliną pod wpływem glukozy.']),
      q('Jaka jest rola glukokinazy w komórce beta trzustki?',
        ['Działa jako molekularny sensor glukozy determinujący tempo glikolizy i generowania ATP', 'Wysokie Km i brak hamowania produktem pozwalają rejestrować wahania glikemii.'],
        ['Otwiera kanały potasowe K-ATP', 'Zwiększenie ATP zamyka kanały potasowe, a nie je otwiera.'],
        ['Wycina peptyd C z proinsuliny', 'Do wycinania peptydu C służą konwertazy prohormonowe PC1/3 i PC2.']),
      q('Co dzieje się z kanałami K-ATP po wzroście stężenia glukozy w komórce beta?',
        ['Zamykają się wskutek wzrostu stosunku ATP/ADP, co prowadzi do depolaryzacji błony', 'Zamknięcie kanałów K+ uniemożliwia ucieczkę kationów i depolaryzuje komórkę.'],
        ['Otwierają się, powodując głęboką hiperpolaryzację komórki', 'Hiperpolaryzacja hamowałaby, a nie pobudzała sekrecję insuliny.'],
        ['Ulegają natychmiastowej degradacji lizosomalnej', 'Kanały K-ATP są trwałym elementem błony regulowanym allosterycznie przez nukleotydy adeninowe.']),
      q('Przez jaki receptor inkretyna GLP-1 wzmaga sekrecję insuliny?',
        ['Receptor sprzężony z białkiem Gs aktywujący cyklazę adenylanową i szlak cAMP-PKA/Epac', 'Wzrost cAMP uwrażliwia aparat egzocytotyczny komórki beta na jony wapnia.'],
        ['Receptor tyrozynowy aktywujący kinazę Akt', 'To domena działania samej insuliny na tkanki obwodowe, nie GLP-1.'],
        ['Kanał sodowy bramkowany napięciem', 'GLP-1 działa przez receptor metabotropowy GPCR, nie kanał jonowy.']),
    ],
  },
  {
    id: 'cukrzyca-diagnostyka',
    title: 'Kryteria rozpoznania i stany przedcukrzycowe',
    subtitle: 'Glikemia na czczo, OGTT, HbA1c i pułapki laboratoryjne wg PTD/ADA',
    group: 'Fundamenty i diagnostyka',
    minutes: 15,
    goals: [
      'Przedstawisz aktualne kryteria rozpoznania cukrzycy i stanów przedcukrzycowych (IFG, IGT).',
      'Wymienisz ograniczenia i interferencje w oznaczaniu hemoglobiny glikowanej (HbA1c).',
    ],
    sections: [
      {
        title: 'Standardowe kryteria rozpoznania cukrzycy',
        text: 'Według wytycznych PTD 2025 i ADA 2026 cukrzycę rozpoznaje się na podstawie jednego z 4 kryteriów: 1) Glikemia przygodna >= 200 mg/dl (11,1 mmol/L) z typowymi objawami hiperglikemii; 2) Glikemia na czczo (FPG) >= 126 mg/dl (7,0 mmol/L) potwierdzona w dwóch niezależnych oznaczeniach; 3) Glikemia w 120. minucie testu doustnego obciążenia 75 g glukozy (OGTT) >= 200 mg/dl (11,1 mmol/L); 4) HbA1c >= 6,5% (48 mmol/mol) oznaczona metodą certyfikowaną przez NGSP/IFCC.',
      },
      {
        title: 'Stany przedcukrzycowe: stan alarmowy',
        text: 'Stany przedcukrzycowe wiążą się ze znacznym ryzykiem progresji do jawnej cukrzycy i powikłań sercowo-naczyniowych. Obejmują: nieprawidłową glikemię na czczo (IFG): FPG 100–125 mg/dl (5,6–6,9 mmol/L) oraz nieprawidłową tolerancję glukozy (IGT): glikemia w 120. minucie OGTT 140–199 mg/dl (7,8–11,0 mmol/L). W kryteriach ADA stanem przedcukrzycowym jest także HbA1c w przedziale 5,7–6,4% (39–47 mmol/mol).',
      },
      {
        title: 'Pułapki i interferencje hemoglobiny glikowanej (HbA1c)',
        text: 'HbA1c odzwierciedla średnią glikemię z ostatnich 8–12 tygodni (czas przeżycia erytrocytu to ~120 dni). Fałszywie zaniżone wyniki występują w stanach skróconego przeżycia krwinek: niedokrwistości hemolityczne, stan po przetoczeniu KKCz, dializoterapia, leczenie erytropoetyną czy III trymestr ciąży. Wyniki fałszywie zawyżone dają: ciężka niedokrwistość z niedoboru żelaza, witaminy B12, splenektomia i przewlekły alkoholizm. W takich sytuacjach alternatywą jest oznaczenie fruktozaminy lub profil CGM.',
      },
    ],
    table: {
      headers: ['Kategoria', 'Glikemia na czczo (FPG)', 'OGTT 120. minuta', 'HbA1c'],
      rows: [
        ['Prawidłowa tolerancja glukozy', '70–99 mg/dl (3,9–5,5 mmol/l)', '<140 mg/dl (<7,8 mmol/l)', '<5,7% (<39 mmol/mol)'],
        ['Nieprawidłowa glikemia na czczo (IFG)', '100–125 mg/dl (5,6–6,9 mmol/l)', '<140 mg/dl (<7,8 mmol/l)', '5,7–6,4% (wg ADA)'],
        ['Nieprawidłowa tolerancja glukozy (IGT)', '<100 lub 100–125 mg/dl', '140–199 mg/dl (7,8–11,0 mmol/l)', '5,7–6,4% (wg ADA)'],
        ['Cukrzyca (Diabetes Mellitus)', '>=126 mg/dl (>=7,0 mmol/l) w 2 testach', '>=200 mg/dl (>=11,1 mmol/l)', '>=6,5% (>=48 mmol/mol)'],
      ],
    },
    advanced:
      'Gdy występują objawy ostrej hiperglikemii (polidypsja, wielomocz, utrata masy ciała) i glikemia przygodna wynosi >=200 mg/dl, rozpoznanie cukrzycy jest PEWNE i nie wymaga żadnych badań potwierdzających ani testu OGTT! Wykonywanie testu OGTT u pacjenta z glikemią na czczo >=126 mg/dl lub jawną dekompensacją jest błędem w sztuce i stwarza ryzyko wywołania ostrej hiperglikemii.',
    summary:
      'Cukrzycę rozpoznajemy przy FPG >=126 mg/dl (dwukrotnie), OGTT >=200 mg/dl lub glikemii przygodnej >=200 mg/dl z objawami. HbA1c >=6,5% wymaga uwzględnienia czasu życia erytrocytów.',
    sourceIds: ['ptd_guidelines', 'ada_standards'],
    questions: [
      q('Pacjent bez objawów hiperglikemii ma glikemię na czczo 132 mg/dl (7,3 mmol/L). Jaki jest prawidłowy krok diagnostyczny?',
        ['Powtórzyć oznaczenie glikemii na czczo w inny dzień lub oznaczyć HbA1c certyfikowaną metodą', 'U osoby bezobjawowej nieprawidłowy wynik na czczo wymaga laboratoryjnego potwierdzenia drugim testem.'],
        ['Natychmiast rozpoznać cukrzycę i wdrożyć insulinę', 'Jeden wynik u chorego bez objawów nie spełnia kryteriów pewnego rozpoznania.'],
        ['Wykonać biopsję trzustki', 'Biopsja trzustki nie ma żadnego zastosowania w diagnostyce cukrzycy.']),
      q('Glikemia w 120. minucie testu OGTT wynosi 168 mg/dl (9,3 mmol/L). Jaka jest prawidłowa klasyfikacja?',
        ['Nieprawidłowa tolerancja glukozy (IGT — stan przedcukrzycowy)', 'Przedział 140–199 mg/dl w 120. minucie OGTT definiuje IGT.'],
        ['Prawidłowa tolerancja glukozy', 'Glikemia prawidłowa w 120. minucie nie może przekraczać 140 mg/dl.'],
        ['Jawna cukrzyca wymagająca leczenia szpitalnego', 'Cukrzycę rozpoznaje się dopiero od 200 mg/dl w 120. minucie OGTT.']),
      q('W którym z poniższych stanów klinicznych stężenie HbA1c będzie FAŁSZYWIE ZANIŻONE?',
        ['Niedokrwistość hemolityczna ze skróconym czasem przeżycia krwinek czerwonych', 'Młodsza populacja erytrocytów ma mniej czasu na nieenzymatyczną glikację hemoglobiny.'],
        ['Ciężka niedokrwistość z niedoboru żelaza', 'Niedobór żelaza fałszywie zawyża HbA1c wskutek wydłużenia przeżycia starych erytrocytów.'],
        ['Stan po splenektomii', 'Brak śledziony wydłuża czas krążenia erytrocytów, co zawyża HbA1c.']),
      q('Które kryterium pozwala na natychmiastowe rozpoznanie cukrzycy bez konieczności powtarzania badań?',
        ['Glikemia przygodna >= 200 mg/dl (11,1 mmol/L) z typowymi objawami klinicznymi (wielomocz, pragnienie)', 'Obecność jawnych objawów w połączeniu z glikemią >=200 mg/dl jest kryterium jednoznacznym.'],
        ['Pojedyncza glikemia na czczo 128 mg/dl bez żadnych objawów', 'Bezobjawowy wynik na czczo musi zostać powtórzony.'],
        ['Glikemia w 120. minucie OGTT wynosząca 155 mg/dl', 'To jest stan przedcukrzycowy (IGT), a nie cukrzyca.']),
      q('Czy u pacjenta ze świeżo wykrytą glikemią na czczo 180 mg/dl należy zlecić doustny test obciążenia 75 g glukozy (OGTT)?',
        ['Nie, test OGTT jest u takiego chorego przeciwwskazany i zbędny', 'Wystarczy powtórzyć oznaczenie glikemii na czczo; podanie 75 g glukozy grozi zaostrzeniem hiperglikemii.'],
        ['Tak, OGTT jest obowiązkowy u każdego pacjenta przed wdrożeniem diety', 'OGTT wykonuje się przy wątpliwościach w przedziale IFG (100–125 mg/dl), nie przy FPG >=126 mg/dl.'],
        ['Tak, ale wyłącznie z dawką 150 g glukozy', 'Standardowy test OGTT zawsze wykorzystuje 75 g bezwodnej glukozy.']),
    ],
  },
  {
    id: 'cukrzyca-technologie-cgm',
    title: 'Technologie diabetologiczne i ciągłe monitorowanie (CGM)',
    subtitle: 'Wskaźniki TIR, TAR, TBR, profil AGP i zmienność glikemii (CV)',
    group: 'Fundamenty i diagnostyka',
    minutes: 16,
    goals: [
      'Zdefiniujesz i zinterpretujesz kluczowe parametry raportu AGP: TIR, TAR, TBR, CV i GMI.',
      'Wyjaśnisz różnicę między pomiarem we krwi włośniczkowej (SMBG) a pomiarem w płynie śródtkankowym (CGM).',
    ],
    sections: [
      {
        title: 'Od glukometru do ciągłego monitorowania',
        text: 'Ciągłe monitorowanie glikemii (CGM w czasie rzeczywistym rtCGM lub skanowane flash isCGM) mierzy stężenie glukozy w płynie śródtkankowym tkanki podskórnej za pomocą enzymatycznej elektrody z oksydazą glukozową. Występuje fizjologiczne opóźnienie (tzw. lag time, zazwyczaj 4–10 minut) między glikemią w osoczu naczyniowym a płynem śródtkankowym, szczególnie wyraźne przy gwałtownych trendach wzrostowych lub spadkowych.',
      },
      {
        title: 'Złoty standard celów: Time in Range (TIR)',
        text: 'Według międzynarodowego konsensusu ATTD kluczowe cele dla większości dorosłych z cukrzycą typu 1 i 2 obejmują: 1) Czas w zakresie docelowym (TIR: 70–180 mg/dl [3,9–10,0 mmol/l]) > 70% doby (odpowiada to HbA1c ok. 7,0%); 2) Czas poniżej zakresu (TBR < 70 mg/dl) < 4%, w tym hipoglikemia bardzo niska (< 54 mg/dl) < 1%; 3) Czas powyżej zakresu (TAR > 180 mg/dl) < 25%, w tym hiperglikemia skrajna (> 250 mg/dl) < 5%. U seniorów i osób z powikłaniami cel TIR obniża się do > 50%, przy TBR < 1%.',
      },
      {
        title: 'Zmienność glikemii i profil AGP',
        text: 'Raport Ambulatory Glucose Profile (AGP) standaryzuje odczyt z minimum 14 dni ciągłego zapisu (z pokryciem sensora > 70%). Kluczowym wskaźnikiem stabilności leczenia jest współczynnik zmienności (CV = SD / Średnia * 100%). Wartość CV <= 36% oznacza stabilną glikemię; CV > 36% to chwiejna glikemia o podwyższonym ryzyku ciężkich hipoglikemii. Wskaźnik GMI (Glucose Management Indicator) szacuje oczekiwane stężenie HbA1c na podstawie średniej z sensora.',
      },
    ],
    table: {
      headers: ['Wskaźnik CGM', 'Zakres glikemii', 'Cel dla T1D/T2D', 'Cel dla pacjentów wysokiego ryzyka'],
      rows: [
        ['TIR (Time in Range)', '70–180 mg/dl (3,9–10,0 mmol/l)', '> 70% (> 16 godz. 48 min/dobę)', '> 50% (> 12 godzin/dobę)'],
        ['TBR poziom 1 (Low)', '54–69 mg/dl (3,0–3,8 mmol/l)', '< 4% (< 58 minut/dobę)', '< 1% (< 14 minut/dobę)'],
        ['TBR poziom 2 (Very Low)', '< 54 mg/dl (< 3,0 mmol/l)', '< 1% (< 14 minut/dobę)', '< 0,5% (< 7 minut/dobę)'],
        ['TAR poziom 1 (High)', '181–250 mg/dl (10,1–13,9 mmol/l)', '< 25% (< 6 godzin/dobę)', '< 50%'],
        ['Współczynnik zmienności (CV)', 'SD / Średnia glikemia * 100%', '<= 36% (glikemia stabilna)', '<= 36% (rygorystyczne unikanie hipo)'],
      ],
    },
    advanced:
      'Zjawisko opóźnienia fizjologicznego (lag time) ma krytyczne znaczenie w hipoglikemii: po spożyciu 15 g szybkich węglowodanów glikemia we krwi włośniczkowej wzrasta po 5–10 minutach, podczas gdy sensor CGM może jeszcze przez kilka minut pokazywać trend spadkowy. W razie wątpliwości lub rozbieżności między objawami a odczytem sensora zawsze należy wykonać pomiar z opuszki palca glukometrem!',
    summary:
      'Raport AGP z sensora CGM opiera się na triadzie celów: TIR >70%, TBR <4% i CV <=36%. Pozwala wykryć bezobjawowe hipoglikemie i ocenić stabilność terapii.',
    sourceIds: ['cgm_consensus', 'ptd_guidelines', 'ada_standards'],
    questions: [
      q('Jaki jest docelowy odsetek czasu w zakresie (TIR 70–180 mg/dl) dla większości chorych na cukrzycę typu 1?',
        ['Powyżej 70% czasu zapisu sensora', 'TIR > 70% koreluje ze zmniejszeniem ryzyka mikro- i makroangiopatii i odpowiada HbA1c ~7,0%.'],
        ['Powyżej 98% czasu zapisu', 'Nierealistyczny cel, który drastycznie zwiększyłby ryzyko zagrażających życiu hipoglikemii.'],
        ['Wystarczy powyżej 40%', 'Zbyt niski odsetek wiąże się z wysoką ekspozycją na hiperglikemię i szybkim rozwojem powikłań.']),
      q('Jaki jest bezpieczny limit czasu spędzonego w hipoglikemii (TBR < 70 mg/dl) wg konsensusu ATTD?',
        ['Mniej niż 4% doby (< 1 godzina na dobę), w tym < 1% poniżej 54 mg/dl', 'Restrykcyjne ograniczenie TBR chroni mózg przed neuroglikopenią i utratą świadomości hipoglikemii.'],
        ['Mniej niż 15% doby', '15% to ponad 3,5 godziny dziennie w hipoglikemii — niedopuszczalnie wysokie zagrożenie.'],
        ['TBR nie ma znaczenia, dopóki TIR wynosi 70%', 'Nawet przy wysokim TIR częste spadki poniżej 70 mg/dl wymagają natychmiastowej korekty bazy/bolusów.']),
      q('Współczynnik zmienności glikemii (CV) u pacjenta wynosi 42%. Jak należy zinterpretować ten wynik?',
        ['Zmienność glikemii jest nadmierna (CV > 36%), co oznacza wysoką niestabilność i podwyższone ryzyko hipoglikemii', 'Wartość odcięcia wynosi 36%; powyżej tej granicy krzywa cukrowa jest niestabilna.'],
        ['Glikemia jest doskonale wyrównana, cel to CV powyżej 50%', 'Im niższy współczynnik CV, tym stabilniejsza glikemia.'],
        ['CV dotyczy wyłącznie pacjentek w ciąży', 'Współczynnik CV jest uniwersalnym parametrem raportu AGP dla każdego pacjenta z CGM.']),
      q('Co mierzy sensor ciągłego monitorowania glikemii (CGM)?',
        ['Stężenie glukozy w płynie śródtkankowym tkanki podskórnej', 'Elektroda enzymatyczna reaguje z glukozą obecną w przestrzeni międzykomórkowej tkanki tłuszczowej.'],
        ['Stężenie glukozy bezpośrednio w tętnicy ramiennej', 'Sensory CGM nie są wprowadzane do naczyń krwionośnych.'],
        ['Poziom zmagazynowanego glikogenu w mięśniach szkieletowych', 'CGM mierzy wyłącznie wolną glukozę w płynie śródtkankowym.']),
      q('Sensor CGM pokazuje glikemię 65 mg/dl ze strzałką pionowo w dół, ale pacjent czuje się dobrze i zjadł obfity posiłek 15 minut temu. Co należy zrobić?',
        ['Sprawdzić glikemię glukometrem z krwi włośniczkowej z opuszki palca', 'Przy gwałtownych zmianach i rozbieżności z obrazem klinicznym pomiar kapilarny jest konieczną weryfikacją.'],
        ['Podać natychmiast 4 jednostki insuliny szybkodziałającej', 'Podanie insuliny przy wskazaniu hipoglikemii mogłoby wywołać śmiertelny spadek cukru.'],
        ['Skalibrować sensor wpisując losową wysoką wartość', 'Błędna kalibracja rozreguluje algorytm sensora na kolejne godziny.']),
    ],
  },
  {
    id: 'cukrzyca-t1d',
    title: 'Cukrzyca typu 1: Autoimmunizacja i stadia choroby',
    subtitle: 'Przeciwciała anty-GAD, IA-2, ZnT8, stadia presymptomatyczne i terapia',
    group: 'Klasyfikacja i patogeneza',
    minutes: 15,
    goals: [
      'Scharakteryzujesz autoimmunologiczny mechanizm niszczenia komórek beta trzustki.',
      'Wymienisz 3 stadia rozwoju cukrzycy typu 1 i autoprzeciwciała diagnostyczne.',
    ],
    sections: [
      {
        title: 'Autoimmunologiczne zapalenie wysp (insulitis)',
        text: 'Cukrzyca typu 1 (T1D) rozwija się u osób predysponowanych genetycznie (głównie haplotypy HLA-DR3-DQ2 i HLA-DR4-DQ8). Dochodzi do załamania autotolerancji immunologicznej i nacieku limfocytów T cytotoksycznych (CD8+) oraz pomocniczych (CD4+) na wyspy trzustkowe. Proces ten prowadzi do selektywnej, postępującej apoptozy komórek beta wytwarzających insulinę, przy zachowaniu nienaruszonych komórek alfa (glukagon) i delta (somatostatyna).',
      },
      {
        title: 'Serologia: kwartet autoprzeciwciał',
        text: 'W diagnostyce autoimmunizacji wyspowej oznacza się 4 główne przeciwciała: 1) anty-GAD65 (przeciw dekarboksylazie kwasu glutaminowego) — najdłużej utrzymujące się u dorosłych; 2) anty-IA-2 (przeciw fosfatazie tyrozynowej IA-2); 3) anty-ZnT8 (przeciw transporterowi cynku 8) — wysoce swoiste dla komórek beta; 4) IAA (przeciwciała przeciwinsulinowe) — częste u małych dzieci przed wdrożeniem leczenia insuliną. Obecność >= 2 przeciwciał daje niemal 100% ryzyko rozwoju jawnej cukrzycy w ciągu życia.',
      },
      {
        title: 'Trzystopniowa klasyfikacja stadiów cukrzycy typu 1',
        text: 'Według konsensusu JDRF/ADA wyróżnia się 3 stadia: Stadium 1 (Normoglikemia, >= 2 autoprzeciwciała, bez objawów); Stadium 2 (Dyskinezja glikemiczna: IFG/IGT/HbA1c 5,7–6,4%, >= 2 autoprzeciwciała, nadal bez objawów klinicznych); Stadium 3 (Jawna klinicznie cukrzyca z typowymi objawami: wielomocz, polidypsja, utrata masy ciała, ryzyko kwasicy ketonowej DKA). We wczesnych stadiach zastosowanie znajduje przeciwciało anty-CD3 (teplizumab) opóźniające nadejście stadium 3.',
      },
    ],
    table: {
      headers: ['Stadium T1D', 'Autoprzeciwciała', 'Status glikemii', 'Objawy kliniczne'],
      rows: [
        ['Stadium 1 (Presymptomatyczne)', '>= 2 swoiste przeciwciała (+)', 'Prawidłowa (euglikemia)', 'Brak jakichkolwiek objawów'],
        ['Stadium 2 (Przedobjawowe dysglikemiczne)', '>= 2 swoiste przeciwciała (+)', 'Nieprawidłowa (IFG lub IGT lub HbA1c 5,7–6,4%)', 'Brak objawów lub dyskretne zmęczenie'],
        ['Stadium 3 (Jawna klinicznie cukrzyca)', 'Autoprzeciwciała obecne (lub wygasłe po latach)', 'Kryteria jawnej cukrzycy (FPG >=126, glikemia >=200)', 'Wielomocz, pragnienie, chudnięcie, kwasica DKA'],
      ],
    },
    advanced:
      'Zjawisko „miodowego miesiąca” (remisja częściowa): po wdrożeniu leczenia insuliną w stadium 3 i zniesieniu glukotoksyczności ocalałe komórki beta przejściowo odzyskują zdolność wydzielniczą. Zapotrzebowanie na insulinę egzogenną może spaść poniżej 0,3–0,5 j./kg m.c./dobę przy doskonałym wyrównaniu. Nie wolno wówczas całkowicie odstawiać insuliny — minimalna dawka podtrzymuje ochronę komórek beta przed nadmiernym obciążeniem metabolicznym.',
    summary:
      'Cukrzyca typu 1 to choroba autoimmunologiczna niszcząca komórki beta. Obecność co najmniej 2 rodzajów przeciwciał (anty-GAD, IA-2, ZnT8) definiuje stadium 1, zanim pojawią się objawy kliniczne.',
    sourceIds: ['t1d_staging', 'ada_standards', 'ptd_guidelines'],
    questions: [
      q('Obecność których przeciwciał ma największą czułość w diagnostyce autoimmunologicznej cukrzycy u osób dorosłych?',
        ['Anty-GAD65 (przeciw dekarboksylazie kwasu glutaminowego)', 'Anty-GAD utrzymują się we krwi przez wiele lat po zniszczeniu wysp i są kluczowe w T1D oraz LADA.'],
        ['TRAb (przeciw receptorowi TSH)', 'TRAb są swoiste dla choroby Gravesa-Basedowa tarczycy.'],
        ['Anty-TPO (przeciw peroksydazie tarczycowej)', 'Występują w chorobie Hashimoto, choć mogą współistnieć w zespole APS-2/3.']),
      q('10-letnie dziecko ma dodatnie przeciwciała anty-GAD i anty-ZnT8, ale jego glikemie na czczo i w teście OGTT są w normie. W jakim stadium T1D się znajduje?',
        ['Stadium 1 cukrzycy typu 1', 'Dwa autoprzeciwciała przy prawidłowej glikemii definiują bezobjawowe stadium 1.'],
        ['Stadium 3 cukrzycy typu 1', 'Stadium 3 wymaga obecności jawnej hiperglikemii i objawów klinicznych.'],
        ['Nie ma cukrzycy i nigdy na nią nie zachoruje', 'Obecność dwóch przeciwciał wiąże się z niemal 100% ryzykiem progresji do stadium 3 w ciągu życia.']),
      q('Czym charakteryzuje się tzw. okres „miodowego miesiąca” (remisji częściowej) po rozpoznaniu cukrzycy typu 1?',
        ['Przejściowym spadkiem zapotrzebowania na insulinę (<0,3–0,5 j./kg/d) wskutek zniesienia glukotoksyczności', 'Zregenerowane resztkowe komórki beta podejmują wydzielanie, co stabilizuje glikemię na kilka miesięcy.'],
        ['Całkowitym wyleczeniem autoimmunizacji i brakiem konieczności dalszej kontroli', 'To tylko faza przejściowa; proces destrukcji immunologicznej postępuje dalej.'],
        ['Gwałtownym wzrostem zapotrzebowania na insulinę powyżej 2 j./kg/d', 'Wzrost zapotrzebowania cechuje fazę dekompensacji i kwasicy ketonowej, nie remisję.']),
      q('Który transporter cynku jest celem swoistych przeciwciał w cukrzycy typu 1?',
        ['ZnT8 (transporter cynku 8 w błonie ziarnistości komórek beta)', 'Cynk jest niezbędny do tworzenia heksamerów krystalicznych insuliny w ziarnistościach.'],
        ['SGLT2', 'SGLT2 to nerkowy kotransporter sodowo-glukozowy w kanalikach proksymalnych.'],
        ['GLUT4', 'GLUT4 to transporter glukozy w mięśniach i tkance tłuszczowej.']),
      q('Jaki lek biologiczny został zarejestrowany do opóźniania przejścia ze stadium 2 do jawnego stadium 3 cukrzycy typu 1?',
        ['Teplizumab (przeciwciało monoklonalne anty-CD3)', 'Modyfikuje odpowiedź limfocytów T i opóźnia nadejście jawnej klinicznie cukrzycy średnio o ok. 2–3 lata.'],
        ['Rytuksymab (anty-CD20)', 'Nie jest lekiem zarejestrowanym w tym specyficznym wskazaniu klinicznym.'],
        ['Metformina', 'Metformina nie wpływa na autoimmunologiczną destrukcję komórek beta.']),
    ],
  },
  {
    id: 'cukrzyca-t2d',
    title: 'Cukrzyca typu 2 i insulinooporność',
    subtitle: 'Złowroga ósemka (ominous octet), narządowe mechanizmy i progresja',
    group: 'Klasyfikacja i patogeneza',
    minutes: 15,
    goals: [
      'Wyjaśnisz wzajemną relację między insulinoopornością a wyczerpaniem rezerwy komórek beta.',
      'Wymienisz składowe patofizjologiczne „złowrogiej ósemki” (DeFronzo ominous octet).',
    ],
    sections: [
      {
        title: 'Błędne koło: oporność i hiperinsulinizm kompensacyjny',
        text: 'Cukrzyca typu 2 (T2D) to choroba heterogenna, w której pierwotnym zaburzeniem jest najczęściej insulinooporność tkanek obwodowych (mięśnie szkieletowe, wątroba, tkanka tłuszczowa), silnie skojarzona z otyłością brzuszną i lipotoksycznością. W początkowym etapie komórki beta odpowiadają hipersekrecją insuliny (hiperinsulinizm kompensacyjny), co utrzymuje euglikemię. Gdy komórki beta nie są w stanie sprostać zapotrzebowaniu, pojawia się IGT, a następnie jawna cukrzyca.',
      },
      {
        title: 'Złowroga ósemka DeFronzo (Ominous Octet)',
        text: 'Patogeneza T2D obejmuje defekty w wielu narządach: 1) Zmniejszone wydzielanie insuliny przez komórki beta trzustki; 2) Nadmierne wydzielanie glukagonu przez komórki alfa; 3) Zwiększona wątrobowa produkcja glukozy (glukoneogeneza); 4) Spadek wychwytu glukozy w mięśniach szkieletowych; 5) Wzmożona lipoliza w adipocytach i napływ wolnych kwasów tłuszczowych (FFA); 6) Niedobór i oporność na inkretyny (GLP-1/GIP) w jelicie cienkim; 7) Zwiększona reabsorpcja glukozy przez nerkowy kotransporter SGLT2; 8) Oporność na insulinę w podwzgórzu i zaburzenia łaknienia.',
      },
      {
        title: 'Postępujący charakter choroby i apoptoza komórek beta',
        text: 'W momencie rozpoznania cukrzycy typu 2 pacjent ma już utracone średnio 50% wyjściowej masy i funkcji wydzielniczej komórek beta. Glukotoksyczność (przewlekła hiperglikemia), lipotoksyczność (odkładanie ceramidów i diacylogliceroli) oraz odkładanie amyloidu wyspowego (IAPP/amylina) prowadzą do postępującego ubytku komórek beta o ok. 4–6% rocznie, co wyjaśnia konieczność stopniowej eskalacji farmakoterapii.',
      },
    ],
    table: {
      headers: ['Narząd / Tkanka', 'Zaburzenie w T2D', 'Konsekwencja kliniczna'],
      rows: [
        ['Wątroba', 'Oporność na hamujące działanie insuliny', 'Wzmożona glukoneogeneza -> wysoka glikemia na czczo'],
        ['Mięśnie szkieletowe', 'Upośledzona translokacja transportera GLUT4', 'Zmniejszony wychwyt glukozy -> hiperglikemia poposiłkowa'],
        ['Tkanka tłuszczowa', 'Brak hamowania lipazy hormonozależnej (HSL)', 'Wzrost FFA -> lipotoksyczność i stłuszczenie wątroby (MASLD)'],
        ['Nerki', 'Upregulacja kotransportera SGLT2', 'Zatrzymywanie nadmiaru glukozy zamiast jej wydalania'],
      ],
    },
    advanced:
      'Współczesna diabetologia rozszerza koncepcję DeFronzo do tzw. „egregious eleven” (jedenastki), dodając do patogenezy: przewlekły stan zapalny o niskim natężeniu (makrofagi M1 w tkance tłuszczowej wydzielające TNF-alfa i IL-6), dysbiozę mikrobioty jelitowej (zaburzenia produkcji krótkołańcuchowych kwasów tłuszczowych SCFA) oraz nieprawidłową sekrecję amyliny nasilającą apoptozę.',
    summary:
      'Cukrzyca typu 2 łączy insulinooporność narządową z postępującą dysfunkcją komórek beta. Współczesne leczenie (flozyny, agoniści GLP-1) uderza w wielonarządowe mechanizmy patogenezy.',
    sourceIds: ['ptd_guidelines', 'ada_standards', 'cardiovascular_easd'],
    questions: [
      q('Który narząd odpowiada za nadmierne uwalnianie glukozy na czczo u pacjenta z cukrzycą typu 2?',
        ['Wątroba wskutek nieskutecznego hamowania glukoneogenezy przez insulinę', 'Oporna na insulinę wątroba stale produkuje glukozę, mimo podwyższonego stężenia glikemii.'],
        ['Śledziona przez fagocytozę limfocytów', 'Śledziona nie produkuje wolnej glukozy do krążenia.'],
        ['Płuca poprzez utlenianie surfaktantu', 'Płuca nie pełnią roli narządu glukoneogenetycznego w organizmie.']),
      q('O ile procent średnio zredukowana jest masa/funkcja komórek beta w momencie klinicznego rozpoznania cukrzycy typu 2?',
        ['O około 50%', 'Wieloletni okres bezobjawowej insulinooporności prowadzi do utraty połowy rezerwy wydzielniczej przed postawieniem diagnozy.'],
        ['O 0% — komórki beta są całkowicie zdrowe', 'Sama insulinooporność bez defektu komórki beta nie doprowadziłaby do jawnej cukrzycy.'],
        ['O 99% jak w zaawansowanym stadium T1D', 'Utrata 99% komórek beta wywołałaby bezwzględny niedobór insuliny i kwasicę ketonową.']),
      q('Jaką rolę w patogenezie T2D odgrywa nerkowy kotransporter SGLT2?',
        ['Ulega upregulacji, powodując nieadekwatne zwrotne wchłanianie glukozy w kanalikach nerkowych mimo hiperglikemii', 'Nerki chorego z T2D paradoksalnie zatrzymują glukozę, zamiast usuwać ją z moczem.'],
        ['Rozkłada insulinę w kłębuszkach nerkowych', 'Degradacją insuliny zajmują się proteazy, a nie transporter SGLT2.'],
        ['Hamuje wydzielanie reniny przez aparat przykłębuszkowy', 'SGLT2 odpowiada za kotransport sodowo-glukozowy w kanaliku proksymalnym.']),
      q('Co to jest hiperinsulinizm kompensacyjny we wczesnej fazie patogenezy T2D?',
        ['Stan, w którym komórki beta wydzielają wielokrotnie więcej insuliny, aby przełamać oporność tkanek i utrzymać euglikemię', 'Dopiero wyczerpanie tej zdolności kompensacyjnej prowadzi do wzrostu glikemii.'],
        ['Jatrogenne przedawkowanie insuliny w pompie', 'Chodzi o proces fizjologiczny zachodzący lata przed wdrożeniem jakichkolwiek leków.'],
        ['Wydzielanie insuliny przez nowotwór insulinoma', 'To odrębna jednostka patologiczna — guz neuroendokrynny.']),
      q('Dlaczego wolne kwasy tłuszczowe (FFA) nasilają insulinooporność w mięśniach szkieletowych?',
        ['Ich metabolity (diacyloglicerole, ceramidy) aktywują kinazy PKCtheta fosforylujące serynę w IRS-1, blokując kaskadę insuliny', 'Fosforylacja serynowa zamiast tyrozynowej wyłącza przekazywanie sygnału do receptora GLUT4.'],
        ['FFA bezpośrednio wiążą się z cząsteczką glukozy we krwi, uniemożliwiając jej dyfuzję', 'Kwasy tłuszczowe nie tworzą takich kompleksów z glukozą.'],
        ['FFA niszczą receptory insulinowe na drodze fagocytozy', 'Zjawisko lipotoksyczności to wewnątrzkomórkowa dysregulacja enzymatyczna, a nie fagocytoza.']),
    ],
  },
  {
    id: 'cukrzyca-mody',
    title: 'Cukrzyca monogenowa: MODY i postacie rzadkie',
    subtitle: 'MODY 2 (GCK), MODY 3 (HNF1A), MODY 1 (HNF4A) — diagnostyka i precyzyjna terapia',
    group: 'Klasyfikacja i patogeneza',
    minutes: 16,
    goals: [
      'Wskaż cechy kliniczne nakazujące różnicowanie cukrzycy monogenowej (MODY) z T1D i T2D.',
      'Scharakteryzujesz odmienności terapeutyczne w MODY 2 (brak leczenia) i MODY 3 (pochodne sulfonylomocznika).',
    ],
    sections: [
      {
        title: 'Czym jest cukrzyca typu MODY?',
        text: 'Cukrzyca MODY (Maturity-Onset Diabetes of the Young) to grupa monogenowych postaci cukrzycy dziedziczonych autosomalnie dominująco (często wywiad w 3 kolejnych pokoleniach). Odpowiada za ok. 1–3% wszystkich przypadków cukrzycy, lecz w 80% pozostaje błędnie rozpoznana jako cukrzyca typu 1 lub 2. Cechy alarmowe to: rozpoznanie <25. roku życia, brak cech insulinooporności (szczupła sylwetka), brak autoprzeciwciał i zachowane wydzielanie peptydu C po wielu latach od diagnozy.',
      },
      {
        title: 'MODY 2 (mutacja glukokinazy GCK): łagodna hiperglikemia',
        text: 'Mutacja inaktywująca w jednym allelu genu GCK przesuwa punkt nastawczy (set-point) glukokinazy ku wyższym wartościom. Pacjent ma całożyciową, stabilną, umiarkowaną hiperglikemię na czczo (zazwyczaj 100–145 mg/dl, 5,5–8,0 mmol/l) z niewielkim przyrostem w teście OGTT (<54 mg/dl) i HbA1c 5,8–7,5%. Stan ten NIE prowadzi do przewlekłych powikłań naczyniowych i poza ciążą NIE wymaga żadnego leczenia farmakologicznego (leki doustne i insulina są nieskuteczne).',
      },
      {
        title: 'MODY 3 (mutacja HNF1A): spektakularna wrażliwość na sulfonylomocznik',
        text: 'Mutacja w genie czynnika transkrypcyjnego HNF1A (i rzadsza MODY 1 HNF4A) powoduje postępujący spadek sekrecji insuliny ujawniający się w okresie dojrzewania lub wczesnej dorosłości. Charakterystyczny jest niski próg nerkowy dla glukozy (glukozuria przy prawidłowej glikemii) i niskie stężenie hs-CRP. Złotym standardem terapii jest zamiana insuliny na małe dawki doustnych pochodnych sulfonylomocznika (np. gliklazyd), co przywraca fizjologiczną kontrolę glikemii na dziesięciolecia.',
      },
    ],
    table: {
      headers: ['Cecha', 'MODY 2 (gen GCK)', 'MODY 3 (gen HNF1A)', 'Cukrzyca typu 1 (T1D)'],
      rows: [
        ['Gen / Mechanizm', 'Glukokinaza (podwyższony set-point)', 'Czynnik HNF1A (postępująca dysfunkcja beta)', 'Autoimmunizacja komórek beta'],
        ['Glikemia na czczo', '100–145 mg/dl (stabilna przez całe życie)', 'Początkowo norma, potem narasta', 'Prawidłowa -> gwałtownie rośnie w stadium 3'],
        ['Przyrost w 120. min OGTT', 'Niski (< 54 mg/dl, < 3,0 mmol/l)', 'Bardzo wysoki (> 90 mg/dl, > 5,0 mmol/l)', 'Zmienny / bardzo wysoki'],
        ['Powikłania naczyniowe', 'Brak (przebieg łagodny)', 'Tak (jak w T1D/T2D przy złej kontroli)', 'Tak (wymagają intensywnego leczenia)'],
        ['Leczenie z wyboru', 'Brak leczenia (wyjątek: ciąża)', 'Pochodne sulfonylomocznika (małe dawki)', 'Insulinoterapia od początku'],
      ],
    },
    advanced:
      'Cukrzyca mitochondrialna (zespół MIDD — Maternally Inherited Diabetes and Deafness, mutacja m.3243A>G w mtDNA): dziedziczona wyłącznie w linii matczynej, współistnieje z odbiorczym upośledzeniem słuchu i kardiomiopatią. Bezwzględnie przeciwwskazana jest w niej metformina z powodu wysokiego ryzyka zagrażającej życiu kwasicy mleczanowej!',
    summary:
      'Cukrzyca MODY to dziedziczony dominująco defekt pojedynczego genu. MODY 2 nie wymaga leczenia, a MODY 3 doskonale odpowiada na małe dawki pochodnych sulfonylomocznika.',
    sourceIds: ['mody_genetics', 'ada_standards', 'ptd_guidelines'],
    questions: [
      q('22-letnia szczupła kobieta ma glikemie na czczo w przedziale 115–130 mg/dl od dziecka, ujemne przeciwciała anty-GAD i zachowany peptyd C. Jej matka i dziadek mają identyczne wartości. Jakie rozpoznanie należy podejrzewać?',
        ['Cukrzyca monogenowa MODY 2 (mutacja genu glukokinazy GCK)', 'Stała, bezobjawowa hiperglikemia na czczo u 3 pokoleń bez cech insulinooporności to klasyczny obraz MODY 2.'],
        ['Ciężka cukrzyca typu 2 z zespołem metabolicznym', 'Brak otyłości i stabilny przebieg u 3 pokoleń wykluczają typową postać T2D.'],
        ['Ostra dekompensacja w przebiegu cukrzycy typu 1', 'W T1D glikemia gwałtownie narasta, a przeciwciała są dodatnie w >90% przypadków.']),
      q('Jakie jest właściwe postępowanie farmakologiczne u nieciężarnego pacjenta ze zdiagnozowaną mutacją GCK (MODY 2)?',
        ['Brak jakiegokolwiek leczenia farmakologicznego; jedynie edukacja i okresowa kontrola', 'Przesunięty próg glukokinazy sprawia, że leki hipoglikemizujące są nieskuteczne, a powikłania mikronaczyniowe nie występują.'],
        ['Natychmiastowe wdrożenie pompy insulinowej', 'Insulinoterapia u osób z MODY 2 nie obniża HbA1c, ponieważ wątroba wyrównuje set-point glukagonem.'],
        ['Wysokie dawki metforminy w skojarzeniu z flozyną', 'Leki hipoglikemizujące nie są wskazane w MODY 2.']),
      q('Jaka grupa leków stanowi leczenie z wyboru w cukrzycy MODY 3 (mutacja genu HNF1A)?',
        ['Doustne pochodne sulfonylomocznika w małych dawkach (np. gliklazyd)', 'Komórki beta z defektem HNF1A wykazują niezwykłą wrażliwość na blokadę kanałów K-ATP przez sulfonylomocznik.'],
        ['Wyłącznie wielokrotne wstrzyknięcia insuliny (MDI)', 'U większości chorych z MODY 3 można bezpiecznie odstawić insulinę na rzecz tabletki sulfonylomocznika.'],
        ['Akarboza w monoterapii', 'Akarboza nie usuwa pierwotnego defektu wydzielniczego komórek beta.']),
      q('Jaka dodatkowa cecha laboratoryjna jest charakterystyczna dla pacjentów z MODY 3 (HNF1A)?',
        ['Niski próg nerkowy dla glukozy powodujący glukozurię przy glikemii < 180 mg/dl oraz bardzo niskie hs-CRP', 'HNF1A reguluje ekspresję kotransportera SGLT2 w nerkach i syntezę białka CRP w wątrobie.'],
        ['Wysokie miana przeciwciał anty-ZnT8', 'W cukrzycy monogenowej autoprzeciwciała są z reguły ujemne.'],
        ['Głęboka hipokaliemia z zasadowicą metaboliczną', 'To cecha hiperaldosteronizmu (zespół Conna), nie MODY 3.']),
      q('Dlaczego metformina jest bezwzględnie przeciwwskazana w cukrzycy mitochondrialnej (zespół MIDD)?',
        ['Zwiększa ryzyko zagrażającej życiu kwasicy mleczanowej poprzez nakładające się hamowanie kompleksu I łańcucha oddechowego', 'Wada mitochondrialna upośledza utlenianie pirogronianu, co przy metforminie gwałtownie nasila beztlenową glikolizę.'],
        ['Powoduje natychmiastową głuchotę odbiorczą', 'Głuchota jest objawem samej choroby mitochondrialnej, nie powikłaniem metforminy.'],
        ['Wchodzi w bezpośrednią interakcję z DNA mitochondrialnym', 'Metformina hamuje mitochondrialny kompleks I enzymatycznie, a nie genotoksycznie.']),
    ],
  },
  {
    id: 'cukrzyca-lada-3c',
    title: 'Cukrzyca LADA i cukrzyca wtórna (typ 3c)',
    subtitle: 'Autoimmunizacja o późnym początku, zapalenie trzustki i postacie polekowe',
    group: 'Klasyfikacja i patogeneza',
    minutes: 15,
    goals: [
      'Zdefiniujesz kryteria rozpoznania cukrzycy LADA (Latent Autoimmune Diabetes in Adults).',
      'Wskażesz cechy odróżniające pankreatogenną cukrzycę typu 3c od cukrzycy typu 2.',
    ],
    sections: [
      {
        title: 'Cukrzyca LADA: wilk w owczej skórze',
        text: 'Cukrzyca LADA (Latent Autoimmune Diabetes in Adults) to wolno postępująca postać autoimmunologicznej cukrzycy u dorosłych (zazwyczaj rozpoznawana po 30.–35. roku życia). Z powodu powolnego tempa destrukcji komórek beta pacjent początkowo nie wymaga podawania insuliny przez co najmniej 6 miesięcy od rozpoznania i często bywa błędnie diagnozowany jako cukrzyca typu 2. Z czasem rezerwa komórek beta wyczerpuje się, prowadząc do konieczności pełnej substytucji insuliną.',
      },
      {
        title: 'Triada diagnostyczna LADA',
        text: 'Do rozpoznania LADA wymagane jest spełnienie 3 kryteriów: 1) Wiek zachorowania > 30–35 lat; 2) Obecność krążących autoprzeciwciał przeciw wyspom trzustkowym (przede wszystkim wysokie miano anty-GAD65); 3) Brak konieczności stosowania insuliny przez co najmniej 6 miesięcy od momentu postawienia diagnozy. Wczesne wykrycie LADA chroni przed stosowaniem leków wyczerpujących komórki beta (np. pochodnych sulfonylomocznika) i pozwala na wczesne wdrożenie małych dawek insuliny protekcyjnej.',
      },
      {
        title: 'Cukrzyca typu 3c (pankreatogenna)',
        text: 'Cukrzyca typu 3c wynika ze zniszczenia miąższu trzustki w przebiegu przewlekłego zapalenia trzustki (PZT, >75% przypadków), resekcji chirurgicznej, mukowiscydozy (CFRD) lub hemochromatozy (tzw. cukrzyca brązowa). W odróżnieniu od T1D i T2D, w typie 3c zniszczeniu ulegają ZARÓWNO komórki beta (niedobór insuliny), jak i komórki alfa (niedobór glukagonu) oraz komórki PP. Prowadzi to do tzw. „chwiejnej cukrzycy” (brittle diabetes) ze skrajną skłonnością do ciężkich, opornych hipoglikemii.',
      },
    ],
    table: {
      headers: ['Cecha', 'Cukrzyca LADA', 'Cukrzyca typu 3c', 'Cukrzyca typu 2'],
      rows: [
        ['Etiologia', 'Autoimmunizacja (niszczenie komórek beta)', 'Zniszczenie zewnątrzwydzielnicze (PZT, resekcja)', 'Insulinooporność + względny niedobór'],
        ['Autoprzeciwciała', 'Dodatnie (głównie anty-GAD65)', 'Ujemne', 'Ujemne'],
        ['Wydzielanie glukagonu', 'Prawidłowe lub nadmierne', 'Zniesione (zniszczenie komórek alfa)', 'Nadmierne (hiperglukagonemia)'],
        ['Ryzyko hipoglikemii', 'Umiarkowane (narasta z czasem)', 'Skrajnie wysokie (brak kontrregulacji glukagonem)', 'Niskie (chyba że leczona insuliną/SU)'],
        ['Enzymy trzustkowe', 'W normie', 'Niedomoga zewnątrzwydzielnicza (niska elastaza-1 w kale)', 'W normie'],
      ],
    },
    advanced:
      'Cukrzyca posteroidowa (indukowana glikokortykosteroidami): steroidy nasilają wątrobową glukoneogenezę i potęgują insulinooporność obwodową. Charakterystyczny profil glikemii to PRAWIDŁOWY cukier rano na czczo i GWIAŹDZISTY wzrost glikemii w godzinach popołudniowych i wieczornych (szczyt po 8–12h od przyjęcia porannego prednizonu/deksametazonu). Wymaga to celowanego podawania insuliny NPH lub analogu w godzinach południowych.',
    summary:
      'LADA to wolno postępująca cukrzyca autoimmunologiczna z dodatnimi anty-GAD. Cukrzyca typu 3c łączy niedobór insuliny i glukagonu z niedomogą zewnątrzwydzielniczą trzustki.',
    sourceIds: ['ptd_guidelines', 'ada_standards', 't1d_staging'],
    questions: [
      q('Który parametr laboratoryjny jest kluczowy do odróżnienia cukrzycy LADA od klasycznej cukrzycy typu 2?',
        ['Obecność autoprzeciwciał przeciw dekarboksylazie kwasu glutaminowego (anty-GAD65)', 'Anty-GAD są dodatnie w LADA i ujemne w typowej cukrzycy typu 2.'],
        ['Stężenie cholesterolu LDL', 'Zaburzenia lipidowe występują w obu typach cukrzycy i nie mają wartości różnicującej.'],
        ['Obecność glukozy w moczu', 'Glukozuria pojawia się w każdym typie cukrzycy po przekroczeniu progu nerkowego.']),
      q('Dlaczego pacjent z cukrzycą typu 3c (po resekcji trzustki lub w PZT) ma skrajną skłonność do ciężkich hipoglikemii?',
        ['Zniszczeniu uległy również komórki alfa wysp, co uniemożliwia fizjologiczne wydzielanie glukagonu w odpowiedzi na spadek glikemii', 'Brak kontrregulacji glukagonowej pozbawia wątrobę sygnału do natychmiastowej glikogenolizy ratunkowej.'],
        ['Jego nerki filtrują insulinę 10-krotnie wolniej', 'Niewydolność trzustki nie zaburza bezpośrednio filtracji kłębuszkowej nerek.'],
        ['Wątroba całkowicie traci zdolność magazynowania glikogenu', 'Glikogen może być syntetyzowany, ale brak sygnału glukagonu blokuje jego szybkie uwalnianie.']),
      q('Jaki lek należy włączyć u pacjenta z cukrzycą typu 3c w przebiegu przewlekłego zapalenia trzustki ze stolcami tłuszczowymi?',
        ['Substytucję enzymów trzustkowych (pankreatynę w mikrosferach o opóźnionym uwalnianiu) do każdego posiłku', 'Wyrównanie trawienia tłuszczów normalizuje wchłanianie węglowodanów i stabilizuje glikemię.'],
        ['Pochodne sulfonylomocznika w maksymalnej dawce', 'Leki te stymulują komórki beta, których w zniszczonej trzustce praktycznie nie ma, a zwiększają ryzyko hipoglikemii.'],
        ['Wyłącznie restrykcyjną dietę beztłuszczową bez leków', 'Dieta bez enzymów prowadzi do ciężkiego niedożywienia i niedoboru witamin ADEK.']),
      q('Jaki jest typowy dobowy profil glikemii u pacjenta przyjmującego doustne glikokortykosteroidy (np. Encorton rano)?',
        ['Prawidłowa glikemia rano na czczo i gwałtowny wzrost hiperglikemii po południu i wieczorem', 'Farmakokinetyka doustnych steroidów osiąga szczytowy wpływ na insulinooporność w drugiej połowie dnia.'],
        ['Bardzo wysoki cukier wyłącznie o 3:00 w nocy', 'To zjawisko brzasku lub efekt Somogyi, nie typowy profil posteroidowy.'],
        ['Stała ciężka hipoglikemia przez całą dobę', 'Steroidy są hormonami hiperglikemizującymi, nasilającymi glukoneogenezę.']),
      q('Jakie postępowanie farmakologiczne zaleca się po potwierdzeniu rozpoznania LADA, nawet gdy pacjent ma jeszcze dobrą kontrolę na diecie?',
        ['Wczesne wdrożenie małych dawek insuliny w celu odciążenia i protekcji ocalałych komórek beta', 'Wczesna insulinoterapia wydłuża czas przeżycia komórek beta i zapobiega wczesnej dekompensacji.'],
        ['Intensywne leczenie pochodną sulfonylomocznika', 'Pochodne sulfonylomocznika przyspieszają apoptozę komórek beta w procesie autoimmunologicznym.'],
        ['Odstawienie wszelkich leków i kontrola za 5 lat', 'Zaniechanie opieki grozi nagłą kwasicą ketonową.']),
    ],
  },
];
