import { type DraftLesson, q } from './course-types.ts';

export const draftDiabetesPart2: DraftLesson[] = [
  {
    id: 'cukrzyca-dka',
    title: 'Cukrzycowa kwasica ketonowa (DKA)',
    subtitle: 'Patofizjologia, luka anionowa, protokół nawadniania i insulinoterapii',
    group: 'Ostre stany i powikłania',
    minutes: 17,
    goals: [
      'Wyjaśnisz mechanizm rozwoju kwasicy metabolicznej z podwyższoną luką anionową w DKA.',
      'Przedstawisz priorytety resuscytacji: płynoterapia, wlew insuliny i warunki suplementacji potasu.',
    ],
    sections: [
      {
        title: 'Bezwzględny niedobór insuliny i kaskada ketogenezy',
        text: 'Cukrzycowa kwasica ketonowa (DKA) jest ostrym, zagrażającym życiu powikłaniem wynikającym z bezwzględnego (lub głębokiego względnego) niedoboru insuliny przy jednoczesnym wyrzucie hormonów kontrregulacyjnych (glukagon, katecholaminy, kortyzol, GH). Skutkuje to odhamowaniem lipazy hormonozależnej (HSL) w tkance tłuszczowej, masowym uwalnianiem wolnych kwasów tłuszczowych do wątroby i ich beta-oksydacją do ciał ketonowych (kwas acetooctowy i beta-hydroksymasłowy).',
      },
      {
        title: 'Triada rozpoznania DKA',
        text: 'Do rozpoznania DKA wymagane jest jednoczesne stwierdzenie: 1) Hiperglikemii (zwykle > 250 mg/dl [13,9 mmol/l], choć w kwasicy euglikemicznej np. po flozynach może być < 200 mg/dl); 2) Kwasicy metabolicznej: pH krwi tętniczej/żylnej <= 7,30 i stężenie wodorowęglanów HCO3- < 18 mmol/l; 3) Ketonemii (stężenie beta-hydroksymaślanu we krwi >= 3,0 mmol/l) lub nasilonej ketonurii (>= ++). Luka anionowa (AG = Na+ - [Cl- + HCO3-]) jest podwyższona (> 10–12 mmol/l).',
      },
      {
        title: 'Algorytm resuscytacji: płyny, potas i insulina',
        text: 'Postępowanie opiera się na 4 filarach: 1) Płynoterapia: przetoczenie 1000 ml 0,9% NaCl w 1. godzinie, następnie 250–500 ml/h krystaloidów zbilansowanych (płyn Ringera); deficyt płynowy wynosi 5–8 litrów (ok. 100 ml/kg); 2) Wlew insuliny: dożylny wlew insuliny krótko- lub szybkodziałającej 0,1 j./kg/h (lub bolus 0,1 j./kg i wlew 0,1 j./kg/h); 3) Potas: ŻELAZNA ZASADA — NIE włączaj insuliny, jeśli K+ < 3,3 mmol/l (insulina wpycha K+ do komórek i grozi zgonem z zatrzymania krążenia!); 4) Włączenie 5% glukozy, gdy glikemia spadnie < 200–250 mg/dl, aby umożliwić dalszy wlew insuliny aż do ustąpienia kwasicy i spadku beta-hydroksymaślanu < 0,6 mmol/l (lub pH > 7,30 i HCO3- >= 18 mmol/l).',
      },
    ],
    table: {
      headers: ['Parametr', 'Łagodna DKA', 'Umiarkowana DKA', 'Ciężka DKA'],
      rows: [
        ['pH krwi tętniczej', '7,25–7,30', '7,00–7,24', '< 7,00'],
        ['Stężenie HCO3- (mmol/l)', '15–18', '10–14', '< 10'],
        ['Beta-hydroksymaślan', '>= 3,0 mmol/l', '>= 3,0 mmol/l', 'Często > 6,0 mmol/l'],
        ['Luka anionowa (AG)', '> 10 mmol/l', '> 12 mmol/l', '> 12 mmol/l'],
        ['Stan świadomości', 'Zachowana', 'Senność / podsypianie', 'Śpiączka / stupor (wymaga OIT)'],
      ],
    },
    advanced:
      'Euglikemiczna kwasica ketonowa (euDKA): rozwija się najczęściej u chorych stosujących inhibitory SGLT2 (flozyny) w okresie infekcji, zabiegu operacyjnego lub głodówki. Cukromocz indukowany flozyną utrzymuje glikemię <200 mg/dl, ale hipoinsulinemia i wzrost glukagonu wyzwalają masową ketogenezę. Każdy pacjent na flozynie z nudnościami i dusznością Kussmaula wymaga natychmiastowego oznaczenia gazometrii i ciał ketonowych we krwi!',
    summary:
      'DKA to kwasica metaboliczna z wysoką luką anionową i ketonemią. W leczeniu priorytetem jest nawodnienie i potas; wlew insuliny podaje się dopiero przy K+ >= 3,3 mmol/l.',
    sourceIds: ['dka_guidelines', 'ptd_guidelines', 'ada_standards'],
    questions: [
      q('Jakie jest kryterium wyjściowego stężenia potasu zezwalające na rozpoczęcie dożylnego wlewu insuliny w DKA?',
        ['Potas w surowicy musi wynosić co najmniej 3,3 mmol/L', 'Podanie insuliny przy niższym stężeniu grozi nagłą śmiercią w mechanizmie arytmii komorowej wskutek hipokaliemii.'],
        ['Potas musi przekraczać 6,0 mmol/L', 'Taka wartość oznacza hiperkaliemię, w której insulina jest bezpieczna, ale nie stanowi to dolnego progu.'],
        ['Stężenie potasu nie ma znaczenia przed podaniem insuliny', 'To kardynalny błąd medyczny zagrażający życiu chorego.']),
      q('Dlaczego po obniżeniu glikemii poniżej 200–250 mg/dl w trakcie leczenia DKA podłącza się wlew 5% glukozy?',
        ['Aby zapobiec hipoglikemii i umożliwić kontynuację wlewu insuliny aż do całkowitego ustąpienia kwasicy i ketonemii', 'Celem leczenia DKA jest zlikwidowanie kwasicy ketonowej, a nie samo zbicie cukru.'],
        ['Aby natychmiast wywołać glukozurię', 'Glukozuria nie jest celem terapeutycznym w leczeniu DKA.'],
        ['Glukoza dożylna bezpośrednio buforuje jony wodorowe', 'Glukoza nie jest buforem kwasowo-zasadowym.']),
      q('Który metabolit ketonowy we krwi jest najczulszym wskaźnikiem monitorowania leczenia DKA?',
        ['Kwas beta-hydroksymasłowy (beta-hydroksymaślan)', 'W kwasicy ketonowej stosunek beta-hydroksymaślanu do acetooctanu wynosi nawet 10:1.'],
        ['Aceton w moczu oznaczany testem paskowym ze nitroprusydkiem', 'Paski moczowe nie wykrywają beta-hydroksymaślanu i mogą dawać wynik fałszywie ujemny.'],
        ['Kwas mlekowy w surowicy', 'Mleczan jest markerem hipoperfuzji tkankowej, a nie ciał ketonowych.']),
      q('Jaki czynnik jest najczęstszą przyczyną tzw. euglikemicznej kwasicy ketonowej (euDKA)?',
        ['Stosowanie inhibitorów kotransportera SGLT2 (flozyn) w połączeniu ze stresem metabolicznym lub zabiegiem', 'Cukromocz maskuje hiperglikemię, utrzymując glikemię < 200 mg/dl mimo narastającej ketozy.'],
        ['Przedawkowanie metforminy', 'Metformina powoduje kwasicę mleczanową, a nie euglikemiczną ketonową.'],
        ['Nadmierne spożycie soli kuchennej', 'Chlorek sodu może wywołać kwasicę hiperchloremiczną, nie ketonową.']),
      q('Kiedy uznaje się kwasicę ketonową (DKA) za wyleczoną (kryteria ustąpienia DKA)?',
        ['Glikemia < 200 mg/dl, beta-hydroksymaślan < 0,6 mmol/l (lub pH > 7,30 i HCO3- >= 18 mmol/l) oraz powrót łaknienia', 'Wg konsensusu ADA/EASD 2024 i PTD 2025 kryterium ustąpienia to spadek beta-OHB < 0,6 mmol/l (lub pH > 7,30 z HCO3- >= 18) przy glikemii < 200 mg/dl i możliwości przyjmowania posiłków.'],
        ['Gdy glikemia spadnie do 90 mg/dl niezależnie od pH', 'Spadek glikemii następuje znacznie szybciej niż ustąpienie kwasicy metabolicznej.'],
        ['Gdy pacjent przestanie odczuwać pragnienie', 'Subiektywne pragnienie nie jest parametrem laboratoryjnym ustąpienia kwasicy.']),
    ],
  },
  {
    id: 'cukrzyca-hhs',
    title: 'Zespół hiperglikemiczno-hiperosmolarny (HHS)',
    subtitle: 'Różnicowanie z DKA, osmolalność efektywna, skrajne odwodnienie i powolna rehydratacja',
    group: 'Ostre stany i powikłania',
    minutes: 16,
    goals: [
      'Wymienisz kryteria diagnostyczne różniące zespół HHS od kwasicy DKA.',
      'Obliczysz osmolalność efektywną osocza i wyjaśnisz ryzyko powikłań zakrzepowo-zatorowych.',
    ],
    sections: [
      {
        title: 'Czym jest stan hiperglikemiczno-hiperosmolarny (HHS)?',
        text: 'HHS (Hyperosmolar Hyperglycemic State) występuje głównie u starszych chorych na cukrzycę typu 2, często wyzwalany przez ostre zakażenie (zapalenie płuc, ZUM), udar mózgu, zawał serca lub odwodnienie. Resztkowe wydzielanie endogennej insuliny wystarcza do zablokowania lipolizy i ketogenezy w wątrobie, ale nie wystarcza do obwodowego zużycia glukozy. Prowadzi to do potężnej diurezy osmotycznej, skrajnego odwodnienia (deficyt płynów 100–220 ml/kg, 8–12 litrów) i hiperosmolalności osocza.',
      },
      {
        title: 'Kryteria laboratoryjne HHS',
        text: 'Rozpoznanie HHS opiera się na 4 cechach: 1) Skrajna hiperglikemia (zwykle > 600 mg/dl [33,3 mmol/l], nierzadko > 1000 mg/dl); 2) Efektywna osmolalność osocza > 320 mOsm/kg H2O; 3) Brak istotnej kwasicy metabolicznej (pH krwi tętniczej > 7,30, wodorowęglany HCO3- > 18 mmol/l); 4) Ujemne lub śladowe ciała ketonowe w surowicy i moczu. Śmiertelność w HHS (10–20%) jest znacznie wyższa niż w DKA (1–2%).',
      },
      {
        title: 'Resuscytacja: ostrożna rehydratacja i profilaktyka heparyną',
        text: 'Głównym celem jest powolne wyrównanie osmolalności — spadek glikemii nie powinien przekraczać 50–70 mg/dl/h (3–4 mmol/l/h), a spadek osmolalności 3 mOsm/kg/h, aby zapobiec obrzękowi mózgu. Podstawą jest 0,9% NaCl (lub 0,45% NaCl, gdy sód skorygowany jest wysoki). Z powodu zagęszczenia krwi i hiperlepkości chorzy mają ogromne ryzyko powikłań zakrzepowo-zatorowych (udar, zatorowość płucna) — rutynowo podaje się heparynę drobnocząsteczkową (HDCz) w dawkach profilaktycznych.',
      },
    ],
    table: {
      headers: ['Cecha kliniczna', 'Zespół hiperosmolarny (HHS)', 'Kwasica ketonowa (DKA)'],
      rows: [
        ['Typowi pacjenci', 'Seniorzy z cukrzycą typu 2', 'Młodzi z cukrzycą typu 1'],
        ['Glikemia typowa', '> 600 mg/dl (często > 1000 mg/dl)', '250–600 mg/dl (lub euglikemia)'],
        ['Kwasica metaboliczna', 'Brak (pH > 7,30, HCO3- > 18)', 'Obecna (pH <= 7,30, HCO3- < 18)'],
        ['Ketonemia', 'Ujemna lub śladowa (< 3,0 mmol/l)', 'Silnie dodatnia (>= 3,0 mmol/l)'],
        ['Osmolalność efektywna', '> 320 mOsm/kg H2O', 'Zwykle < 320 mOsm/kg H2O'],
        ['Deficyt płynowy', 'Skrajny: 8–12 litrów (15–20% m.c.)', 'Umiarkowany: 4–6 litrów (5–10% m.c.)'],
      ],
    },
    advanced:
      'Wzór na efektywną osmolalność osocza: Osm_eff = 2 * [Na+] + Glukoza [mg/dl] / 18 (wszystko w mmol/L lub po przeliczeniu mg/dl). Mocznik nie jest osmolitem efektywnym, ponieważ swobodnie dyfunduje przez błony komórkowe i nie wywołuje przesunięć wody między przestrzenią wewnątrz- i zewnątrznaczyniową.',
    summary:
      'HHS to stan skrajnej hiperglikemii (>600 mg/dl) i hiperosmolalności (>320 mOsm/kg) bez kwasicy ketonowej. Wymaga powolnego nawadniania i profilaktyki heparyną.',
    sourceIds: ['dka_guidelines', 'ada_standards', 'ptd_guidelines'],
    questions: [
      q('Dlaczego u chorych z HHS nie dochodzi do rozwoju kwasicy ketonowej?',
        ['Resztkowa endogenna insulina wystarcza do zahamowania lipolizy w tkance tłuszczowej i ketogenezy w wątrobie', 'Stężenie insuliny potrzebne do hamowania lipolizy jest 10-krotnie niższe niż do stymulacji wychwytu glukozy.'],
        ['Wątroba pacjenta nie posiada enzymów do produkcji ciał ketonowych', 'Wątroba ma komplet enzymów, ale brak sygnału lipolitycznego nie dostarcza substratów.'],
        ['Nerki filtrują ciała ketonowe 100 razy szybciej niż glukozę', 'Filtracja ketonów nie chroni przed zakwaszeniem krwi.']),
      q('Jaka jest wartość progowa efektywnej osmolalności osocza w kryteriach rozpoznania HHS?',
        ['Powyżej 320 mOsm/kg H2O', 'Wartość ta koreluje z zaburzeniami świadomości, stuporem i śpiączką hiperosmolarną.'],
        ['Powyżej 150 mOsm/kg H2O', '150 mOsm/kg to stan skrajnej hipoosmolalności zagrażający obrzękiem mózgu.'],
        ['Dokładnie 285 mOsm/kg H2O', '285 mOsm/kg to prawidłowa fizjologiczna osmolalność osocza u człowieka.']),
      q('Dlaczego u każdego pacjenta z HHS należy wdrożyć profilaktykę przeciwzakrzepową heparyną drobnocząsteczkową?',
        ['Skrajne odwodnienie i hiperglikemia wywołują hiperlepkość krwi, zwiększając ryzyko zakrzepicy żylnej i tętniczej', 'Zatorowość płucna i udar są głównymi przyczynami zgonów w zespole HHS.'],
        ['Heparyna bezpośrednio obniża stężenie glukozy we krwi', 'Heparyna nie ma właściwości hipoglikemizujących.'],
        ['Heparyna zapobiega utracie potasu z moczem', 'Heparyna może wręcz podnosić potas przez hamowanie aldosteronu.']),
      q('Dlaczego zbyt szybkie obniżanie glikemii i osmolalności w HHS jest niebezpieczne?',
        ['Grozi gwałtownym przemieszczeniem wody do neuronów i obrzękiem mózgu', 'Mózg adaptuje się do hiperosmolalności generując osmoprotektanty (idiogenne osmolity).'],
        ['Wywołuje natychmiastowe uszkodzenie siatkówki', 'Obrzęk mózgu i zapaść naczyniowa są bezpośrednim zagrożeniem życia.'],
        ['Zwiększa tempo powstawania ciał ketonowych', 'Spadek glikemii nie nasila ketogenezy przy prawidłowym wlewie płynów.']),
      q('76-letni mężczyzna z glikemią 840 mg/dl, sodem 148 mmol/l, pH 7,38, HCO3- 22 mmol/l i ujemnymi ketonami ma rozpoznanie:',
        ['Zespół hiperglikemiczno-hiperosmolarny (HHS)', 'Wysoka glikemia, brak kwasicy i ujemne ketony jednoznacznie wskazują na HHS.'],
        ['Ciężka cukrzycowa kwasica ketonowa (DKA)', 'W DKA pH wynosi <= 7,30, wodorowęglany < 18, a ketonemia jest wysoka.'],
        ['Kwasica mleczanowa w przebiegu sepsy', 'Prawidłowe pH 7,38 i HCO3- 22 wykluczają kwasicę metaboliczną.']),
    ],
  },
  {
    id: 'cukrzyca-hipoglikemia',
    title: 'Hipoglikemia i zaburzenia świadomości hipoglikemii',
    subtitle: 'Triada Whipple’a, reguła 15/15, glukagon, neuroglikopenia i zjawisko HAAF',
    group: 'Ostre stany i powikłania',
    minutes: 15,
    goals: [
      'Sklasyfikujesz 3 stopnie ciężkości hipoglikemii wg PTD/ADA oraz triadę Whipple’a.',
      'Wdrożysz prawidłowe postępowanie w hipoglikemii lekkiej (reguła 15/15) oraz ciężkiej (glukagon, 20% glukoza).',
    ],
    sections: [
      {
        title: 'Definicja, triada Whipple’a i klasyfikacja poziomów',
        text: 'Hipoglikemię kliniczną u chorych na cukrzycę definiuje stężenie glukozy we krwi < 70 mg/dl (3,9 mmol/l). U osób bez cukrzycy rozpoznanie wymaga spełnienia klasycznej triady Whipple’a: 1) Objawy hipoglikemii; 2) Niskie stężenie glukozy we krwi potwierdzone laboratoryjnie; 3) Natychmiastowe ustąpienie objawów po podaniu węglowodanów. ADA i PTD wyróżniają 3 poziomy: Poziom 1 (Alert: 54–69 mg/dl); Poziom 2 (Klinicznie istotna: < 54 mg/dl); Poziom 3 (Ciężka hipoglikemia: upośledzenie funkcji poznawczych wymagające pomocy osób trzecich, niezależnie od wartości glikemii).',
      },
      {
        title: 'Objawy adrenergiczne vs neuroglikopeniczne',
        text: 'W odpowiedzi na spadek glikemii najpierw uruchamia się układ współczulny i wyrzut adrenaliny (objawy autonomiczne/adrenergiczne): tachykardia, drżenie rąk, zlewne zimne poty, niepokój, bladość i uczucie głodu. Dalszy spadek glikemii pozbawia neurony glukozy (objawy neuroglikopeniczne): zaburzenia koncentracji, podwójne widzenie, bełkotliwa mowa, zmiana zachowania (agresja lub euforia), drgawki, utrata przytomności i śpiączka hipoglikemiczna.',
      },
      {
        title: 'Zasady leczenia i nieświadomość hipoglikemii (HAAF)',
        text: 'W hipoglikemii lekkiej (pacjent przytomny) obowiązuje reguła 15/15: spożycie 15 g szybkich węglowodanów (sok owocowy, glukoza w żelu, tabletki; unikać czekolady, gdyż tłuszcz spowalnia wchłanianie!), odczekanie 15 minut i kontrola glikemii. W hipoglikemii ciężkiej (brak przytomności): natychmiast ułożenie w pozycji bezpiecznej, podanie glukagonu (1 mg domięśniowo/podskórnie lub 3 mg donosowo — preparat Baqsimi) lub dożylny wlew 20% glukozy. Nieświadomość hipoglikemii (HAAF) rozwija się przez powtarzające się spadki glikemii wygaszające odpowiedź adrenergiczną — wymaga czasowego podwyższenia celów glikemii na 2–3 tygodnie.',
      },
    ],
    table: {
      headers: ['Poziom hipoglikemii', 'Kryterium stężenia', 'Objawy', 'Postępowanie ratunkowe'],
      rows: [
        ['Poziom 1 (Alert)', '54–69 mg/dl (3,0–3,8 mmol/l)', 'Adrenergiczne (drżenie, poty, głód)', 'Reguła 15/15: 15 g prostych węglowodanów'],
        ['Poziom 2 (Istotna)', '< 54 mg/dl (< 3,0 mmol/l)', 'Neuroglikopenia (splątanie, zaburzenia mowy)', 'Węglowodany proste, powtórzenie po 15 min'],
        ['Poziom 3 (Ciężka)', 'Każde stężenie wymagające pomocy', 'Utrata przytomności, drgawki, śpiączka', 'Glukagon 1 mg i.m. / 3 mg donosowo lub 20% glukoza i.v.'],
      ],
    },
    advanced:
      'Zjawisko HAAF (Hypoglycemia-Associated Autonomic Failure): każdy epizod hipoglikemii obniża próg wydzielania adrenaliny przy kolejnym spadku glikemii. Mózg przestaje wysyłać sygnały ostrzegawcze (drżenie, poty), a pierwszym objawem staje się od razu nagła utrata przytomności. Ścisłe unikanie glikemii <70 mg/dl przez zaledwie 2–3 tygodnie pozwala na zresetowanie receptorów mózgowych i odzyskanie świadomości hipoglikemii!',
    summary:
      'Hipoglikemia <70 mg/dl wymaga reguły 15/15. Ciężka hipoglikemia z utratą przytomności wymaga glukagonu (i.m. lub donosowo) bądź 20% glukozy i.v. i bezwzględnego zakazu pojenia doustnego.',
    sourceIds: ['ptd_guidelines', 'ada_standards', 'cgm_consensus'],
    questions: [
      q('Na czym polega zasada 15/15 w leczeniu lekkiej hipoglikemii u przytomnego pacjenta?',
        ['Spożycie 15 g cukrów prostych, odczekanie 15 minut i ponowna kontrola glikemii', 'Zapewnia to szybki przyrost glikemii bez wywoływania wtórnej ciężkiej hiperglikemii.'],
        ['Podanie 15 jednostek insuliny i odczekanie 15 minut', 'Insulina drastycznie pogłębiłaby zagrażający życiu stan hipoglikemii.'],
        ['Wypicie 15 szklanek mleka w 15 minut', 'Nadmiar płynów i białka opóźnia wchłanianie i grozi wymiotami.']),
      q('Dlaczego czekolada lub batony z kremem NIE są polecane do szybkiego wyprowadzania z hipoglikemii?',
        ['Wysoka zawartość tłuszczu opóźnia opróżnianie żołądka i spowalnia wchłanianie glukozy do krwi', 'Do szybkiej interwencji nadają się wyłącznie czyste roztwory wodne glukozy lub soki.'],
        ['Czekolada bezpośrednio neutralizuje glukagon w wątrobie', 'Tłuszcz spowalnia perystaltykę przewodu pokarmowego, nie neutralizuje hormonów.'],
        ['Czekolada wywołuje natychmiastową kwasicę ketonową', 'Tłuszcz nie wywołuje ostrej ketozy w 15 minut.']),
      q('Co należy podać nieprzytomnemu pacjentowi z cukrzycą z podejrzeniem ciężkiej hipoglikemii w warunkach domowych?',
        ['Glukagon 1 mg domięśniowo/podskórnie lub 3 mg donosowo (preparat Baqsimi)', 'Glukagon uwalnia zapasy glikogenu wątrobowego i jest bezpieczny do podania przez przeszkoloną rodzinę.'],
        ['Podać doustnie ciepłą herbatę z 5 łyżeczkami cukru', 'Podawanie płynów nieprzytomnemu grozi zachłyśnięciem, zachłystowym zapaleniem płuc i uduszeniem!'],
        ['Wstrzyknąć 10 jednostek insuliny bazowej', 'Insulina pogłębiłaby hipoglikemię ze skutkiem śmiertelnym.']),
      q('Jak definiuje się zjawisko nieświadomości hipoglikemii (HAAF)?',
        ['Brak wczesnych objawów adrenergicznych (drżenie, poty) przed wystąpieniem objawów neuroglikopenii', 'Próg alarmowy przesuwa się poniżej progu zaburzeń funkcji mózgu.'],
        ['Świadome ignorowanie zaleceń lekarskich przez pacjenta', 'To zaburzenie fizjologiczne autonomicznego układu nerwowego, nie cecha behawioralna.'],
        ['Występowanie hipoglikemii wyłącznie w czasie snu', 'HAAF dotyczy braku percepcji objawów zarówno w dzień, jak i w nocy.']),
      q('Który lek u chorych z cukrzycą może maskować objawy ostrzegawcze hipoglikemii (drżenie, tachykardię)?',
        ['Nieselektywne beta-adrenolityki (np. propranolol)', 'Blokada receptorów beta tłumi adrenergiczne objawy tachykardii i drżenia (z wyjątkiem pocenia się).'],
        ['Statyny (np. atorwastatyna)', 'Statyny nie blokują receptorów układu współczulnego.'],
        ['Inhibitory pompy protonowej (np. pantoprazol)', 'IPP nie wpływają na percepcję adrenergicznych objawów hipoglikemii.']),
    ],
  },
  {
    id: 'cukrzyca-powiklania-naczyniowe',
    title: 'Przewlekłe powikłania naczyniowe cukrzycy',
    subtitle: 'Nefropatia (DKD), retinopatia, polineuropatia obwodowa i nefroprotekcja',
    group: 'Ostre stany i powikłania',
    minutes: 17,
    goals: [
      'Opiszesz patogenezę i stadia cukrzycowej choroby nerek (DKD) oraz kryteria albuminurii.',
      'Wskażesz filary nowoczesnej nefro- i kardioprotekcji: ACEI/ARB, flozyny (SGLT2i) i finerenon.',
    ],
    sections: [
      {
        title: 'Mikroangiopatia: naczynia włosowate na celowniku',
        text: 'Przewlekła hiperglikemia uszkadza śródbłonek naczyń włosowatych na drodze 4 szlaków biochemicznych: 1) Aktywacji szlaku poliolowego (sorbitol, spadek NADPH); 2) Tworzenia zaawansowanych produktów końcowych glikacji (AGE) wiążących receptor RAGE; 3) Aktywacji kinazy białkowej C (PKC); 4) Przeciążenia szlaku heksozaminowego. Prowadzi to do pogrubienia błony podstawnej, utraty perycytów i mikrotętniaków w siatkówce, kłębuszkach nerkowych i nerwach obwodowych.',
      },
      {
        title: 'Cukrzycowa choroba nerek (DKD): albuminuria i eGFR',
        text: 'DKD jest wiodącą przyczyną schyłkowej niewydolności nerek na świecie. Wczesnym markerem jest umiarkowanie zwiększona albuminuria (wskaźnik albumina/kreatynina w moczu UACR 30–300 mg/g; dawniej mikroalbuminuria), która z czasem przechodzi w albuminurię jawną (UACR > 300 mg/g) i spadek filtracji kłębuszkowej eGFR. Badania przesiewowe (UACR i eGFR) wykonuje się raz w roku od momentu rozpoznania T2D oraz po 5 latach trwania T1D.',
      },
      {
        title: 'Filary nowoczesnej nefroprotekcji w cukrzycy',
        text: 'Złoty standard spowalniania progresji DKD opiera się na 4 filarach o udowodnionym twardym punkcie końcowym: 1) Blokada układu RAA (inhibitor ACE lub sartan ARB w maksymalnej tolerowanej dawce); 2) Inhibitor SGLT2 (dapagliflozyna lub empagliflozyna) — zmniejsza ciśnienie wewnątrzkłębuszkowe i hiperfiltrację; 3) Niesteroidowy antagonista receptora mineralokortykoidowego (finerenon) — silnie redukuje stan zapalny i włóknienie nerek; 4) Agonista receptora GLP-1 (np. semaglutyd).',
      },
    ],
    table: {
      headers: ['Powikłanie mikronaczyniowe', 'Metoda screeningu', 'Kryteria wczesnego wykrycia', 'Kluczowa interwencja'],
      rows: [
        ['Nefropatia (DKD)', 'UACR w porannej próbce moczu + eGFR', 'UACR >= 30 mg/g lub eGFR < 60 ml/min', 'ACEI/ARB + Flozyna (SGLT2i) + Finerenon'],
        ['Retinopatia cukrzycowa', 'Badanie dna oka po rozszerzeniu źrenic', 'Mikrotętniaki, wysięki twarde, mikrowylewy', 'Dobra kontrola glikemii/RR, laserokoagulacja, anty-VEGF'],
        ['Polineuropatia dystalna', 'Monofilament 10 g, kamerton 128 Hz', 'Utrata czucia ucisku / wibracji (ryzyko stopy)', 'Pregabalina, duloksetyna, codzienna inspekcja stóp'],
        ['Autonomiczna neuropatia', 'Próba ortostatyczna, EKG (HRV)', 'Spadek RR skurczowego > 20 mmHg po pionizacji', 'Nawodnienie, pończochy uciskowe, midodryna'],
      ],
    },
    advanced:
      'Paradoks hemodynamiczny flozyn: wdrożenie inhibitora SGLT2 powoduje przejściowy, fizjologiczny spadek eGFR o 3–5 ml/min/1,73m2 w pierwszych tygodniach (tzw. initial dip) wskutek obkurczenia tętniczki doprowadzającej przez przywrócenie sprzężenia kanalikowo-kłębuszkowego (TGF). Spadek ten NIE jest uszkodzeniem nerek — świadczy o odciążeniu mechanicznym kłębuszka i chroni nerkę przed schyłkową mocznicą w długim okresie!',
    summary:
      'Przewlekłe powikłania mikronaczyniowe (nerki, oczy, nerwy) wymagają corocznego screeningu. Podstawą nefroprotekcji jest skojarzenie ACEI/ARB z inhibitorem SGLT2 i finerenonem.',
    sourceIds: ['ckd_diabetes', 'ptd_guidelines', 'ada_standards'],
    questions: [
      q('Jaki parametr jest najczulszym wskaźnikiem wczesnego uszkodzenia nerek w przebiegu cukrzycy?',
        ['Wskaźnik albumina/kreatynina w moczu (UACR >= 30 mg/g)', 'Wzrost wydalania albuminy wyprzedza spadek wskaźnika eGFR o wiele lat.'],
        ['Stężenie mocznika w surowicy', 'Mocznik rośnie dopiero w zaawansowanej, schyłkowej niewydolności nerek.'],
        ['Białko całkowite w moczu oznaczane metodą biuretową', 'Metoda ta wykrywa białkomocz dopiero powyżej 300–500 mg/dobę (przeoczy wczesne stadium).']),
      q('Jakie skojarzenie leków stanowi współczesny filar nefroprotekcji u pacjenta z cukrzycą typu 2 i albuminurią UACR > 300 mg/g?',
        ['Inhibitor ACE (lub ARB) + inhibitor SGLT2 (flozyna) + niesteroidowy MRA (finerenon)', 'Terapia potrójna redukuje ryzyko dializoterapii i zgonu sercowo-naczyniowego o ponad 40%.'],
        ['Jednoczesne podanie inhibitora ACE i sartanu w podwójnej dawce', 'Skojarzenie ACEI + ARB jest błędem sztuki — drastycznie zwiększa ryzyko ostrego uszkodzenia nerek (AKI).'],
        ['Furosemid z hydrochlorotiazydem w monoterapii', 'Diuretyki nie mają bezpośredniego działania hamującego włóknienie kłębuszków.']),
      q('Co oznacza tzw. „initial dip” (przejściowy spadek eGFR o 3–5 ml/min) po rozpoczęciu leczenia flozyną (inhibitorem SGLT2)?',
        ['Fizjologiczny spadek ciśnienia wewnątrzkłębuszkowego chroniący nerkę przed hiperfiltracją', 'Zjawisko to jest w pełni odwracalne i dowodzi skutecznego odciążenia hemodynamicznego nefronu.'],
        ['Ostre toksyczne uszkodzenie cewek nerkowych wymagające natychmiastowego odstawienia leku', 'Odstawienie flozyny z powodu spadku < 30% pozbawia pacjenta kluczowej nefroprotekcji.'],
        ['Błąd pomiarowy laboratorium', 'To powtarzalny, udowodniony mechanizm farmakodynamiczny.']),
      q('Jak często należy wykonywać badanie dna oka po rozszerzeniu źrenic u pacjenta z nowo rozpoznaną cukrzycą typu 2?',
        ['Natychmiast w momencie rozpoznania cukrzycy, a następnie co 1–2 lata', 'W T2D okres bezobjawowej hiperglikemii przed diagnozą sprawia, że nawet 20% chorych ma już retinopatię.'],
        ['Dopiero po 10 latach od rozpoznania', 'Zbyt późny screening grozi przeoczeniem proliferacji naczyniowej i nieodwracalną utratą wzroku.'],
        ['Wyłącznie wtedy, gdy pacjent zgłasza ból gałki ocznej', 'Retinopatia cukrzycowa nie boli w żadnym stadium zaawansowania.']),
      q('Czym charakteryzuje się dystalna symetryczna polineuropatia cukrzycowa w badaniu fizykalnym?',
        ['Utratą czucia wibracji (kamerton) i dotyku (monofilament 10 g) o typie „rękawiczek i skarpetek”', 'Objawy postępują od najdłuższych włókien nerwowych kończyn dolnych ku górze.'],
        ['Porażeniem połowiczym z wygórowaniem odruchów', 'To obraz udaru mózgu (uszkodzenie ośrodkowego neuronu ruchowego), nie polineuropatii.'],
        ['Wyłącznie drżeniem spoczynkowym kciuka', 'Drżenie spoczynkowe to cecha choroby Parkinsona.']),
    ],
  },
  {
    id: 'cukrzyca-leki-nieinsulinowe',
    title: 'Farmakoterapia nieinsulinowa w cukrzycy typu 2',
    subtitle: 'Metformina, inhibitory SGLT2, agoniści GLP-1/GIP i inhibitory DPP-4',
    group: 'Farmakoterapia i sytuacje szczególne',
    minutes: 17,
    goals: [
      'Wyjaśnisz mechanizmy działania, korzyści sercowo-nerkowe i przeciwwskazania flozyn oraz agonistów GLP-1.',
      'Scharakteryzujesz zasady dawkowania i bezpieczeństwa metforminy w zależności od eGFR.',
    ],
    sections: [
      {
        title: 'Metformina: fundament terapii i zasady bezpieczeństwa',
        text: 'Metformina (pochodna biguanidu) aktywuje kinazę AMPK w hepatocytach, hamuje mitochondrialny kompleks I łańcucha oddechowego i redukuje wątrobową glukoneogenezę oraz poprawia wrażliwość na insulinę bez ryzyka hipoglikemii i bez przyrostu masy ciała. Zasada bezpieczeństwa eGFR: dawka standardowa do eGFR >= 45 ml/min; redukcja do maksymalnie 1000 mg/dobę przy eGFR 30–44 ml/min; BEZWZGLĘDNIE odstawić, gdy eGFR < 30 ml/min ze względu na ryzyko kumulacji i kwasicy mleczanowej (MALA).',
      },
      {
        title: 'Inhibitory SGLT2 (flozyny): rewolucja sercowo-nerkowa',
        text: 'Flozyny (dapagliflozyna, empagliflozyna, kanagliflozyna) wybiórczo blokują nerkowy kotransporter SGLT2 w początkowym odcinku kanalika bliższego, wywołując wydalanie 70–80 g glukozy z moczem na dobę (glukozuria z utratą ok. 300 kcal/d). Powodują spadek ciśnienia tętniczego, masy ciała i kwasu moczowego. Co kluczowe — radykalnie redukują ryzyko hospitalizacji z powodu niewydolności serca (zarówno HFrEF, jak i HFpEF) oraz spowalniają progresję PChN (inicjacja do eGFR >= 20 ml/min/1,73m2 wg KDIGO 2023 / ADA 2026, kontynuacja do dializoterapii), niezależnie od stopnia wyrównania glikemii.',
      },
      {
        title: 'Inkretyny: agoniści receptora GLP-1 i podwójni agoniści GLP-1/GIP',
        text: 'Leki inkretynowe (semaglutyd, dulaglutyd, liraglutyd oraz podwójny agonista GLP-1/GIP tirzepatyd) stymulują wydzielanie insuliny zależnie od glukozy, silnie hamują wydzielanie glukagonu, opóźniają opróżnianie żołądka i nasilają sytość w ośrodkowym układzie nerwowym. Zapewniają spektakularną redukcję masy ciała (do 15–22% przy tirzepatydzie) i chronią przed zawałem, udarem oraz zgonem sercowo-naczyniowym (MACE). Inhibitory DPP-4 (gliptyny) to leki doustne o neutralnym wpływie na masę ciała.',
      },
    ],
    table: {
      headers: ['Grupa leków', 'Mechanizm główny', 'Wpływ na masę ciała', 'Wpływ na serce i nerki'],
      rows: [
        ['Metformina', 'Aktywacja AMPK, spadek glukoneogenezy', 'Neutralny / lekki spadek', 'Bezpieczna sercowo, odstawić przy eGFR < 30'],
        ['Inhibitory SGLT2 (Flozyny)', 'Glukozuria i natriureza przez SGLT2', 'Umiarkowany spadek (2–4 kg)', 'Znakomita redukcja HF i progresji PChN (KDIGO 1A)'],
        ['Agoniści GLP-1 (np. Semaglutyd)', 'Inkretynowy: GLP-1R w mózgu i trzustce', 'Bardzo duży spadek (5–15 kg)', 'Silna redukcja miażdżycy, zawałów i udarów (MACE)'],
        ['Inhibitory DPP-4 (Gliptyny)', 'Hamowanie rozpadu endogennego GLP-1', 'Neutralny', 'Bezpieczne, brak redukcji zdarzeń twardych'],
      ],
    },
    advanced:
      'Zasada „sick day rules” dla flozyn i metforminy: w przypadku ostrej choroby gorączkowej, odwodnienia (biegunka, wymioty) lub przed planową operacją w znieczuleniu ogólnym należy ODSTAWIĆ flozyny na 3 dni przed zabiegiem (profilaktyka euglikemicznej kwasicy ketonowej euDKA) oraz odstawić metforminę na 48h przed podaniem jodowego środka cieniującego (profilaktyka nefropatii kontrastowej i kwasicy MALA).',
    summary:
      'Nowoczesna terapia T2D stawia na flozyny (ochrona przed niewydolnością serca i PChN) oraz agonistów GLP-1 (ochrona przed miażdżycą i redukcja otyłości) jako leki pierwszego wyboru obok metforminy.',
    sourceIds: ['cardiovascular_easd', 'ckd_diabetes', 'ptd_guidelines', 'ada_standards'],
    questions: [
      q('Jaka wartość eGFR stanowi bezwzględną granicę, poniżej której należy natychmiast odstawić metforminę?',
        ['eGFR poniżej 30 ml/min/1,73m2', 'Kumulacja leku poniżej tego progu stwarza śmiertelne ryzyko kwasicy mleczanowej.'],
        ['eGFR poniżej 60 ml/min/1,73m2', 'W przedziale 45–59 ml/min metformina jest w pełni bezpieczna w pełnej dawce.'],
        ['eGFR poniżej 90 ml/min/1,73m2', '90 ml/min to prawidłowa wartość filtracji kłębuszkowej.']),
      q('U pacjenta z cukrzycą typu 2 i rozpoznaną niewydolnością serca ze zredukowaną frakcją wyrzutową (HFrEF EF 32%), lekiem o udowodnionej redukcji hospitalizacji i zgonu jest:',
        ['Inhibitor SGLT2 (np. dapagliflozyna lub empagliflozyna)', 'Flozyny są fundamentem leczenia niewydolności serca zgodnie z wytycznymi ESC i ADA.'],
        ['Pochodna tiazolidynodionu (pioglitazon)', 'Pioglitazon powoduje retencję płynów i jest bezwzględnie przeciwwskazany w niewydolności serca!'],
        ['Pochodna sulfonylomocznika (glimepiryd)', 'Nie wykazuje korzyści hemodynamicznych w niewydolności serca.']),
      q('Dlaczego agoniści receptora GLP-1 (np. semaglutyd) NIE wywołują hipoglikemii w monoterapii?',
        ['Stymulują sekrecję insuliny wyłącznie w sposób glukozozależny (gdy glikemia przekracza normę)', 'Gdy glikemia spada do wartości prawidłowych, działanie pobudzające na komórki beta automatycznie wygasa.'],
        ['Hamują całkowicie rozkład glikogenu w mięśniach', 'Nie mają takiego działania.'],
        ['Zwiększają wchłanianie cukru z jelita grubego', 'GLP-1 spowalnia, a nie przyspiesza opróżnianie żołądka.']),
      q('Przed planową tomografią komputerową z dożylnym kontrastem jodowym u pacjenta leczonego metforminą należy:',
        ['Odstawić metforminę na 48 godzin przed podaniem kontrastu i wznowić po 48h po kontroli kreatyniny', 'Zapobiega to kumulacji metforminy w razie wystąpienia ostrego uszkodzenia nerek po kontraście.'],
        ['Podwoić dawkę metforminy w dniu badania', 'Zwiększenie dawki zwiększyłoby ryzyko kwasicy mleczanowej.'],
        ['Podać dożylnie 100 g glukozy', 'Nie ma uzasadnienia dla podawania glukozy przed kontrastem.']),
      q('Który lek jest podwójnym agonistą receptorów GIP oraz GLP-1 zapewniającym redukcję masy ciała powyżej 20%?',
        ['Tirzepatyd', 'Synergistyczna aktywacja receptorów inkretynowych GIP i GLP-1 wykazuje najsilniejsze działanie metaboliczne.'],
        ['Akarboza', 'Akarboza to słaby inhibitor alfa-glukozydazy jelitowej.'],
        ['Gliklazyd', 'To pochodna sulfonylomocznika sprzyjająca przyrostowi masy ciała.']),
    ],
  },
  {
    id: 'cukrzyca-insulinoterapia-aid',
    title: 'Insulinoterapia i zaawansowane systemy pompowe (AID)',
    subtitle: 'Analogi insuliny, schematy baza-bolus, technologia zamkniętej pętli (Artificial Pancreas)',
    group: 'Farmakoterapia i sytuacje szczególne',
    minutes: 16,
    goals: [
      'Porównasz profile farmakokinetyczne analogów szybkodziałających i ultradługodziałających z insulinami ludzkimi.',
      'Wyjaśnisz zasadę działania zaawansowanych systemów hybrydowej zamkniętej pętli (AID).',
    ],
    sections: [
      {
        title: 'Ewolucja cząsteczki insuliny: od ludzkiej do analogów',
        text: 'Insulina regularna (krótkodziałająca ludzka) tworzy w roztworze stabilne heksamery z cynkiem Zn2+, co opóźnia dysocjację do aktywnych monomerów i wymaga podania 30 min przed posiłkiem. Analogi szybkodziałające (lispro, aspart, glulizyna) dzięki zamianie aminokwasów natychmiast dysocjują do monomerów (podanie tuż przed jedzeniem). Analogi ultradługodziałające (glargina U100/U300, degludec U100/U200) tworzą podskórny mikrodepozyt lub wieloheksamery, zapewniając płaski, bezszczytowy profil działania przez 24–42 godziny.',
      },
      {
        title: 'Złoty standard: intensywna funkcjonalna insulinoterapia (FIT)',
        text: 'FIT naśladuje fizjologię za pomocą dwóch składowych: 1) Insuliny bazowej (stanowiącej zwykle 40–50% dobowego zapotrzebowania TDD), która hamuje wątrobową glukoneogenezę między posiłkami i w nocy; 2) Bolusów posiłkowych (dopasowanych do gramów węglowodanów wg wskaźnika ICR) oraz bolusów korekcyjnych (wg współczynnika wrażliwości ISF). Pozwala to pacjentowi na pełną elastyczność dietetyczną i aktywność fizyczną.',
      },
      {
        title: 'Systemy AID (Automated Insulin Delivery): sztuczna trzustka',
        text: 'Systemy hybrydowej zamkniętej pętli (AID / HCL) integrują trzy komponenty: 1) Ciągły sensor glikemii (CGM); 2) Osobistą pompę insulinową; 3) Algorytm predykcyjny (PID lub MPC — Model Predictive Control). Algorytm co 5 minut prognozuje glikemię na kolejne 30–60 min i automatycznie moduluje podaż bazy oraz podaje mikrobolusy korekcyjne. Pacjent deklaruje jedynie gramy węglowodanów przed posiłkiem (system hybrydowy), co podnosi TIR > 75–85% przy minimalnym ryzyku hipoglikemii.',
      },
    ],
    table: {
      headers: ['Typ analogu insuliny', 'Przedstawiciele', 'Początek działania', 'Szczyt / Czas działania'],
      rows: [
        ['Ultraszybkodziałające (faster/ultra-rapid)', 'Fiasp (aspart z nikotynamidem), Lyumjev', '2–5 minut', 'Szczyt po 30–45 min; czas 3–4 h'],
        ['Szybkodziałające (rapid-acting)', 'Lispro, Aspart, Glulizyna', '10–15 minut', 'Szczyt po 60–90 min; czas 4–5 h'],
        ['Długodziałające bezszczytowe', 'Glargina U100, Detemir', '1–2 godziny', 'Płaski profil; czas 20–24 h'],
        ['Ultradługodziałające', 'Degludec, Glargina U300', '1–2 godziny', 'Całkowicie bezszczytowy; czas > 36–42 h'],
      ],
    },
    advanced:
      'Lipohipertrofia (przerost tłuszczowy) w miejscach wkłuć: wstrzykiwanie insuliny w te same zgrubiałe obszary tkanki podskórnej prowadzi do nieprzewidywalnego wchłaniania (raz opóźnionego wywołującego hiperglikemię, innym razem gwałtownego wywołującego ciężką hipoglikemię). Złotą zasadą profilaktyki jest systematyczna rotacja miejsc wkłuć i jednorazowe używanie igieł do penów.',
    summary:
      'Intensywna insulinoterapia opiera się na bazie (40–50% TDD) i bolusach posiłkowo-korekcyjnych. Systemy zamkniętej pętli AID automatycznie dostosowują dawkę bazy co 5 minut w oparciu o sensor CGM.',
    sourceIds: ['ptd_guidelines', 'ada_standards', 'cgm_consensus'],
    questions: [
      q('Jaki odsetek całkowitego dobowego zapotrzebowania na insulinę (TDD) stanowi zazwyczaj insulina bazowa w schemacie baza-bolus?',
        ['Około 40–50% dobowej dawki', 'Pozostałe 50–60% zapotrzebowania pokrywają bolusy prandialne (posiłkowe) i ewentualne korekty.'],
        ['Ponad 90% dobowej dawki', 'Taki rozkład zablokowałby wątrobę, ale uniemożliwił kontrolę glikemii poposiłkowej.'],
        ['Mniej niż 5% dobowej dawki', 'Brak insuliny bazowej wywołałby gwałtowny wzrost glikemii na czczo i ketozę.']),
      q('Czym charakteryzuje się insulina degludec w porównaniu z klasyczną insuliną NPH?',
        ['Tworzy podskórne rozpuszczalne wieloheksamery, zapewniając idealnie płaski, bezszczytowy profil działania przez ponad 42 godziny', 'Brak szczytu drastycznie redukuje ryzyko nocnych hipoglikemii.'],
        ['Działa natychmiast po 30 sekundach i ulega degradacji po 2 godzinach', 'To cecha analogów ultraszybkich, nie bazowych.'],
        ['Wymaga podawania dożylnego w warunkach OIT', 'Degludec to insulina do podawania podskórnego raz na dobę.']),
      q('Jak działa zaawansowany system hybrydowej zamkniętej pętli (AID)?',
        ['Algorytm matematyczny co kilka minut analizuje trend z sensora CGM i automatycznie modyfikuje przepływ bazy oraz podaje mikrobolusy', 'System działa w pętli sprzężenia zwrotnego, naśladując autonomiczną regulację komórek beta.'],
        ['Wymaga ręcznego mierzenia cukru paskiem co 15 minut przez pacjenta', 'To zaprzeczenie idei automatycznej pętli AID.'],
        ['Wstrzykuje glukagon bezpośrednio do żyły wrotnej', 'Pompy AID podają wyłącznie podskórną insulinę szybkodziałającą.']),
      q('Do czego prowadzi regularne wstrzykiwanie insuliny w to samo zmienione miejsce z lipohipertrofią (przerostem tkanki tłuszczowej)?',
        ['Do skrajnie niestabilnego, nieprzewidywalnego wchłaniania insuliny ze skłonnością do niewyjaśnionych hipo- i hiperglikemii', 'Zbliznowaciała i przerośnięta tkanka ma zaburzone mikrokrążenie i wchłanianie leku.'],
        ['Do natychmiastowej trwałej remisji cukrzycy', 'Lipohipertrofia jest powikłaniem miejscowym pogarszającym kontrolę cukrzycy.'],
        ['Do zniszczenia kości udowej', 'Proces dotyczy wyłącznie tkanki tłuszczowej podskórnej.']),
      q('Dlaczego analogi szybkodziałające (lispro, aspart, glulizyna) wchłaniają się szybciej niż zwykła insulina ludzka?',
        ['Modyfikacje łańcucha B osłabiają asocjację cząsteczek, przez co heksamery natychmiast po wstrzyknięciu rozpadają się na monomery', 'Monomery błyskawicznie przenikają przez ścianę naczyń włosowatych do krążenia.'],
        ['Są podawane wyłącznie w połączeniu z adrenaliną', 'Adrenalina skurczyłaby naczynia i opóźniła wchłanianie.'],
        ['Są rozpuszczane w 100% alkoholu etylowym', 'Roztwory insuliny są wodne i izotoniczne.']),
    ],
  },
  {
    id: 'cukrzyca-ciaza',
    title: 'Cukrzyca w ciąży: GDM i cukrzyca przedciążowa (PGDM)',
    subtitle: 'Kryteria rozpoznania GDM, rygorystyczne cele glikemii i bezpieczeństwo płodu',
    group: 'Farmakoterapia i sytuacje szczególne',
    minutes: 16,
    goals: [
      'Wskaż kryteria rozpoznania cukrzycy ciążowej (GDM) w 24.–28. tygodniu wg PTD/FIGO.',
      'Sformułujesz rygorystyczne cele wyrównania glikemii w ciąży i zasady farmakoterapii.',
    ],
    sections: [
      {
        title: 'Fizjologia ciąży: laktogen łożyskowy i insulinooporność',
        text: 'W drugiej połowie ciąży łożysko wydziela duże ilości hormonów o działaniu diabetogennym: laktogen łożyskowy (hPL), progesteron, kortyzol, estrogeny i prolaktynę. Wywołują one fizjologiczną insulinooporność obwodową, która umożliwia stały transport glukozy przez łożysko do płodu. Jeśli komórki beta trzustki matki nie są w stanie zwiększyć wydzielania insuliny 2–3-krotnie, rozwija się cukrzyca ciążowa (GDM).',
      },
      {
        title: 'Diagnostyka GDM: test OGTT w 24.–28. tygodniu',
        text: 'Na początku ciąży (I wizyta) oznacza się glikemię na czczo. W 24.–28. tygodniu ciąży u każdej kobiety bez wcześniej rozpoznanej cukrzycy wykonuje się standardowy doustny test tolerancji 75 g glukozy (OGTT). Do rozpoznania GDM wystarczy spełnienie CHOCIAŻ JEDNEGO z kryteriów: 1) Glikemia na czczo: 92–125 mg/dl (5,1–6,9 mmol/l); 2) Glikemia w 60. minucie: >= 180 mg/dl (10,0 mmol/l); 3) Glikemia w 120. minucie: 153–199 mg/dl (8,5–11,0 mmol/l). Glikemia na czczo >= 126 mg/dl oznacza jawną cukrzycę w ciąży.',
      },
      {
        title: 'Rygorystyczne cele i leczenie z wyboru',
        text: 'Hiperglikemia matki wywołuje hiperglikemię płodu i hiperinsulinizm płodowy, skutkując makrosomią (masa > 4000 g), dystocją barkową, pourodzeniową hipoglikemią noworodka i niewydolnością oddechową (insulina hamuje syntezę surfaktantu!). Cele glikemii w ciąży są bardzo surowe: na czczo i przed posiłkami 70–90 mg/dl (3,9–5,0 mmol/l), 1h po posiłku < 140 mg/dl (< 7,8 mmol/l). Leczeniem z wyboru przy braku wyrównania dietą jest wyłącznie insulinoterapia (analogi: lispro, aspart, detemir). Większość leków doustnych jest przeciwwskazana.',
      },
    ],
    table: {
      headers: ['Punkt pomiaru w teście OGTT (75g)', 'Wartość progowa rozpoznania GDM', 'Rygorystyczny cel w trakcie ciąży'],
      rows: [
        ['Na czczo', '92–125 mg/dl (5,1–6,9 mmol/l)', '70–90 mg/dl (3,9–5,0 mmol/l)'],
        ['Po 1 godzinie (60 min)', '>= 180 mg/dl (>= 10,0 mmol/l)', '< 140 mg/dl (< 7,8 mmol/l)'],
        ['Po 2 godzinach (120 min)', '153–199 mg/dl (8,5–11,0 mmol/l)', '< 120 mg/dl (< 6,7 mmol/l)'],
      ],
    },
    advanced:
      'Postępowanie poporodowe po GDM: bezpośrednio po urodzeniu łożyska gwałtownie spada stężenie hPL i insulinooporność natychmiast ustępuje — u większości kobiet można odstawić insulinę w 1. dobie po porodzie. Kobiety po przebytej GDM mają jednak 7-krotnie wyższe ryzyko rozwoju cukrzycy typu 2 w ciągu kolejnych 10 lat — bezwzględnie wymagają wykonania kontrolnego testu OGTT 6–12 tygodni po porodzie!',
    summary:
      'GDM rozpoznaje się w teście OGTT przy glikemii na czczo >=92 mg/dl, w 60 min >=180 mg/dl lub w 120 min >=153 mg/dl (wystarczy 1 nieprawidłowość). Leczeniem z wyboru jest dieta, a w razie nieskuteczności — insulina.',
    sourceIds: ['gdm_guidelines', 'ptd_guidelines', 'ada_standards'],
    questions: [
      q('Ile nieprawidłowych punktów w teście OGTT (75g) w 24.–28. tyg. ciąży wystarcza do rozpoznania cukrzycy ciążowej (GDM)?',
        ['Wystarczy dokładnie jeden nieprawidłowy wynik z trzech oznaczanych punktów', 'Zgodnie z kryteriami IADPSG/WHO/PTD pojedyncza wartość przekraczająca próg definiuje GDM.'],
        ['Wszystkie trzy punkty muszą być jednocześnie nieprawidłowe', 'Wymóg trzech punktów przeoczyłby większość kobiet zagrożonych makrosomią płodu.'],
        ['Żaden — GDM rozpoznaje się wyłącznie z badania moczu', 'Badanie moczu na obecność glukozy nie ma wartości diagnostycznej w GDM z powodu obniżonego progu nerkowego w ciąży.']),
      q('Jaki jest docelowy poziom glikemii na czczo u kobiety ciężarnej z cukrzycą?',
        ['70–90 mg/dl (3,9–5,0 mmol/l)', 'Utrzymanie glikemii na czczo < 90 mg/dl zapobiega nadmiernej stymulacji trzustki płodu.'],
        ['100–125 mg/dl', 'To zakres nieprawidłowy, który u ciężarnej wywołałby hiperinsulinizm płodu i makrosomię.'],
        ['Poniżej 50 mg/dl', 'Stężenie < 50 mg/dl to hipoglikemia groźna dla matki.']),
      q('Dlaczego hiperglikemia u matki może doprowadzić do zespołu zaburzeń oddychania (RDS) u noworodka?',
        ['Wysokie stężenie insuliny u płodu hamuje syntezę surfaktantu w pneumocytach typu II', 'Płód z makrosomią rodzi się z niedojrzałymi płucami mimo donoszonego wieku ciążowego.'],
        ['Glukoza niszczy pęcherzyki płucne na drodze apoptozy', 'To zaburzenie biochemiczne syntezy dipalmitoilofosfatydylocholiny, nie apoptoza pęcherzyków.'],
        ['Insulina matki przenika przez łożysko i niszczy tchawicę', 'Insulina matczyna nie przechodzi przez barierę łożyskową (przechodzi tylko glukoza).']),
      q('Jakie jest leczenie farmakologiczne z wyboru w cukrzycy ciążowej, gdy dieta nie zapewnia celów glikemii?',
        ['Insulinoterapia podskórna (analogi szybkodziałające lispro/aspart i bazowe detemir/glargina)', 'Insulina nie przechodzi przez łożysko i jest najbezpieczniejszym lekiem w ciąży.'],
        ['Pochodne sulfonylomocznika w dużych dawkach', 'Przenikają przez łożysko i wywołują ciężką, przedłużoną hipoglikemię u noworodka.'],
        ['Inhibitory SGLT2 (flozyny)', 'Są bezwzględnie przeciwwskazane w ciąży ze względu na potencjalną nefrotoksyczność dla płodu.']),
      q('Kiedy po porodzie należy wykonać kontrolny test OGTT u kobiety, która przebyła cukrzycę ciążową?',
        ['Po 6–12 tygodniach od porodu', 'Pozwala ocenić, czy doszło do pełnej normalizacji tolerancji glukozy, czy też przetrwał stan przedcukrzycowy lub T2D.'],
        ['Dopiero po 10 latach', 'To zbyt późno na wczesną interwencję dietetyczną i profilaktykę T2D.'],
        ['W pierwszej dobie po porodzie przed wypisem ze szpitala', 'Bezpośrednio po porodzie organizm znajduje się w stanie ostrego stresu połogowego i wynik byłby niemiarodajny.']),
    ],
  },
];
