import type {DraftLesson, DraftQuestion, Source} from './course-types.ts';

export const gahtSources:Record<string,Source> = {
  'ucsf-fem-2016':{id:'ucsf-fem-2016',title:'UCSF — Overview of feminizing hormone therapy (strona oznaczona jako oczekująca aktualizacji)',year:'2016',kind:'Przewodnik kliniczny — materiał uzupełniający',url:'https://transcare.ucsf.edu/guidelines/feminizing-hormone-therapy'},
  'ucsf-masc-2016':{id:'ucsf-masc-2016',title:'UCSF — Overview of masculinizing hormone therapy',year:'2016',kind:'Przewodnik kliniczny — materiał uzupełniający',url:'https://transcare.ucsf.edu/guidelines/masculinizing-therapy'},
  'cdc-testosterone-2024':{id:'cdc-testosterone-2024',title:'CDC — Testosterone Use and Risk for Pregnancy',year:'2024',kind:'Rekomendacje antykoncepcji',url:'https://www.cdc.gov/contraception/hcp/usspr/testosterone-pregnancy-risk.html'},
  'ema-cpa-2020':{id:'ema-cpa-2020',title:'EMA — Cyproterone: restrictions due to meningioma risk',year:'2020',kind:'Komunikat bezpieczeństwa',url:'https://www.ema.europa.eu/en/medicines/human/referrals/cyproterone-containing-medicinal-products'},
  'estradiol-patch-pk-2025':{id:'estradiol-patch-pk-2025',title:'DailyMed — Estradiol transdermal system: farmakokinetyka i zmienność międzyosobnicza',year:'2025',kind:'Etykieta produktu / dane PK',url:'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c714974b-766f-42f2-a846-b0c1f5a60560'},
  'testosterone-gel-pk-2025':{id:'testosterone-gel-pk-2025',title:'DailyMed — Testosterone gel 1.62%: profil stężenie–czas',year:'2025',kind:'Etykieta produktu / dane PK',url:'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=10dab294-6a43-4bb3-9d91-2d200c624ffb'},
  'gaht-levels-2021':{id:'gaht-levels-2021',title:'Serum Hormone Concentrations in Transgender Individuals Receiving GAHT',year:'2021',kind:'Kohorta retrospektywna — zależność dawka–stężenie',url:'https://doi.org/10.1016/j.eprac.2020.10.001'},
};
// Each concept has an authored retrieval question and two plausible misconceptions.
type Concept = [id:string,heading:string,text:string,prompt:string,correct:string,wrong1:string,why1:string,wrong2:string,why2:string];
type Unit = {id:string;title:string;concepts:Concept[];advanced:string;sources:string[]};
const units:Unit[] = [
{id:'gaht-anatomia-cele',title:'GAHT 1 · Anatomia, cele i oś HPG',sources:['endo-trans-2017','ucsf-fem-2016','ucsf-masc-2016'],advanced:'Cele uzgadnia się z osobą korzystającą z terapii. Tożsamość płciowa nie określa automatycznie anatomii, pożądanych efektów ani docelowego schematu. Atlas dotyczy dorosłych; opieka nad młodzieżą wymaga odrębnej ścieżki.',concepts:[
['anatomy','Anatomia i cel to osobne informacje','Przed interpretacją badań określ obecność i czynność gonad, przebyte operacje, zachowane narządy oraz leki. Sama etykieta płci nie wystarcza do modelowania osi.','Co najlepiej opisuje stan wyjściowy do interpretacji GAHT?','Anatomia, czynność gonad, leki i indywidualne cele','Wyłącznie płeć w dokumentacji','Dokumentacja nie opisuje gonad ani leczenia.','Wyłącznie stężenie testosteronu','Jeden wynik nie ujawnia anatomii ani mechanizmu.'],
['uterus','Histerektomia nie jest gonadektomią','Macica nie jest głównym źródłem steroidów płciowych. Po histerektomii zachowane jajniki mogą nadal pracować; nie można już wnioskować o cyklu z miesiączki.','Po usunięciu macicy z pozostawieniem jajników należy założyć:','Czynność jajników może pozostać zachowana','Całkowity brak endogennego estradiolu','Estradiol może nadal powstawać w jajnikach.','Brak jakichkolwiek wahań hormonalnych','Brak krwawienia nie wyklucza czynności cyklicznej.'],
['feedback','Sprzężenie zwrotne','Steroidy płciowe oddziałują na podwzgórze i przysadkę. Egzogenne hormony również uczestniczą w sprzężeniu; nie muszą pochodzić z gonad.','Czy estradiol podawany po gonadektomii może hamować LH?','Tak, działa na zachowane piętra osi','Nie, sprzężenie wymaga jajników','Receptory w podwzgórzu i przysadce pozostają obecne.','Nie, egzogenny hormon działa tylko w piersiach','Efekty estradiolu obejmują wiele tkanek.'],
['inhibin','FSH i LH nie są tym samym sygnałem','Inhibiny z gonad regulują przede wszystkim FSH. Utrata gonad zmienia zarówno steroidowe, jak i peptydowe sprzężenia.','Który sygnał jest szczególnie hamowany przez inhibinę?','FSH','LH w identycznym stopniu jak FSH','Inhibina działa preferencyjnie na FSH.','Wyłącznie GnRH','Istotnym miejscem działania inhibiny jest przysadka.'],
['goals','Cele i ograniczenia efektów','Efekty terapii są indywidualne i rozwijają się w różnym czasie. Nie można zagwarantować wybranej konfiguracji wyglądu przez ustawienie jednego stężenia.','Jak ustalać oczekiwane efekty?','Omówić cele, zmienność i odwracalność zmian','Przypisać stały efekt do każdej wartości E2','Stężenie nie przewiduje dokładnie efektów tkankowych.','Zakładać identyczne cele wszystkich osób','Cele i preferencje są indywidualne.'],
]},
{id:'gaht-steroidogeneza',title:'GAHT 2 · Od steroidu do receptora',sources:['endo-trans-2017','ucsf-fem-2016','ucsf-masc-2016'],advanced:'Wynik całkowity, frakcja wolna, lokalna konwersja i aktywacja receptora opisują różne zjawiska. Kalkulacja wolnego T wymaga poprawnych jednostek oraz znajomości ograniczeń oznaczeń i modelu wiązania.',concepts:[
['aromatase','Aromataza','Aromataza przekształca androgeny w estrogeny. Konwersja egzogennego testosteronu do estradiolu zachodzi również poza gonadami i nie znika po usunięciu jajników.','Czy po usunięciu jajników podczas terapii T może powstawać E2?','Tak, przez aromatyzację obwodową','Nie, potrzebne są komórki jajnikowe','Aromataza jest obecna także w tkankach obwodowych.','Tylko po dodaniu progesteronu','Progesteron nie jest warunkiem aromatyzacji T.'],
['dht','5α-reduktaza','5α-reduktaza przekształca testosteron w DHT. Jej inhibitor ogranicza ten szlak, ale nie blokuje bezpośrednio AR ani syntezy całego testosteronu.','Który szlak hamuje finasteryd?','T → DHT','T → E2','Ten szlak zależy od aromatazy.','Wiązanie każdego androgenu z AR','Finasteryd jest inhibitorem enzymu, nie antagonistą AR.'],
['ar','Receptor androgenowy','Antagonizm AR może ograniczać efekt androgenowy bez proporcjonalnego obniżenia stężenia testosteronu. Nie przeliczamy blokady receptora na procent supresji osi.','Co oznacza blokada AR przy utrzymującym się T?','Działanie tkankowe może być ograniczone mimo obecności T','Lek na pewno nie działa','Stężenie nie mierzy bezpośrednio blokady receptora.','T musi natychmiast stać się niewykrywalny','Antagonizm receptora nie oznacza usunięcia hormonu.'],
['shbg','SHBG i albumina','Białka wiążą hormony. Doustny estrogen może zwiększać SHBG przez wpływ na wątrobę; dlatego T całkowity i jego frakcja wolna nie muszą zmieniać się równolegle.','Przy zmianie SHBG należy:','Interpretować T całkowity w kontekście wiązania i objawów','Zakładać identyczny procent zmiany wolnego T','Zależność nie jest prostą proporcją.','Uznawać każde wysokie SHBG za guz','SHBG zmienia się także pod wpływem leków i innych stanów.'],
['adrenal','Źródła pozagonadalne','Prekursory nadnerczowe i ich obwodowe przemiany pozostają po gonadektomii. Nie oznacza to jednak automatycznie wystarczającej substytucji dla zdrowia kości.','Brak gonad oznacza:','Brak produkcji gonadalnej, ale nie wszystkich steroidów','Brak wszystkich androgenów w organizmie','Pozostają prekursory nadnerczowe i konwersja.','Pewną wystarczalność hormonów nadnerczowych','Adekwatność substytucji wymaga oceny klinicznej.'],
]},
{id:'gonady-trans-feminizujaca',title:'GAHT 3 · Terapia feminizująca i mechanizmy blokady',sources:['endo-trans-2017','ucsf-fem-2016','ema-cpa-2020','estradiol-patch-pk-2025','gaht-levels-2021'],advanced:'Zakres E2 100–200 pg/ml i T <50 ng/dl z wytycznych Endocrine Society jest punktem odniesienia dla typowych celów terapii, a nie obietnicą efektu ani automatycznym poleceniem zmiany dawki. Uwzględniaj czas pobrania, metodę, objawy i cele. W modelu ilościowym mediana nie jest oczekiwanym wynikiem konkretnej osoby: pasma pokazują zmienność populacyjną, a pomiar może skalibrować tylko ten analit i ten schemat.',concepts:[
['estradiol','17β-estradiol','Estradiol działa na receptory estrogenowe i uczestniczy w hamowaniu osi HPG. Wybór drogi podania uwzględnia odpowiedź, preferencje i ryzyko; etynyloestradiolu nie zaleca się w GAHT.','Który estrogen jest preferowany w GAHT?','17β-estradiol w odpowiednio dobranej postaci','Etynyloestradiol dla silniejszego działania','Nie zaleca się go ze względu na profil ryzyka.','Estrogeny sprzężone jako łatwiejsze do monitorowania','Standardowy pomiar E2 nie opisuje dobrze ich ekspozycji.'],
['spiro','Spironolakton','Spironolakton działa antyandrogenowo, w tym na receptor AR, oraz oszczędza potas. Należy uwzględniać funkcję nerek, potas i leki zwiększające ryzyko hiperkaliemii.','Jakie badania są szczególnie istotne przy spironolaktonie?','Potas i funkcja nerek','Wyłącznie prolaktyna','Nie ocenia ryzyka hiperkaliemii.','Wyłącznie estradiol','Prawidłowy E2 nie wyklucza zaburzeń elektrolitowych.'],
['cpa','CPA','CPA działa antyandrogenowo i antygonadotropowo. Ryzyko oponiaka zależy m.in. od ekspozycji skumulowanej. Prolaktyna ocenia hiperprolaktynemię, a nie przesiewowo oponiaka.','Czy prawidłowa prolaktyna wyklucza ryzyko oponiaka przy CPA?','Nie, to odrębne zagadnienia','Tak, oponiak zawsze wydziela prolaktynę','Oponiak nie jest prolactinoma.','Tak, jeśli E2 mieści się w celu','E2 nie wyklucza ryzyka związanego z CPA.'],
['gnrh','Agonista i antagonista GnRH','Agonista może początkowo pobudzać oś, a przewlekle prowadzi do desensytyzacji. Antagonista blokuje receptor bez tego początkowego pobudzenia.','Który efekt może wystąpić na początku podawania agonisty GnRH?','Przejściowy flare','Natychmiastowa utrata anatomiczna gonad','To hamowanie farmakologiczne, a nie zabieg.','Identyczny przebieg jak po antagoniście','Mechanizm i początek działania się różnią.'],
['vte','Ryzyko i droga podania','Droga przezskórna omija efekt pierwszego przejścia i jest rozważana szczególnie przy zwiększonym ryzyku zakrzepowym. Nie gwarantuje braku VTE.','Jak opisać przezskórny E2?','Może być korzystniejszy przy ryzyku VTE, bez gwarancji zerowego ryzyka','Eliminuje potrzebę oceny czynników ryzyka','Pozostałe czynniki nadal mają znaczenie.','Ma identyczny wpływ wątrobowy jak doustny','Drogi podania różnią się efektem pierwszego przejścia.'],
]},
{id:'gonady-trans-maskulinizujaca',title:'GAHT 4 · Terapia maskulinizująca i odpowiedź tkankowa',sources:['endo-trans-2017','ucsf-masc-2016','cdc-testosterone-2024','testosterone-gel-pk-2025','gaht-levels-2021'],advanced:'Hct >54% wymaga oceny i interwencji według kontekstu klinicznego. Nie oznacza pewnego udaru ani automatycznego upustu u każdego pacjenta. Oceń poziom T, szczyty ekspozycji, bezdech senny, palenie, odwodnienie i inne przyczyny. Syntetyczny Hct w pracowni pokazuje kierunek i niepewność populacyjną; decyzję opiera się na rzeczywistej morfologii.',concepts:[
['sampling','Wynik a czas pobrania','Dla enantanu/cypionianu Endocrine Society podaje orientacyjny cel 400–700 ng/dl przy pomiarze między iniekcjami. Dla undekanianu pobranie następuje przed kolejną iniekcją.','Co jest konieczne przy interpretacji wyniku T?','Preparat i czas pobrania względem podania','Porównanie każdego wyniku do 400–700 bez kontekstu','Ten cel dotyczy określonego schematu pomiaru.','Wyłącznie czas od rozpoczęcia tranzycji','Nie określa fazy farmakokinetycznej.'],
['hct','Hematokryt','Testosteron może nasilać erytropoezę. Interpretuj rzeczywistą morfologię, odpowiedni zakres i inne przyczyny erytrocytozy. Hct nie da się obliczyć z dawki.','Co zrobić przy istotnym wzroście Hct?','Ocenić ekspozycję na T i inne przyczyny oraz dobrać interwencję','Zawsze wykonać upust bez dalszej oceny','Postępowanie wymaga kontekstu i diagnostyki.','Przewidzieć ryzyko udaru z jednej dawki T','Nie istnieje tu użyty zwalidowany przelicznik.'],
['voice','Odwracalność','Obniżenie głosu i rozrost łechtaczki mogą być trwałe. Zmiany skóry, masy mięśniowej i dystrybucji tłuszczu zależą od dalszej ekspozycji i innych czynników.','Który efekt może pozostać po odstawieniu T?','Obniżenie głosu','Zawsze całkowite zahamowanie jajników','Powrót czynności jest możliwy, choć indywidualny.','Każdy efekt ustępuje w kilka tygodni','Część zmian strukturalnych jest trwała.'],
['bleeding','Nawrót krwawień','Krwawienie wymaga różnicowania: ekspozycja na T, ciąża jeśli możliwa, atrofia, infekcje oraz patologia narządowa. Nie przypisuj go automatycznie aromatyzacji.','Co zrobić przy nowych plamieniach po okresie amenorrhei?','Przeprowadzić ocenę zależną od anatomii i ryzyka ciąży','Rozpoznać nadmiar E2 bez badań','Sam objaw nie określa mechanizmu.','Zwiększyć T bez ustalenia przyczyny','Może to opóźnić rozpoznanie innego problemu.'],
['local','Objawy miejscowe','Przy objawach atrofii urogenitalnej rozważ leczenie miejscowe po ocenie. Miejscowe estrogeny mają zwykle niewielką ekspozycję ogólną; nie utożsamiaj ich z pełną terapią feminizującą.','Co warto rozważyć przy potwierdzonej atrofii?','Leczenie miejscowe dostosowane do objawów i preferencji','Zawsze całkowite odstawienie T','Nie jest to automatycznie konieczne.','Podwyższenie T jako leczenie atrofii','Nie rozwiązuje bezpośrednio niedoborowego stanu nabłonka.'],
]},
{id:'gaht-gonadektomia',title:'GAHT 5 · Gonady obecne, zahamowane i usunięte',sources:['endo-trans-2017','ucsf-fem-2016','ucsf-masc-2016'],advanced:'Po gonadektomii adekwatność substytucji ocenia się przez objawy, ekspozycję, wyniki i zdrowie kości. Nie stosuj automatycznej redukcji dawki ani automatycznego dodania drugiego steroidu. LH/FSH mogą dostarczać kontekstu, lecz nie są samodzielnym miernikiem wszystkich efektów terapii.',concepts:[
['removed','Brak tkanki','Po obustronnej gonadektomii nie ma gonadalnego źródła steroidów ani gamet. Sama stymulacja gonadotropinami nie przywróci funkcji usuniętej tkanki.','Czy wysokie LH odtworzy T po obustronnej orchiektomii?','Nie, brak tkanki docelowej','Tak, jeśli LH wzrośnie wystarczająco','Wysoki sygnał nie zastępuje narządu.','Tak, przez pobudzenie jajników','Orchiektomia nie tworzy jajników.'],
['blockade','Ponowna ocena blokady','Po usunięciu jąder zwykle znika potrzeba hamowania ich produkcji T. Pozostałe wskazania do leku ocenia się osobno, a nie kontynuuje automatycznie.', 'Po orchiektomii co należy ponownie ocenić?','Potrzebę antyandrogenu i adekwatność substytucji','Potrzebę rutynowego zwiększenia blokady LH','Nie ma już gonadalnego źródła do zahamowania.','Konieczność odstawienia wszystkich steroidów','Może to prowadzić do niedoboru hormonów.'],
['bones','Kości','Długotrwały niedobór steroidów płciowych może szkodzić kościom. U osoby bez gonad przerwa w substytucji wymaga szczególnej uwagi; nadnercza nie gwarantują ochrony.','Co jest ważne przy przerwie w terapii po gonadektomii?','Objawy niedoboru i zdrowie kości','Założenie pełnej kompensacji przez nadnercza','Kompensacja nie jest gwarantowana.','Ocena wyłącznie potasu','Nie opisuje adekwatności steroidów płciowych.'],
['suppressed','Zahamowanie nie jest usunięciem','Gonady pod wpływem leków nadal istnieją. Czynność może wracać po zmianie leczenia, zależnie od rezerwy i historii terapii.','Czy zahamowane jajniki oznaczają trwałą niepłodność?','Nie, nie można tego wywnioskować z samej supresji','Tak, brak krwawienia to dowód','Amenorrhea nie dowodzi utraty rezerwy.','Tak, niski LH zawsze oznacza brak oocytów','LH nie mierzy liczby oocytów.'],
['ovaries','Testosteron po usunięciu jajników','Egzogenny testosteron może nadal działać i ulegać aromatyzacji bez jajników. Adekwatność leczenia nie wynika z samego faktu operacji.','Czy testosteron przestaje działać po usunięciu jajników?','Nie, receptory i przemiany obwodowe pozostają','Tak, jajniki aktywują każdą dawkę','T działa na receptory w tkankach.','Tak, bez jajników nie powstanie żaden E2','Pozostaje aromatyzacja obwodowa.'],
]},
{id:'gaht-monitorowanie',title:'GAHT 6 · Pobranie krwi, monitorowanie i niepewność',sources:['endo-trans-2017','ucsf-fem-2016','ucsf-masc-2016','estradiol-patch-pk-2025','testosterone-gel-pk-2025'],advanced:'W pierwszym roku zwykle planuje się częstsze kontrole, a po stabilizacji rzadsze, zgodnie z wytycznymi i sytuacją. Zapisz nazwę preparatu, drogę, ostatnie podanie i godzinę pobrania. Ciemne pasmo symulatora oznacza środkowe 50%, jasne 90%, a nie zakres terapeutyczny. Przy niespójności klinicznej rozważ metodę oznaczenia, adherencję, interferencję i zgodność populacji źródłowej.',concepts:[
['peak','Szczyt i dołek','Iniekcje mogą powodować wahania stężeń. Wynik pobrany tuż po podaniu i przed kolejną dawką opisuje różne punkty profilu.','Dwa różne wyniki po tej samej dawce wymagają najpierw sprawdzenia:','Czasu pobrania względem podania','Wyłącznie zmiany masy ciała','Faza profilu może wyjaśniać różnicę.','Zawsze błędu pacjenta','Różnica nie dowodzi błędu stosowania.'],
['route','Droga i jednostki','Miligram podany doustnie, przez skórę lub w iniekcji nie daje identycznej ekspozycji. Plastry mogą opisywać uwalnianie w mikrogramach na dobę.','Czy można bezpośrednio porównać mg tabletki i mg żelu?','Nie, trzeba uwzględnić postać i biodostępność','Tak, masa substancji wystarcza','Wchłanianie i metabolizm różnią się.','Tak, jeśli podaje się raz dziennie','Częstość nie wyrównuje biodostępności.'],
['units','Przeliczanie jednostek','Dla T: ng/dl ×0,0347 ≈ nmol/l. Dla E2: pg/ml ×3,67 ≈ pmol/l. Współczynnik zależy od masy cząsteczkowej hormonu.','E2 100 pg/ml odpowiada w przybliżeniu:','367 pmol/l','3,47 nmol/l','To pomieszanie współczynników i jednostek.','100 pmol/l','Jednostek masowych i molowych nie zamienia się 1:1.'],
['context','Zakres i cel','Zakres referencyjny laboratorium i cel monitorowania terapii to różne pojęcia. Dobierz interpretację do hormonu, leczenia i sytuacji klinicznej.','Czy flaga laboratoryjna poza zakresem zawsze oznacza błąd leczenia?','Nie, sprawdź zastosowany zakres i kontekst','Tak, niezależnie od rejestracji i terapii','Laboratorium może użyć nieadekwatnego zakresu.','Nie, wszystkie flagi należy ignorować','Nieprawidłowość wymaga interpretacji, nie pominięcia.'],
['uncertainty','Wynik a efekt','Nie ma wiarygodnej reguły przewidującej rozmiar piersi czy barwę głosu z pojedynczego E2 lub T. Oceniaj także cele, efekty i działania niepożądane.','Czy wyższy E2 gwarantuje większą feminizację?','Nie, nie ma takiej prostej zależności','Tak, efekt rośnie liniowo','Tkanki nie odpowiadają według takiego przelicznika.','Tak, jeśli T jest niewykrywalny','Pełna supresja nie tworzy liniowej zależności.'],
]},
{id:'gaht-plodnosc',title:'GAHT 7 · Płodność i opieka nad zachowanymi narządami',sources:['cdc-testosterone-2024','endo-trans-2017','ucsf-masc-2016'],advanced:'Porozmawiaj o zabezpieczeniu gamet przed leczeniem mogącym wpłynąć na płodność. Powrót płodności po odstawieniu GAHT jest możliwy, ale indywidualny. Screening dobieraj do zachowanych narządów, wieku i ryzyka, nie wyłącznie danych rejestracyjnych.',concepts:[
['contraception','Testosteron nie jest antykoncepcją','Owulacja i ciąża mogą wystąpić podczas terapii testosteronem mimo braku miesiączki. Dobór antykoncepcji zależy od potrzeb i przeciwwskazań.','Osoba z macicą i jajnikami przyjmująca T bez miesiączki:','Może nadal potrzebować antykoncepcji','Ma potwierdzoną bezpłodność','Brak miesiączki nie dowodzi braku owulacji.','Nie może zajść w ciążę przy T w celu','Cel T nie gwarantuje antykoncepcji.'],
['gametes','Zabezpieczenie płodności','Omów opcje zachowania gamet przed terapią i operacją. Obustronne usunięcie gonad eliminuje późniejsze uzyskanie gamet z tych narządów.','Kiedy najlepiej rozpocząć rozmowę o zabezpieczeniu gamet?','Przed leczeniem i gonadektomią','Dopiero po obustronnym usunięciu gonad','Może być już za późno na pobranie gamet.','Dopiero gdy pojawi się amenorrhea','Warto omówić opcje wcześniej.'],
['pregnancy','Ocena ryzyka ciąży','Nowe krwawienie, ból lub inne objawy wymagają oceny zgodnej z anatomią i możliwością ciąży. Sam fakt GAHT nie wyklucza testu ciążowego.','Czy GAHT wyklucza potrzebę testu ciążowego?','Nie, decyzja zależy od anatomii i ekspozycji','Tak, przy regularnych iniekcjach T','T nie jest niezawodną antykoncepcją.','Tak, po roku bez krwawień','Długa amenorrhea nie wyklucza owulacji.'],
['organs','Opieka zależna od narządów','Zachowana szyjka, piersi lub prostata mogą wymagać odpowiedniego screeningu. Zabieg i terapia nie zawsze usuwają narząd ani jego ryzyko chorób.','Na czym opierać plan screeningu?','Zachowane narządy, wiek, ryzyko i wytyczne','Wyłącznie oznaczenie płci w dokumentacji','Może pomijać obecne narządy.','Wyłącznie stosowany steroid','Nie opisuje pełnego ryzyka.'],
['recovery','Powrót płodności','Po zmianie lub odstawieniu hormonów czynność gonad może wracać. Nie można przewidzieć terminu z jednego wyniku ani obiecać odzyskania płodności.','Jak rozmawiać o powrocie płodności?','Omówić możliwość i niepewność oraz potrzebę oceny','Zagwarantować powrót w miesiąc','Tempo i zakres są indywidualne.','Wykluczyć powrót po każdej GAHT','To nieuzasadnione uogólnienie.'],
]},
{id:'gaht-decyzje',title:'GAHT 8 · Decyzje złożone i granice wiedzy',sources:['endo-trans-2017','ucsf-fem-2016','ucsf-masc-2016','ema-cpa-2020'],advanced:'Oddziel wynik pomiaru, wniosek kliniczny i preferencję. Jeśli dane nie rozstrzygają problemu, nazwij brakującą informację. Nie przenoś automatycznie wyników badań menopauzalnych na każdą populację korzystającą z GAHT.',concepts:[
['progesterone','Progesteron: osobne pytanie','Nie należy obiecywać większego rozwoju piersi po progesteronie. Dowody dotyczące korzyści i ryzyka są ograniczone; nie jest to automatyczny element każdej GAHT.','Jak przedstawić dodanie progesteronu w terapii feminizującej?','Jako decyzję z omówieniem ograniczeń dowodów','Jako gwarancję większego rozwoju piersi','Nie można takiej korzyści obiecać.','Jako obowiązkowy składnik bez macicy','Nie wynika to z potrzeby ochrony endometrium.'],
['prolactin','Hiperprolaktynemia','Podwyższona PRL wymaga kontekstu: objawy, leki, warunki pobrania i inne przyczyny. Jeden wynik nie rozpoznaje oponiaka ani automatycznie guza przysadki.','PRL podwyższona podczas CPA wymaga:','Oceny leków, objawów i potwierdzenia zgodnie z kontekstem','Rozpoznania oponiaka z wyniku PRL','PRL nie jest jego markerem.','Pominięcia wyniku jako zawsze nieistotnego','Odchylenie wymaga interpretacji.'],
['hct-decision','Erytrocytoza: decyzja','Przy wysokim Hct sprawdź szczyty T i inne przyczyny. Zmiana częstości z odpowiednią zmianą dawki jednostkowej lub drogi podania może ograniczać wahania; nie zwiększaj łącznej ekspozycji przypadkiem.','Przy zmianie iniekcji na częstsze należy:','Uwzględnić także dawkę jednostkową i ekspozycję łączną','Zachować tę samą dawkę pojedynczą niezależnie od interwału','Może to zwiększyć całkowitą ekspozycję.','Wydłużyć interwał jako zawsze najlepszą metodę','Nie jest to uniwersalna odpowiedź na wahania.'],
['nonbinary','Indywidualne cele','Osoby niebinarne mogą mieć zróżnicowane cele. Nie można precyzyjnie oddzielić wszystkich efektów jednego hormonu; omów również niepożądane i trwałe zmiany.','Przy częściowej maskulinizacji należy:','Omówić możliwe efekty i ograniczenia ich selekcji','Zagwarantować brak zmiany głosu przy małej dawce','Niska ekspozycja nie gwarantuje selektywności.','Zakładać brak potrzeby monitorowania','Monitorowanie nadal zależy od stosowanych leków.'],
['reasoning','Rozumowanie zamiast automatu','Bezpieczna interpretacja łączy anatomię, leki, czas, objawy, wyniki i preferencje. Atlas pokazuje mechanizm, a nie zastępuje tej oceny.','Co zrobić, gdy wynik nie pasuje do scenariusza?','Sprawdzić założenia, pomiar i brakujące dane','Zawsze zwiększyć dawkę do poprawnego koloru','Kolor modelu nie jest celem leczenia.','Uznać symulator za rozstrzygający','Model jakościowy nie przewiduje indywidualnych stężeń.'],
]},
];
export const gahtLessons:DraftLesson[]=units.map(u=>({id:u.id,moduleId:'gonady',title:u.title,group:'GAHT · ścieżka mechanizmów',minutes:15,goals:u.concepts.slice(0,3).map(c=>`Wyjaśnisz: ${c[1].toLowerCase()}.`),sections:u.concepts.map(c=>({title:c[1],text:c[2]})),table:{headers:['Mechanizm / decyzja','Co zapamiętać'],rows:u.concepts.map(c=>[c[1],c[2]])},advanced:u.advanced,summary:u.concepts.map(c=>c[2].split('. ')[0]).join('. ')+'.',sourceIds:u.sources,review:{checkedAt:'2026-09-12',scope:'Mechanizmy, interpretacja badań, przedziały modeli PK/PD i punkty bezpieczeństwa; opracowanie bez recenzji klinicznej.'},questions:u.concepts.map(c=>({id:`${u.id}-${c[0]}-v2`,prompt:c[3],choices:[[c[4],c[2]],[c[5],c[6]],[c[7],c[8]]]} as DraftQuestion))}));
export const gahtLessonIds=gahtLessons.map(l=>l.id);
export const gahtConceptCards=units.flatMap(u=>u.concepts.map(c=>({id:`${u.id}-${c[0]}-concept-v2`,lessonId:u.id,front:`Wyjaśnij mechanizm: ${c[1].toLowerCase()}.`,back:c[2]})));
