import type { Source } from './course-types.ts';

export const diabetesSources: Record<string, Source> = {
  ptd_guidelines: {
    id: 'ptd_guidelines',
    title: 'Zalecenia kliniczne dotyczące postępowania u chorych na cukrzycę — Polskie Towarzystwo Diabetologiczne',
    year: '2025',
    url: 'https://cukrzyca.info.pl/zalecenia_ptd',
    kind: 'Polskie wytyczne',
  },
  ada_standards: {
    id: 'ada_standards',
    title: 'ADA Standards of Care in Diabetes — Diagnosis, Classification and Glycemic Targets',
    year: '2026',
    url: 'https://doi.org/10.2337/dc26-S002',
    kind: 'Wytyczne międzynarodowe',
  },
  cgm_consensus: {
    id: 'cgm_consensus',
    title: 'Clinical Targets for Continuous Glucose Monitoring Data Interpretation: Recommendations From the International Consensus on Time in Range',
    year: '2019',
    url: 'https://doi.org/10.2337/dci19-0028',
    kind: 'Konsensus międzynarodowy (ATTD)',
  },
  dka_guidelines: {
    id: 'dka_guidelines',
    title: 'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report by the American Diabetes Association and European Association for the Study of Diabetes',
    year: '2024',
    url: 'https://doi.org/10.2337/dci24-0032',
    kind: 'Konsensus stanów nagłych (ADA/EASD)',
  },
  t1d_staging: {
    id: 't1d_staging',
    title: 'Staging Presymptomatic Type 1 Diabetes: A Scientific Statement of the JDRF, Endocrine Society, and ADA',
    year: '2015',
    url: 'https://doi.org/10.2337/dc15-1419',
    kind: 'Oświadczenie naukowe',
  },
  mody_genetics: {
    id: 'mody_genetics',
    title: 'The use of precision diagnostics for monogenic diabetes: a systematic review and expert opinion',
    year: '2023',
    url: 'https://doi.org/10.1038/s43856-023-00369-8',
    kind: 'Przegląd kliniczny: genetyka',
  },
  ckd_diabetes: {
    id: 'ckd_diabetes',
    title: 'Executive summary of the KDIGO 2022 Clinical Practice Guideline for Diabetes Management in Chronic Kidney Disease: an update based on rapidly emerging new evidence',
    year: '2022',
    url: 'https://doi.org/10.1016/j.kint.2022.06.013',
    kind: 'Wytyczne nefrologiczne (KDIGO)',
  },
  cardiovascular_easd: {
    id: 'cardiovascular_easd',
    title: 'ESC Guidelines for the management of cardiovascular disease in patients with diabetes',
    year: '2023',
    url: 'https://doi.org/10.1093/eurheartj/ehad192',
    kind: 'Wytyczne kardiologiczne',
  },
  gdm_guidelines: {
    id: 'gdm_guidelines',
    title: 'Integrating nutrition and mental health screening, risk assessment, and management in gestational diabetes mellitus',
    year: '2023',
    url: 'https://doi.org/10.1002/ijgo.14728',
    kind: 'Wytyczne położnicze',
  },
  bergman_model: {
    id: 'bergman_model',
    title: 'Quantitative estimation of insulin sensitivity',
    year: '1979',
    url: 'https://doi.org/10.1152/ajpendo.1979.236.6.E667',
    kind: 'Podręcznik / Publikacja źródłowa: biocybernetyka',
  },
  insulin_biochem: {
    id: 'insulin_biochem',
    title: 'Insulin Receptor Signaling in Normal and Insulin-Resistant States',
    year: '2014',
    url: 'https://doi.org/10.1101/cshperspect.a009191',
    kind: 'Przegląd biochemiczny',
  },
  ketogenesis_biochem: {
    id: 'ketogenesis_biochem',
    title: 'Multi-dimensional Roles of Ketone Bodies in Fuel Metabolism, Signaling, and Therapeutics',
    year: '2017',
    url: 'https://doi.org/10.1016/j.cmet.2016.12.022',
    kind: 'Przegląd biochemiczny',
  },
};
