import type { Source } from './course';

export const pituitarySources: Record<string, Source> = {
  pituitary_endo: {
    id: 'pituitary_endo',
    title: 'Endotext — Hypothalamic-Pituitary Axis Physiology',
    year: '2023',
    url: 'https://www.ncbi.nlm.nih.gov/books/NBK279140/',
    kind: 'Podręcznik: fizjologia nadrzędna',
  },
  katznelson: {
    id: 'katznelson',
    title: 'Endocrine Society — Acromegaly: An Endocrine Society Clinical Practice Guideline',
    year: '2014',
    url: 'https://doi.org/10.1210/jc.2014-2700',
    kind: 'Wytyczne międzynarodowe',
  },
  melmed: {
    id: 'melmed',
    title: 'Endocrine Society — Diagnosis and Treatment of Hyperprolactinemia: An Endocrine Society Clinical Practice Guideline',
    year: '2011',
    url: 'https://doi.org/10.1210/jc.2010-1692',
    kind: 'Wytyczne: prolactinoma',
  },
  nieman: {
    id: 'nieman',
    title: 'Endocrine Society — Treatment of Cushing’s Syndrome: An Endocrine Society Clinical Practice Guideline',
    year: '2015',
    url: 'https://doi.org/10.1210/jc.2015-1818',
    kind: 'Wytyczne: hiperkortyzolemia',
  },
  fleseriu: {
    id: 'fleseriu',
    title: 'Endocrine Society — Hormonal Replacement in Hypopituitarism in Adults: An Endocrine Society Clinical Practice Guideline',
    year: '2016',
    url: 'https://doi.org/10.1210/jc.2016-2118',
    kind: 'Wytyczne: niedoczynność przysadki',
  },
  freda: {
    id: 'freda',
    title: 'Endocrine Society — Pituitary Incidentaloma: An Endocrine Society Clinical Practice Guideline',
    year: '2011',
    url: 'https://doi.org/10.1210/jc.2010-1048',
    kind: 'Wytyczne: incydentaloma i NFPA',
  },
  baldeweg: {
    id: 'baldeweg',
    title: 'Society for Endocrinology Emergency Guidance: Emergency management of pituitary apoplexy in adult patients',
    year: '2016',
    url: 'https://doi.org/10.1530/EC-16-0057',
    kind: 'Wytyczne: stany nagłe',
  },
  hyponatraemia: {
    id: 'hyponatraemia',
    title: 'ESE / ERA-EDTA — Clinical Practice Guideline on Hyponatraemia',
    year: '2014',
    url: 'https://doi.org/10.1530/EJE-13-1020',
    kind: 'Wytyczne: SIADH i zaburzenia sodowe',
  },
  pte_acro: {
    id: 'pte_acro',
    title: 'PTE — Diagnostics and treatment of acromegaly: updated recommendations of the Polish Society of Endocrinology',
    year: '2019',
    url: 'https://doi.org/10.5603/EP.a2018.0093',
    kind: 'Polskie wytyczne: PTE',
  },
  pte_cushing: {
    id: 'pte_cushing',
    title: 'Consensus on diagnosis and management of Cushing\'s disease: a guideline update',
    year: '2021',
    url: 'https://doi.org/10.1016/S2213-8587(21)00235-7',
    kind: 'Międzynarodowy konsensus: Cushing',
  },
  pituitary_prolactinoma_2023: {
    id: 'pituitary_prolactinoma_2023',
    title: 'Petersenn S et al. — Diagnosis and management of prolactin-secreting pituitary adenomas: a Pituitary Society consensus statement',
    year: '2023',
    url: 'https://doi.org/10.1038/s41574-023-00886-5',
    kind: 'Konsensus międzynarodowy (Pituitary Society)',
  },
  pituitary_incidentaloma_2025: {
    id: 'pituitary_incidentaloma_2025',
    title: 'Fleseriu M et al. — Pituitary incidentaloma: a Pituitary Society international consensus guidance statement',
    year: '2025',
    url: 'https://doi.org/10.1038/s41574-025-01134-8',
    kind: 'Konsensus międzynarodowy (Pituitary Society)',
  },
  avpd_copeptin: {
    id: 'avpd_copeptin',
    title: 'Fenske W, Refardt J, Christ-Crain M et al. — A Copeptin-Based Approach in the Diagnosis of Diabetes Insipidus',
    year: '2018',
    url: 'https://doi.org/10.1056/NEJMoa1803760',
    kind: 'Złoty standard diagnostyki AVP-D (NEJM)',
  },
};
