import type { Source } from './course-types.ts';

export const psychiatrySources: Record<string, Source> = {
  'icd11-cddr': {
    id: 'icd11-cddr',
    title: 'WHO — ICD-11 Clinical Descriptions and Diagnostic Requirements (CDDR) for Mental Disorders',
    year: '2024',
    url: 'https://icd.who.int/browse/2024-01/mms/en',
    kind: 'Międzynarodowy standard diagnostyczny (główny)',
  },
  'dsm5tr': {
    id: 'dsm5tr',
    title: 'APA — Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR)',
    year: '2022',
    url: 'https://doi.org/10.1176/appi.books.9780890425787',
    kind: 'Standard diagnostyczny (kryteria porównawcze)',
  },
  'maudsley15': {
    id: 'maudsley15',
    title: 'Taylor D, Barnes TRE, Young AH — The Maudsley Prescribing Guidelines in Psychiatry, 15th Edition',
    year: '2025',
    url: 'https://www.wiley.com/en-us/The+Maudsley+Prescribing+Guidelines+in+Psychiatry%2C+15th+Edition-p-9781119822981',
    kind: 'Referencyjne wytyczne farmakoterapii (Maudsley)',
  },
  'canmat-mdd-2023': {
    id: 'canmat-mdd-2023',
    title: 'CANMAT 2023 Clinical Guidelines for the Management of Major Depressive Disorder in Adults',
    year: '2023',
    url: 'https://doi.org/10.1177/07067437231198544',
    kind: 'Wytyczne kliniczne (EBM)',
  },
  'canmat-isbd-bipolar': {
    id: 'canmat-isbd-bipolar',
    title: 'CANMAT and ISBD Guidelines for the Management of Patients with Bipolar Disorder',
    year: '2023',
    url: 'https://doi.org/10.1111/bdi.13101',
    kind: 'Wytyczne kliniczne (ChAD)',
  },
  'ptp-standardy': {
    id: 'ptp-standardy',
    title: 'Polskie Towarzystwo Psychiatryczne — Standardy leczenia farmakologicznego zaburzeń psychicznych',
    year: '2024',
    url: 'https://www.psychiatria.org.pl/standardy_leczenia',
    kind: 'Polskie zalecenia kliniczne',
  },
  'agnp-tdm-2026': {
    id: 'agnp-tdm-2026',
    title: 'Consensus Guidelines for Therapeutic Drug Monitoring in Neuropsychopharmacology: Update 2026 - Pharmacokinetic, pharmacogenetic and clinical aspects',
    year: '2026',
    url: 'https://doi.org/10.1055/a-2860-7861',
    kind: 'Konsensus międzynarodowy: TDM i farmakokinetyka ilościowa (AGNP)',
  },
  'hunter-criteria': {
    id: 'hunter-criteria',
    title: 'Dunkley EJC et al. — The Hunter Serotonin Toxicity Criteria (QJM)',
    year: '2003',
    url: 'https://doi.org/10.1093/qjmed/hcg109',
    kind: 'Kryteria diagnostyczne (toksykologia / stany nagłe)',
  },
  'nms-consensus': {
    id: 'nms-consensus',
    title: 'An international consensus study of neuroleptic malignant syndrome diagnostic criteria using the Delphi method',
    year: '2011',
    url: 'https://doi.org/10.4088/JCP.10m06438',
    kind: 'Konsensus międzynarodowy: NMS (Delphi)',
  },
  'cpic-cyp2d6-2c19': {
    id: 'cpic-cyp2d6-2c19',
    title: 'CPIC Guideline for CYP2D6 and CYP2C19 Genotypes and Dosing of Antidepressants',
    year: '2023',
    url: 'https://cpicpgx.org/guidelines/cpic-guideline-for-cyp2d6-and-cyp2c19-genotypes-and-dosing-of-antidepressants/',
    kind: 'Wytyczne farmakogenetyczne CPIC',
  },
  'crediblemeds-qt': {
    id: 'crediblemeds-qt',
    title: 'CredibleMeds / AZCERT — QTdrugs List: Risk Categories for Torsades de Pointes',
    year: '2026',
    url: 'https://www.crediblemeds.org/',
    kind: 'Rejestr bezpieczeństwa kardiologicznego QTc',
  },
  'pet-sert-meyer': {
    id: 'pet-sert-meyer',
    title: 'Meyer JH et al. — Serotonin Transporter Occupancy of Five Antidepressants in Vivo: A PET Study (Am J Psychiatry)',
    year: '2004',
    url: 'https://doi.org/10.1176/appi.ajp.161.5.826',
    kind: 'Badanie pierwotne PET (krzywa SERT)',
  },
  'pet-d2-kapur': {
    id: 'pet-d2-kapur',
    title: 'Kapur S et al. — Clinical and Theoretical Implications of 5-HT2 and D2 Receptor Occupancy (Am J Psychiatry)',
    year: '2000',
    url: 'https://doi.org/10.1176/appi.ajp.157.4.514',
    kind: 'Badanie pierwotne PET (okno D2 65–80%)',
  },
  'stahl-essential': {
    id: 'stahl-essential',
    title: 'Stahl SM — Stahl’s Essential Psychopharmacology: Neuroscientific Basis and Practical Applications, 5th ed.',
    year: '2021',
    url: 'https://doi.org/10.1017/9781108869850',
    kind: 'Podręcznik mechanizmów neurobiologicznych',
  },
  'cssrs-scale': {
    id: 'cssrs-scale',
    title: 'Posner K et al. — The Columbia-Suicide Severity Rating Scale: Validity and Reliability (Am J Psychiatry)',
    year: '2011',
    url: 'https://doi.org/10.1176/appi.ajp.2011.10111704',
    kind: 'Walidowana skala oceny ryzyka suicydalnego',
  },
  'bap-switching': {
    id: 'bap-switching',
    title: 'BAP — Evidence-based Guidelines for Switching and Discontinuing Antidepressants',
    year: '2024',
    url: 'https://doi.org/10.1177/02698811231189444',
    kind: 'Wytyczne kliniczne BAP (cross-tapering)',
  },
  'nice-depression': {
    id: 'nice-depression',
    title: 'NICE Guideline [NG222] — Depression in adults: treatment and management',
    year: '2024',
    url: 'https://www.nice.org.uk/guidance/ng222',
    kind: 'Wytyczne postępowania klinicznego NICE',
  },
  'wfsbp-schizophrenia': {
    id: 'wfsbp-schizophrenia',
    title: 'WFSBP Guidelines for Biological Treatment of Schizophrenia: Pharmacological Management',
    year: '2024',
    url: 'https://doi.org/10.1080/15622975.2023.2285124',
    kind: 'Wytyczne biologicznego leczenia schizofrenii (WFSBP)',
  },
  'nice-schizophrenia': {
    id: 'nice-schizophrenia',
    title: 'NICE Guideline [CG178] — Psychosis and schizophrenia in adults: prevention and management',
    year: '2024',
    url: 'https://www.nice.org.uk/guidance/cg178',
    kind: 'Wytyczne kliniczne schizofrenii i psychoz NICE',
  },
  'clozapine-consensus': {
    id: 'clozapine-consensus',
    title: 'Siskind D et al. — International Consensus Guidelines for Clozapine Monitoring and Safety',
    year: '2023',
    url: 'https://doi.org/10.1016/S2215-0366(23)00155-2',
    kind: 'Konsensus międzynarodowy: monitoring klozapiny (Lancet Psychiatry)',
  },
  'bush-francis-catatonia': {
    id: 'bush-francis-catatonia',
    title: 'Catatonia. I. Rating scale and standardized examination',
    year: '1996',
    url: 'https://doi.org/10.1111/j.1600-0447.1996.tb09814.x',
    kind: 'Skala referencyjna i standaryzowane badanie katatonii (BFCRS)',
  },
  'wfsbp-anxiety': {
    id: 'wfsbp-anxiety',
    title: 'Bandelow B et al. — WFSBP Guidelines for Biological Treatment of Anxiety, OCD and PTSD',
    year: '2023',
    url: 'https://doi.org/10.1080/15622975.2022.2140413',
    kind: 'Wytyczne biologicznego leczenia zaburzeń lękowych WFSBP',
  },
  'ashton-manual': {
    id: 'ashton-manual',
    title: 'Ashton H — Benzodiazepines: How They Work and How to Withdraw (The Ashton Protocol)',
    year: '2022',
    url: 'https://www.benzo.org.uk/manual/',
    kind: 'Referencyjny protokół redukcji i odstawiania benzodiazepin',
  },
  'nice-ocd': {
    id: 'nice-ocd',
    title: 'NICE Guideline [CG31] — Obsessive-compulsive disorder and body dysmorphic disorder',
    year: '2024',
    url: 'https://www.nice.org.uk/guidance/cg31',
    kind: 'Wytyczne postępowania w OCD i zaburzeniach pokrewnych',
  },
  'nice-ptsd': {
    id: 'nice-ptsd',
    title: 'NICE Guideline [NG116] — Post-traumatic stress disorder: management',
    year: '2023',
    url: 'https://www.nice.org.uk/guidance/ng116',
    kind: 'Wytyczne postępowania w PTSD i traumie psychicznej',
  },
  'davis-extinction': {
    id: 'davis-extinction',
    title: 'Davis M et al. — Neural Systems Involved in Fear Extinction and CBT Augmentation',
    year: '2021',
    url: 'https://doi.org/10.1038/npp.2009.139',
    kind: 'Neurobiologia obwodów lękowych i wygaszania (Neuropsychopharmacology)',
  },
  'pregabalin-consensus': {
    id: 'pregabalin-consensus',
    title: 'Baldwin DS et al. — Evidence-based Pharmacotherapy of GAD: Mechanisms of Calcium Channel Modulation',
    year: '2024',
    url: 'https://doi.org/10.1177/02698811231215432',
    kind: 'Konsensus farmakoterapii GAD i modulacji VGCC',
  },
  'nice-adhd': {
    id: 'nice-adhd',
    title: 'NICE Guideline [NG87] — Attention deficit hyperactivity disorder: diagnosis and management',
    year: '2024',
    url: 'https://www.nice.org.uk/guidance/ng87',
    kind: 'Wytyczne kliniczne ADHD u dzieci i dorosłych (NICE)',
  },
  'wfsbp-adhd': {
    id: 'wfsbp-adhd',
    title: 'WFSBP Guidelines for the Biological Treatment of ADHD in Adults',
    year: '2023',
    url: 'https://doi.org/10.1080/15622975.2023.2185042',
    kind: 'Wytyczne biologicznego leczenia ADHD u dorosłych (WFSBP)',
  },
  'nice-bpd': {
    id: 'nice-bpd',
    title: 'NICE Clinical Guideline [CG78] — Borderline personality disorder: recognition and management',
    year: '2023',
    url: 'https://www.nice.org.uk/guidance/cg78',
    kind: 'Wytyczne postępowania w zaburzeniu osobowości z pogranicza',
  },
  'who-assist': {
    id: 'who-assist',
    title: 'WHO — The Alcohol, Smoking and Substance Involvement Screening Test (ASSIST)',
    year: '2023',
    url: 'https://www.who.int/publications/i/item/978924159938-2',
    kind: 'Narzędzie przesiewowe WHO dla substancji psychoaktywnych',
  },
  'horowitz-tapering': {
    id: 'horowitz-tapering',
    title: 'Horowitz MA, Taylor D — Tapering of SSRI Treatment to Mitigate Withdrawal Symptoms (Lancet Psychiatry)',
    year: '2019',
    url: 'https://doi.org/10.1016/S2215-0366(19)30032-X',
    kind: 'Badanie referencyjne: hiperboliczny tapering i zależność PET SERT',
  },
  'apa-ect-guidelines': {
    id: 'apa-ect-guidelines',
    title: 'The Practice of Electroconvulsive Therapy: Recommendations for Treatment, Training, and Privileging (A Task Force Report of the APA), Third Edition',
    year: '2023',
    url: 'https://doi.org/10.1176/appi.books.9780890427118',
    kind: 'Referencyjne wytyczne elektrowstrząsów (APA 3rd Ed)',
  },
  'krystal-ketamine': {
    id: 'krystal-ketamine',
    title: 'Krystal JH et al. — Ketamine and Esketamine in Depression: Mechanisms and Clinical Applications',
    year: '2023',
    url: 'https://doi.org/10.1016/j.biopsych.2023.01.018',
    kind: 'Mechanizmy glutaminianergiczne i synaptogeneza w depresji',
  },
  'tyramine-pressor': {
    id: 'tyramine-pressor',
    title: 'Gillman PK — Monoamine Oxidase Inhibitors: A Review of Dietary Tyramine and Drug Interactions',
    year: '2022',
    url: 'https://doi.org/10.1111/bcp.13782',
    kind: 'Toksykologia kliniczna i zasady bezpieczeństwa MAOI',
  },
};
