import type { GlossaryItem } from './glossary.ts';

export const diabetesGlossary: GlossaryItem[] = [
  {
    id: 'insulina',
    term: 'Insulina',
    aliases: ['insulin'],
    category: 'hormony',
    definition: 'Anaboliczny hormon polipeptydowy wytwarzany przez komórki beta wysp trzustkowych, stymulujący wychwyt glukozy i lipogenezę.',
    normalRange: 'Na czczo: 2–20 uIU/ml (zależnie od metody)',
    clinicalSignificance: 'Bezwzględny niedobór prowadzi do cukrzycy typu 1 i kwasicy ketonowej DKA; oporność tkanek na insulinę jest osiowym defektem cukrzycy typu 2.',
  },
  {
    id: 'c-peptyd',
    term: 'Peptyd C',
    aliases: ['C-peptide', 'peptyd łączący'],
    category: 'diagnostyka',
    definition: '31-aminokwasowy fragment proinsuliny uwalniany ekwimolarnie z insuliną, niepodlegający klirensowi pierwszego przejścia w wątrobie.',
    normalRange: 'Na czczo: 1,1–4,4 ng/ml (0,37–1,47 nmol/l)',
    clinicalSignificance: 'Najbardziej miarodajny marker endogennej rezerwy komórek beta trzustki. Nie reaguje krzyżowo z podawaną podskórnie insuliną egzogenną.',
  },
  {
    id: 'hba1c',
    term: 'HbA1c',
    aliases: ['hemoglobina glikowana', 'A1c'],
    category: 'diagnostyka',
    definition: 'Frakcja hemoglobiny trwale związana nieenzymatycznie z glukozą, odzwierciedlająca średnią glikemię z ostatnich 8–12 tygodni.',
    normalRange: '< 5,7% (39 mmol/mol); cel w cukrzycy zwykle <= 7,0% (53 mmol/mol)',
    clinicalSignificance: 'Wartość >= 6,5% jest kryterium rozpoznania cukrzycy. Wynik bywa fałszywie zaniżony w hemolizie i fałszywie zawyżony w niedoborze żelaza.',
  },
  {
    id: 'glukagon',
    term: 'Glukagon',
    aliases: ['glucagon'],
    category: 'hormony',
    definition: 'Hormon kataboliczny wydzielany przez komórki alfa wysp trzustkowych w odpowiedzi na spadek glikemii.',
    clinicalSignificance: 'Główny hormon kontrregulacyjny stymulujący wątrobową glikogenolizę i glukoneogenezę. Lek ratunkowy w ciężkiej hipoglikemii.',
  },
  {
    id: 'dka',
    term: 'Cukrzycowa kwasica ketonowa (DKA)',
    aliases: ['DKA', 'diabetic ketoacidosis'],
    category: 'choroby',
    definition: 'Ostry, zagrażający życiu zespół dekompensacji metabolicznej z hiperglikemią, kwasicą metaboliczną (pH <= 7,30, HCO3- < 18) i wysoką ketonemią.',
    clinicalSignificance: 'Wymaga intensywnego nawadniania i dożylnego wlewu insuliny pod warunkiem prawidłowego stężenia potasu (K+ >= 3,3 mmol/l).',
  },
  {
    id: 'hhs',
    term: 'Zespół hiperglikemiczno-hiperosmolarny (HHS)',
    aliases: ['HHS', 'stan hiperosmolarny'],
    category: 'choroby',
    definition: 'Stan skrajnej hiperglikemii (> 600 mg/dl) i hiperosmolalności efektywnej (> 320 mOsm/kg H2O) u chorych na T2D bez istotnej ketozy.',
    clinicalSignificance: 'Cechuje się deficytem płynów rzędu 8–12 litrów i wysokim ryzykiem powikłań zatorowych, wymagając powolnej rehydratacji i heparyny.',
  },
  {
    id: 'tir',
    term: 'Time in Range (TIR)',
    aliases: ['czas w zakresie docelowym'],
    category: 'diagnostyka',
    definition: 'Odsetek czasu w dobie, w którym glikemia rejestrowana przez sensor CGM mieści się w przedziale 70–180 mg/dl (3,9–10,0 mmol/l).',
    normalRange: 'Cel dla T1D i T2D: > 70% doby (> 16 godz. 48 min)',
    clinicalSignificance: 'Kluczowy parametr nowoczesnej oceny wyrównania cukrzycy korelujący ze spadkiem ryzyka retinopatii i nefropatii; TIR 70% odpowiada HbA1c ~7,0%.',
  },
  {
    id: 'isf',
    term: 'Współczynnik wrażliwości na insulinę (ISF)',
    aliases: ['ISF', 'Insulin Sensitivity Factor'],
    category: 'fizjologia',
    definition: 'Wartość określająca, o ile mg/dl (lub mmol/l) obniży się glikemia po podaniu 1 jednostki insuliny szybkodziałającej (reguła 1800/TDD).',
    clinicalSignificance: 'Podstawa precyzyjnej kalkulacji bolusów korekcyjnych w penach i osobistych pompach insulinowych.',
  },
  {
    id: 'icr',
    term: 'Wskaźnik węglowodanowo-insulinowy (ICR)',
    aliases: ['ICR', 'CIR', 'Carb to Insulin Ratio'],
    category: 'fizjologia',
    definition: 'Liczba gramów węglowodanów w posiłku metabolizowana przez 1 jednostkę insuliny prandialnej (reguła 500/TDD).',
    clinicalSignificance: 'Umożliwia elastyczne dopasowanie dawki insuliny przed posiłkiem w zależności od gramatury spożywanych węglowodanów.',
  },
  {
    id: 'sglt-2',
    term: 'Inhibitory SGLT2',
    aliases: ['flozyny', 'SGLT2 inhibitors'],
    category: 'leki',
    definition: 'Klasa leków doustnych blokujących nerkowy kotransporter sodowo-glukozowy 2 w kanalikach bliższych, wywołujących glukozurię i natriurezę.',
    clinicalSignificance: 'Zapewniają przełomową redukcję hospitalizacji z powodu niewydolności serca i spowalniają progresję PChN (KDIGO 1A).',
  },
  {
    id: 'glp-1',
    term: 'Agoniści receptora GLP-1',
    aliases: ['analogi GLP-1', 'inkretyny'],
    category: 'leki',
    definition: 'Leki stymulujące receptor glukagonopodobnego peptydu 1, nasilające sekrecję insuliny zależnie od glukozy i hamujące łaknienie.',
    clinicalSignificance: 'Radykalnie redukują ryzyko zawałów, udarów mózgu (MACE) i masy ciała u chorych na cukrzycę typu 2 i otyłość.',
  },
  {
    id: 'mody',
    term: 'Cukrzyca MODY',
    aliases: ['Maturity-Onset Diabetes of the Young'],
    category: 'choroby',
    definition: 'Grupa monogenowych postaci cukrzycy dziedziczonych autosomalnie dominująco (najczęściej mutacje genów HNF1A i GCK).',
    clinicalSignificance: 'MODY 2 (GCK) nie wymaga leczenia farmakologicznego, a MODY 3 (HNF1A) znakomicie odpowiada na małe dawki pochodnych sulfonylomocznika.',
  },
  {
    id: 'lada',
    term: 'Cukrzyca LADA',
    aliases: ['Latent Autoimmune Diabetes in Adults'],
    category: 'choroby',
    definition: 'Wolno postępująca cukrzyca autoimmunologiczna u dorosłych z obecnością przeciwciał anty-GAD i stopniowym wygasaniem komórek beta.',
    clinicalSignificance: 'Często mylona z T2D; wymaga wczesnego wdrożenia małych dawek insuliny w celu ochrony resztkowych wysp trzustkowych.',
  },
  {
    id: 'homa-ir',
    term: 'HOMA-IR',
    aliases: ['wskaźnik insulinooporności HOMA'],
    category: 'diagnostyka',
    definition: 'Model matematyczny szacujący stopień insulinooporności na podstawie iloczynu glikemii i insulinemii na czczo.',
    normalRange: '< 2,0–2,5 u osób zdrowych',
    clinicalSignificance: 'Wartości > 2,5 świadczą o istotnej oporności tkanek obwodowych i wątroby na działanie insuliny.',
  },
  {
    id: 'glut4',
    term: 'GLUT4',
    aliases: ['transporter glukozy 4'],
    category: 'fizjologia',
    definition: 'Wrażliwy na insulinę transporter glukozy zlokalizowany w pęcherzykach wewnątrzkomórkowych mięśni szkieletowych, serca i tkanki tłuszczowej.',
    clinicalSignificance: 'Translokacja GLUT4 do błony komórkowej pod wpływem kaskady IRS-1/PI3K/Akt/AS160 stanowi główny mechanizm obwodowego zużycia glukozy.',
  },
  {
    id: 'as160',
    term: 'AS160',
    aliases: ['TBC1D4', 'Akt Substrate of 160 kDa'],
    category: 'fizjologia',
    definition: 'Białko regulatorowe o aktywności Rab-GAP, którego fosforylacja przez kinazę Akt umożliwia egzocytozę pęcherzyków z GLUT4.',
    clinicalSignificance: 'Kluczowy molekularny łącznik między kaskadą kinazową receptora insulinowego a ruchem pęcherzyków nośnikowych GLUT4.',
  },
  {
    id: 'finerenon',
    term: 'Finerenon',
    aliases: ['non-steroidal MRA'],
    category: 'leki',
    definition: 'Niesteroidowy, selektywny antagonista receptora mineralokortykoidowego hamujący włóknienie i stan zapalny w nerkach i sercu.',
    clinicalSignificance: 'Lek o udowodnionej nefroprotekcji w cukrzycowej chorobie nerek (DKD) z albuminurią na tle cukrzycy typu 2 (badania FIDELIO/FIGARO).',
  },
];
