import type { GlossaryItem } from './glossary.ts';

export const otyloscGlossary: GlossaryItem[] = [
  {
    id: 'gip',
    term: 'Glukozozależny polipeptyd insulinotropowy (GIP)',
    aliases: ['gip', 'gastric inhibitory polypeptide'],
    category: 'fizjologia',
    definition: 'Hormon inkretynowy wydzielany przez komórki K dwunastnicy i jelita czczego w odpowiedzi na składniki odżywcze (tłuszcze i glukozę).',
    clinicalSignificance: 'Pobudza sekrecję insuliny zależnie od glukozy, moduluje buforowanie lipidów w podskórnej tkance tłuszczowej i działa synergistycznie z GLP-1 w tirzepatydzie.',
  },
  {
    id: 'semaglutyd',
    term: 'Semaglutyd (Wegovy / Ozempic)',
    aliases: ['semaglutide', 'wegovy'],
    category: 'leki',
    definition: 'Długodziałający analog GLP-1 z łańcuchem dikarboksylowym C18 i podstawieniem Aib8, oporny na enzym DPP-4, podawany podskórnie raz w tygodniu.',
    normalRange: 'Dawka docelowa w otyłości: 2,4 mg s.c. 1x/tydzień',
    clinicalSignificance: 'Zapewnia średnią redukcję masy ciała o ~15% (STEP 1) i zmniejsza ryzyko zawałów, udarów oraz zgonu naczyniowego o 20% (badanie SELECT).',
  },
  {
    id: 'tirzepatyd',
    term: 'Tirzepatyd (Zepbound / Mounjaro)',
    aliases: ['tirzepatide', 'zepbound', 'twincretin'],
    category: 'leki',
    definition: 'Pierwszy syntetyczny podwójny agonista receptorów GLP-1 oraz GIP (twincretin) z łańcuchem kwasu tłuszczowego C20.',
    normalRange: 'Dawki: 2,5 mg do maksymalnie 15 mg s.c. 1x/tydzień',
    clinicalSignificance: 'Indukuje bezprecedensową redukcję masy ciała o 21–22,5% (program SURMOUNT) oraz spektakularną poprawę parametrów glikemicznych i lipidowych.',
  },
  {
    id: 'leptyna',
    term: 'Leptyna',
    aliases: ['leptin', 'hormon sytości'],
    category: 'fizjologia',
    definition: 'Adipokina białkowa o masie 16 kDa kodowana przez gen LEP, wydzielana przez białą tkankę tłuszczową proporcjonalnie do jej masy.',
    normalRange: 'Mężczyźni: 1–10 ng/ml; Kobiety: 5–25 ng/ml (silnie zależy od BMI)',
    clinicalSignificance: 'Działa anoreksygennie w podwzgórzu (stymuluje POMC, hamuje AgRP). W otyłości występuje hiperleptynemia i leptynooporność.',
  },
  {
    id: 'adiponektyna',
    term: 'Adiponektyna',
    aliases: ['adiponectin', 'acrp30'],
    category: 'fizjologia',
    definition: 'Wielocząsteczkowa adipokina produkowana przez dojrzałe adipocyty, działająca za pośrednictwem receptorów AdipoR1 i AdipoR2.',
    normalRange: '5–30 ug/ml (wyższe stężenia u kobiet)',
    clinicalSignificance: 'Wybiórczo aktywuje kinazę AMPK, działa przeciwzapalnie, przeciwcukrzycowo i przeciwmiażdżycowo. W otyłości jej stężenie paradoksalnie spada.',
  },
  {
    id: 'mc4r',
    term: 'Receptor melanokortyny 4 (MC4R)',
    aliases: ['mc4r', 'melanocortin 4 receptor'],
    category: 'anatomia',
    definition: 'Receptor sprzężony z białkiem Gs w jądrze przykomorowym podwzgórza, aktywowany przez alfa-MSH, kluczowy element osi sytości.',
    clinicalSignificance: 'Mutacje utraty funkcji MC4R są najczęstszą monogenową przyczyną otyłości (3–5% ciężkiej otyłości dziecięcej) z hiperfagią i wysokim wzrostem.',
  },
  {
    id: 'setmelanotyd',
    term: 'Setmelanotyd (Imcivree)',
    aliases: ['setmelanotide', 'mc4r agonist'],
    category: 'leki',
    definition: 'Cykliczny syntetyczny peptydowy agonista receptora melanokortyny 4 (MC4R) podawany podskórnie raz na dobę.',
    clinicalSignificance: 'Pierwszy celowany lek zaaprobowany w rzadkich monogenowych otyłościach: niedoborze POMC, PCSK1, LEPR oraz zespole Bardeta-Biedla (BBS).',
  },
  {
    id: 'masld',
    term: 'Stłuszczeniowa choroba wątroby związana z dysfunkcją metaboliczną (MASLD)',
    aliases: ['masld', 'steatotic liver disease', 'dawniej nafld'],
    category: 'choroby',
    definition: 'Nowa nomenklatura zastępująca NAFLD, definiowana jako stłuszczenie wątroby z obecnością co najmniej 1 czynnika kardiometabolicznego.',
    clinicalSignificance: 'Najczęstsza przewlekła choroba wątroby na świecie (dotyczy > 30% populacji), bezpośrednio powiązana z otyłością brzuszną i insulinoopornością.',
  },
  {
    id: 'mash',
    term: 'Stłuszczeniowe zapalenie wątroby związane z dysfunkcją metaboliczną (MASH)',
    aliases: ['mash', 'metabolic steatohepatitis', 'dawniej nash'],
    category: 'choroby',
    definition: 'Postać MASLD charakteryzująca się obecnością zapalenia zrazikowego, zwyrodnienia balonowatego hepatocytów oraz progresywnym włóknieniem.',
    clinicalSignificance: 'Główna przyczyna marskości metabolicznej i raka wątrobowokomórkowego (HCC). Wskazanie do analogów GLP-1/GIP i rezmetiromu.',
  },
  {
    id: 'fib-4',
    term: 'Wskaźnik zwłóknienia wątroby FIB-4',
    aliases: ['fib-4 index', 'fibrosis 4'],
    category: 'diagnostyka',
    definition: 'Nieinwazyjny wskaźnik laboratoryjny wyliczany ze wzoru: [Wiek (lata) * AST (U/l)] / [Płytki krwi (10^9/l) * pierwiastek kwadratowy z ALT (U/l)].',
    normalRange: '< 1,30 (niska szansa zwłóknienia; u osób > 65 r.ż. punkt odcięcia < 2,0)',
    clinicalSignificance: 'Narzędzie przesiewowe wykluczające zaawansowane zwłóknienie F3–F4 z wartością ujemną NPV > 90%. Wynik > 2,67 wymaga pilnej elastografii.',
  },
  {
    id: 'rygb',
    term: 'Ominięcie żołądkowe Roux-en-Y (RYGB)',
    aliases: ['rygb', 'gastric bypass'],
    category: 'diagnostyka',
    definition: 'Operacja bariatryczna polegająca na wytworzeniu małego zbiornika żołądkowego (20–30 ml) i zespoleniu go z wyłączoną pętlą jelita czczego Roux-en-Y.',
    clinicalSignificance: 'Złoty standard chirurgii metabolicznej w otyłości z GERD i cukrzycą typu 2; daje ~30–35% TBWL i natychmiastową hormonalną remisję cukrzycy.',
  },
  {
    id: 'lsg',
    term: 'Laparoskopowa rękawowa resekcja żołądka (LSG)',
    aliases: ['lsg', 'sleeve gastrectomy'],
    category: 'diagnostyka',
    definition: 'Operacja polegająca na podłużnym wycięciu 75–80% żołądka wzdłuż krzywizny większej z pozostawieniem wąskiego rękawa na sondzie 36–40 Fr.',
    clinicalSignificance: 'Najczęściej wykonywana operacja bariatryczna na świecie; wycina dno żołądka obniżając stężenie greliny, lecz może zaostrzać refluks (GERD).',
  },
  {
    id: 'dumping-syndrome',
    term: 'Zespół poposiłkowy (Dumping Syndrome)',
    aliases: ['dumping', 'zespół poresekcyjny'],
    category: 'choroby',
    definition: 'Zaburzenie wynikające z braku odźwiernika żołądkowego: wczesne (hipowolemia, flushing < 30 min) lub późne (hipoglikemia reaktywna 1–3 h po posiłku).',
    clinicalSignificance: 'Późny dumping wynika z nadmiernego wyrzutu GLP-1 i hiperinsulinizmu po węglowodanach prostych; leczenie dietą o niskim IG i akarbozą.',
  },
  {
    id: 'fh',
    term: 'Hipercholesterolemia rodzinna (FH)',
    aliases: ['fh', 'familial hypercholesterolaemia'],
    category: 'choroby',
    definition: 'Autosomalna dominująca choroba jednogenowa wywołana mutacjami genów LDLR, APOB lub PCSK9, powodująca skrajnie wysoki LDL-C od urodzenia.',
    normalRange: 'HeFH: LDL-C zwykle 190–400 mg/dl; HoFH: LDL-C > 400–1000 mg/dl',
    clinicalSignificance: 'Prowadzi do wczesnej choroby wieńcowej i zawałów serca w młodym wieku. Wymaga skali DLCN, screeningu kaskadowego i intensywnej terapii trójlekowej.',
  },
  {
    id: 'pcsk9',
    term: 'Proproteina konwertaza subtylizyny/keksyny typu 9 (PCSK9)',
    aliases: ['pcsk9', 'proprotein convertase subtilisin/kexin 9'],
    category: 'fizjologia',
    definition: 'Wątrobowa proteaza wiążąca się z receptorem LDLR na powierzchni hepatocytu, kierująca go do degradacji lizosomalnej zamiast recyklingu.',
    clinicalSignificance: 'Zablokowanie PCSK9 przeciwciałami monoklonalnymi (ewolokumab, alirokumab) lub siRNA (inklisiran) zwiększa gęstość LDLR i obniża LDL-C o 50–60%.',
  },
  {
    id: 'inklisiran',
    term: 'Inklisiran (Leqvio)',
    aliases: ['inclisiran', 'leqvio'],
    category: 'leki',
    definition: 'Syntetyczny podwójnoniciowy siRNA sprzężony z N-acetylogalaktozaminą (GalNAc), wybiórczo wyciszający translację mRNA PCSK9 w wątrobie.',
    normalRange: 'Dawkowanie: 284 mg s.c. w dniu 0, po 3 miesiącach, a następnie co 6 miesięcy',
    clinicalSignificance: 'Zapewnia stabilne obniżenie stężenia LDL-C o około 50% przy podawaniu podskórnym zaledwie dwa razy w roku, gwarantując znakomitą adherencję.',
  },
  {
    id: 'kwas-bempedonowy',
    term: 'Kwas bempedonowy (Nilemdo)',
    aliases: ['bempedoic acid', 'nilemdo'],
    category: 'leki',
    definition: 'Doustny inhibitor liazy cytrynianowej ATP (ACL) hamujący syntezę cholesterolu powyżej reduktazy HMG-CoA.',
    normalRange: 'Dawka: 180 mg doustnie raz na dobę',
    clinicalSignificance: 'Prolek aktywowany wyłącznie w wątrobie przez ACSVL1 (nieobecny w mięśniach), stanowiący przełom u chorych z nietolerancją statyn (SAMS).',
  },
  {
    id: 'score2',
    term: 'Kalkulator ryzyka sercowo-naczyniowego SCORE2',
    aliases: ['score2', 'score2-op'],
    category: 'diagnostyka',
    definition: 'Europejski algorytm szacujący 10-letnie ryzyko zgonu sercowo-naczyniowego oraz niepowikłanych zawałów i udarów mózgu u osób w wieku 40–69 lat.',
    clinicalSignificance: 'Definiuje progi ryzyka (małe, umiarkowane, duże, bardzo duże) determinujące cele terapeutyczne LDL-C (< 55 mg/dl w bardzo dużym ryzyku).',
  },
  {
    id: 'fcs',
    term: 'Zespół rodzinnej chylomikronemii (FCS)',
    aliases: ['fcs', 'zespół chylomikronemii'],
    category: 'choroby',
    definition: 'Rzadka choroba autosomalna recesywna wywołana brakiem lipazy lipoproteinowej (LPL) lub ApoC-II, z triglicerydami sięgającymi 1000–3000 mg/dl.',
    clinicalSignificance: 'Objawia się mleczną surowicą krwi, żółtakami kępkowatymi i nawracającymi epizodami ostrego zapalenia trzustki; wymaga diety < 20 g tłuszczu/d.',
  },
  {
    id: 'adaptacja-metaboliczna',
    term: 'Adaptacja metaboliczna (termogeneza adaptacyjna)',
    aliases: ['adaptive thermogenesis', 'spadek bmr'],
    category: 'fizjologia',
    definition: 'Fizjologiczny spadek spoczynkowego wydatku energetycznego (BMR) przekraczający ten wynikający ze statycznej utraty masy tkanek.',
    clinicalSignificance: 'Podstawowy biologiczny mechanizm powstawania plateau podczas odchudzania oraz szybkiego nawrotu masy ciała (efekt jojo) po zaprzestaniu restrykcji.',
  },
];
