import type { ObesitySimulatorInputs } from './obesity-simulator.ts';

export interface ObesityPreset {
  id: string;
  name: string;
  badge?: string;
  description: string;
  data: ObesitySimulatorInputs;
}

export const defaultObesityInputs: ObesitySimulatorInputs = {
  age: 42,
  sex: 'F',
  heightCm: 165,
  weightKg: 98,
  pal: 1.3,
  caloricIntake: 2000,
  bodyFatPct: 41,
  selectedDrug: 'semaglutide',
  drugDoseMg: 2.4,
  adherencePct: 100,
  comorbidities: {
    t2d: false,
    htn: false,
    osas: false,
    masld: true,
    gerd: false,
    dyslipidemia: true,
  },
  bariatricProcedure: 'none',
  monthsPostOp: 0,
  tcMgDl: 230,
  hdlMgDl: 44,
  tgMgDl: 185,
  sbpMmHg: 130,
  smoker: false,
  statinRegimen: 'none',
  astU_L: 38,
  altU_L: 46,
  plt10e9_L: 240,
};

export const obesityPresets: ObesityPreset[] = [
  {
    id: 'glp1-qualification',
    name: 'Kwalifikacja do semaglutydu 2.4 mg',
    badge: 'GLP-1 RA',
    description: 'Kobieta 42 lata, BMI 36 kg/m², stan przedcukrzycowy, niska aktywność.',
    data: {
      age: 42,
      sex: 'F',
      heightCm: 165,
      weightKg: 98,
      pal: 1.3,
      caloricIntake: 2000,
      bodyFatPct: 41,
      selectedDrug: 'semaglutide',
      drugDoseMg: 2.4,
      adherencePct: 100,
      comorbidities: { t2d: false, htn: false, osas: false, masld: true, gerd: false, dyslipidemia: true },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 230,
      hdlMgDl: 44,
      tgMgDl: 185,
      sbpMmHg: 130,
      smoker: false,
      statinRegimen: 'none',
      astU_L: 38,
      altU_L: 46,
      plt10e9_L: 240,
    },
  },
  {
    id: 'tirzepatide-severe',
    name: 'Tirzepatyd w otyłości II st. i T2D',
    badge: 'Dual Agonist',
    description: 'Mężczyzna 48 lat, BMI 38 kg/m², cukrzyca typu 2, dyslipidemia aterogenna.',
    data: {
      age: 48,
      sex: 'M',
      heightCm: 176,
      weightKg: 118,
      pal: 1.4,
      caloricIntake: 2400,
      bodyFatPct: 37,
      selectedDrug: 'tirzepatide',
      drugDoseMg: 15,
      adherencePct: 100,
      comorbidities: { t2d: true, htn: true, osas: false, masld: true, gerd: false, dyslipidemia: true },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 250,
      hdlMgDl: 36,
      tgMgDl: 280,
      sbpMmHg: 145,
      smoker: false,
      statinRegimen: 'high',
      astU_L: 44,
      altU_L: 58,
      plt10e9_L: 210,
    },
  },
  {
    id: 'bariatric-candidate-rygb',
    name: 'Kwalifikacja do RYGB (BMI 44 + GERD)',
    badge: 'Chirurgia',
    description: 'Kobieta 36 lat, BMI 44 kg/m², refluks żołądkowo-przełykowy, bezdech senny.',
    data: {
      age: 36,
      sex: 'F',
      heightCm: 163,
      weightKg: 116,
      pal: 1.2,
      caloricIntake: 2300,
      bodyFatPct: 46,
      selectedDrug: 'none',
      drugDoseMg: 0,
      adherencePct: 0,
      comorbidities: { t2d: false, htn: true, osas: true, masld: true, gerd: true, dyslipidemia: true },
      bariatricProcedure: 'rygb',
      monthsPostOp: 12,
      tcMgDl: 220,
      hdlMgDl: 40,
      tgMgDl: 210,
      sbpMmHg: 140,
      smoker: false,
      statinRegimen: 'none',
      astU_L: 42,
      altU_L: 50,
      plt10e9_L: 225,
    },
  },
  {
    id: 'post-bariatric-dumping',
    name: 'Późny dumping syndrome po RYGB',
    badge: 'Powikłanie',
    description: 'Mężczyzna 39 lat po RYGB z poposiłkową hipoglikemią reaktywną.',
    data: {
      age: 39,
      sex: 'M',
      heightCm: 180,
      weightKg: 85,
      pal: 1.5,
      caloricIntake: 1800,
      bodyFatPct: 22,
      selectedDrug: 'none',
      drugDoseMg: 0,
      adherencePct: 0,
      comorbidities: { t2d: false, htn: false, osas: false, masld: false, gerd: false, dyslipidemia: false },
      bariatricProcedure: 'rygb',
      monthsPostOp: 18,
      tcMgDl: 160,
      hdlMgDl: 52,
      tgMgDl: 95,
      sbpMmHg: 115,
      smoker: false,
      statinRegimen: 'none',
      astU_L: 24,
      altU_L: 22,
      plt10e9_L: 260,
    },
  },
  {
    id: 'familial-hypercholesterolemia',
    name: 'Heterozygotyczna FH (HeFH)',
    badge: 'Genetyka',
    description: 'Mężczyzna 33 lata, żółtaki ścięgien Achillesa, LDL-C wyjściowy 295 mg/dl.',
    data: {
      age: 33,
      sex: 'M',
      heightCm: 182,
      weightKg: 86,
      pal: 1.6,
      caloricIntake: 2500,
      bodyFatPct: 21,
      selectedDrug: 'none',
      drugDoseMg: 0,
      adherencePct: 0,
      comorbidities: { t2d: false, htn: false, osas: false, masld: false, gerd: false, dyslipidemia: true },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 380,
      hdlMgDl: 48,
      tgMgDl: 140,
      sbpMmHg: 125,
      smoker: false,
      statinRegimen: 'triple_pcsk9',
      astU_L: 28,
      altU_L: 32,
      plt10e9_L: 280,
    },
  },
  {
    id: 'statin-intolerance-sams',
    name: 'Nietolerancja statyn (SAMS) po zawale',
    badge: 'Terapia skojarzona',
    description: 'Mężczyzna 64 lata po OZW, bóle mięśniowe na statynach, kwas bempedonowy.',
    data: {
      age: 64,
      sex: 'M',
      heightCm: 172,
      weightKg: 89,
      pal: 1.3,
      caloricIntake: 2100,
      bodyFatPct: 30,
      selectedDrug: 'none',
      drugDoseMg: 0,
      adherencePct: 0,
      comorbidities: { t2d: false, htn: true, osas: false, masld: false, gerd: false, dyslipidemia: true },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 230,
      hdlMgDl: 42,
      tgMgDl: 190,
      sbpMmHg: 135,
      smoker: false,
      statinRegimen: 'bempedoic_ezetimibe',
      astU_L: 34,
      altU_L: 36,
      plt10e9_L: 215,
    },
  },
  {
    id: 'severe-hypertriglyceridemia',
    name: 'Ciężka hipertriglicerydemia (TG 1450)',
    badge: 'Chylomikronemia',
    description: 'Zagrożenie ostrym zapaleniem trzustki, formuła Sampsona zamiast Friedewalda.',
    data: {
      age: 46,
      sex: 'M',
      heightCm: 178,
      weightKg: 104,
      pal: 1.3,
      caloricIntake: 2600,
      bodyFatPct: 34,
      selectedDrug: 'none',
      drugDoseMg: 0,
      adherencePct: 0,
      comorbidities: { t2d: true, htn: true, osas: false, masld: true, gerd: false, dyslipidemia: true },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 410,
      hdlMgDl: 28,
      tgMgDl: 1450,
      sbpMmHg: 142,
      smoker: true,
      statinRegimen: 'high',
      astU_L: 52,
      altU_L: 68,
      plt10e9_L: 195,
    },
  },
  {
    id: 'adaptive-thermogenesis-plateau',
    name: 'Plateau i adaptacja w modelu Halla',
    badge: 'Model Halla',
    description: 'Pacjent po utracie 25 kg ze spłaszczeniem krzywej ubytku wagi i spadkiem BMR.',
    data: {
      age: 40,
      sex: 'M',
      heightCm: 180,
      weightKg: 90,
      pal: 1.4,
      caloricIntake: 1800,
      bodyFatPct: 24,
      selectedDrug: 'semaglutide',
      drugDoseMg: 2.4,
      adherencePct: 100,
      comorbidities: { t2d: false, htn: false, osas: false, masld: false, gerd: false, dyslipidemia: false },
      bariatricProcedure: 'none',
      monthsPostOp: 0,
      tcMgDl: 190,
      hdlMgDl: 48,
      tgMgDl: 130,
      sbpMmHg: 120,
      smoker: false,
      statinRegimen: 'none',
      astU_L: 26,
      altU_L: 28,
      plt10e9_L: 230,
    },
  },
];
