import type {ModuleId} from './course-types.ts';
export const studyPrompts:Record<ModuleId,{question:string;answer:string;pitfall:string}>={
  tarczyca:{question:'Dlaczego prawidłowe TSH nie zamyka diagnostyki przy podejrzeniu choroby przysadki?',answer:'Interpretuj jednocześnie hormon obwodowy, sygnał przysadkowy i kontekst. W chorobie centralnej sygnał może być nieadekwatny do stężenia hormonu obwodowego.',pitfall:'Rozpoznanie z jednego TSH bez oceny FT4 i kontekstu.'},
  przysadka:{question:'Jak odróżnisz skutek ucisku od nadmiernego wydzielania i niedoboru hormonów?',answer:'Utwórz trzy osobne listy: objawy miejscowe, hipersekrecja i niedoczynność osi. Jeden guz może wiązać się z kilkoma mechanizmami.',pitfall:'Przypisanie wszystkich objawów jednemu hormonowi.'},
  nadnercza:{question:'Co musisz wiedzieć o pobraniu i lekach przed interpretacją testu hormonalnego?',answer:'Zapisz wskazanie do testu, porę pobrania, przygotowanie, stosowane leki i stan chorego. Wynik interpretuje się według protokołu konkretnego testu.',pitfall:'Traktowanie wyniku testu dynamicznego jak przypadkowego oznaczenia.'},
  przytarczyce:{question:'Dlaczego PTH należy zestawić z wapniem, funkcją nerek i kontekstem?',answer:'Odpowiedź PTH oceniamy względem bodźca i warunków regulacji, a nie tylko flagi laboratoryjnej. Rozpisz sygnał, efekt i czynniki zakłócające.',pitfall:'Uznanie PTH w zakresie za zawsze adekwatne.'},
  cukrzyca:{question:'Jak oddzielisz pilny problem od planu przewlekłego leczenia?',answer:'Najpierw oceń objawy i pilność. Następnie przejdź do rozpoznania typu zaburzenia, celów, leczenia i monitorowania. Plan przewlekły nie zastępuje oceny ostrego pogorszenia.',pitfall:'Wybór leku przed oceną stanu klinicznego.'},
  gonady:{question:'Jak zmieni się interpretacja, jeśli gonady są usunięte, a hormon podawany z zewnątrz?',answer:'Oddziel źródło gonadalne od egzogennego, zachowane piętra osi i przemiany obwodowe. Brak gonad nie oznacza braku receptorów ani zaniku wszystkich steroidów.',pitfall:'Zastępowanie anatomii etykietą płci lub samym stężeniem T.'},
  nen:{question:'Czy czynność hormonalna, lokalizacja i stopień złośliwości opisują to samo?',answer:'Nie. Zbierz osobno objawy wydzielania, lokalizację i zaawansowanie oraz cechy histopatologiczne. Każda warstwa odpowiada na inne pytanie.',pitfall:'Dobór postępowania z pojedynczego markera.'},
  otylosc:{question:'Jak zbudujesz plan wychodzący poza samą masę ciała?',answer:'Uwzględnij powikłania, funkcjonowanie, leki, preferencje i dostępność leczenia. Ustal cele oraz sposób oceny odpowiedzi i tolerancji.',pitfall:'Ocena sukcesu wyłącznie przez jedną liczbę na wadze.'},
};
