import type { PatientThreadState } from './types.ts';

export const TRAUMA_PATIENT_THREADS: Record<string, PatientThreadState> = {
  'thread-anna-ptsd': {
    threadId: 'thread-anna-ptsd',
    patientName: 'Anna S.',
    age: 32,
    sex: 'K',
    timelinePoint: 'Wypadek komunikacyjny (MVA) → ostra reakcja (ASR) → ASD → pełnoobjawowe PTSD → TF-CBT',
    establishedDiagnoses: ['Zespół stresu pourazowego (PTSD wg ICD-11 / DSM-5-TR)'],
    activeMedications: ['Sertralina 100 mg/d'],
    knownSensitivities: ['Nasilenie niepokoju i pobudzenia przy próbie wczesnego forsowania ekspozycji bez stabilizacji'],
    keyHistoryFacts: [
      'Uczestniczka ciężkiego zderzenia czołowego 3 miesiące temu; brak utraty przytomności, wykluczony uraz czaszkowo-mózgowy',
      'Intruzje o typie flashbacks przy dźwięku pisków opon z wegetatywnym pobudzeniem (tachykardia, drżenie)',
      'Unikanie wsiadania do samochodu nawet jako pasażer; wzmożona czujność i lękliwa reakcja na zaskoczenie (startle response)',
      'Zachowane poczucie ciągłości tożsamości, brak luk w pamięci codziennych zdarzeń poza samym momentem uderzenia',
    ],
    smoking: false,
    eGfr: 98,
  },

  'thread-michal-dpdr': {
    threadId: 'thread-michal-dpdr',
    patientName: 'Michał R.',
    age: 24,
    sex: 'M',
    timelinePoint: 'Pojedyncza intoksykacja THC z paniką → przewlekła depersonalizacja/derealizacja → lęk przed schizofrenią',
    establishedDiagnoses: ['Zespół depersonalizacji i derealizacji (DPDR wg ICD-11)'],
    activeMedications: ['Lamotrygina 100 mg/d (w miareczkowaniu)'],
    knownSensitivities: ['Lękowe nasilenie objawów po kofeinie i braku snu'],
    keyHistoryFacts: [
      'Początek 4 miesiące temu po wypaleniu marihuany: ostry atak paniki z poczuciem, że otoczenie jest „za szybą”',
      'Poczucie obcości własnych rąk i głosu, świat wydaje się sztuczny, dwuwymiarowy („jak z papieru”) lub filmowy',
      'W pełni zachowany krytycyzm (intact reality testing): pacjent wie, że to subiektywne wrażenie, obawia się utraty zmysłów',
      'Brak formalnych zaburzeń myślenia, brak urojeń, brak omamów słuchowych',
    ],
    smoking: false,
    eGfr: 104,
  },

  'thread-elena-did': {
    threadId: 'thread-elena-did',
    patientName: 'Elena V.',
    age: 29,
    sex: 'K',
    timelinePoint: 'Przewlekła trauma relacyjna w dzieciństwie → ubytki czasu (time loss) → dysocjacyjne zaburzenie tożsamości',
    establishedDiagnoses: ['Dysocjacyjne zaburzenie tożsamości (DID wg ICD-11 6B64 / DSM-5-TR 300.14)'],
    activeMedications: ['Brak leków swoistych dla DID; doraźna hydroksyzyna w stanach ostrej dysregulacji'],
    knownSensitivities: ['Retraumatyzacja przy próbach konfrontacyjnego lub hipnotycznego „odzyskiwania wspomnień”'],
    keyHistoryFacts: [
      'Długotrwałe, powtarzane nadużycia fizyczne i emocjonalne w dzieciństwie bez możliwości ucieczki',
      'Nawracające luki w pamięci bieżących zdarzeń (znajdowanie w szafie ubrań, których nie pamięta kupować; nieznani znajomi witający na ulicy)',
      'Wewnętrzne głosy o złożonej tożsamości (krytyczny obrońca, zlęknione dziecko) – wgląd zachowany w stanie neutralnym',
      'Brak urojeniowej interpretacji głosów i zachowany krytycyzm (brak osiowych cech schizofrenii)',
      'Prawidłowe rutynowe badanie neurologiczne, EEG i MRI mózgowia (brak dowodu organicznego)',
    ],
    smoking: false,
    eGfr: 94,
  },

  'thread-karolina-bpd': {
    threadId: 'thread-karolina-bpd',
    patientName: 'Karolina B.',
    age: 22,
    sex: 'K',
    timelinePoint: 'Lęk przed porzuceniem → kryzys relacyjny → samouszkodzenia → dysocjacja w stresie → program DBT',
    establishedDiagnoses: ['Zaburzenie osobowości typu borderline (BPD wg ICD-11 Borderline Pattern / DSM-5-TR)'],
    activeMedications: ['Sertralina 150 mg/d', 'Arypiprazol 2.5 mg/d (niska dawka wspomagająca stabilizację impulsywności)'],
    knownSensitivities: ['Gwałtowna reakcja unieważnienia (invalidation) przy moralizującym języku personelu'],
    keyHistoryFacts: [
      'Gwałtowna chwiejność nastroju w skali godzin (od euforii do rozpaczy i wściekłości po opóźnionej odpowiedzi na SMS)',
      'Trwałe poczucie pustki wewnętrznej, niestabilny obraz własnej osoby i planów zawodowych, ale bez odrębnych alterów',
      'Nawracające nacięcia przedramion jako niefarmakologiczna próba uśmierzenia psychicznego bólu i przerwania dysocjacji',
      'W sytuacjach skrajnego napięcia relacyjnego przemijające odrealnienie lub paranoidalne podejrzenia wobec partnera',
      'Brak nawracającej amnezji wobec codziennych wydarzeń autobiograficznych',
    ],
    smoking: true,
    eGfr: 101,
  },

  'thread-tomasz-tle': {
    threadId: 'thread-tomasz-tle',
    patientName: 'Tomasz M.',
    age: 38,
    sex: 'M',
    timelinePoint: 'Nawracające 30-sekundowe napady „odrealnienia” → mylna diagnoza ataków paniki → wideo-EEG → padaczka skroniowa',
    establishedDiagnoses: ['Padaczka ogniskowa z płata skroniowego (TLE) z napadami świadomymi i z zaburzeniami świadomości'],
    activeMedications: ['Lamotrygina 200 mg/d (terapia przeciwpadaczkowa)'],
    knownSensitivities: ['Leki obniżające próg drgawkowy (np. bupropion, klozapina)'],
    keyHistoryFacts: [
      'Epizody trwające ściśle 30–60 sekund: nagłe uczucie „wznoszenia z żołądka ku gardłu” (aura nadbrzuszna), metaliczny posmak',
      'Krótkotrwałe intensywne uczucie déjà vu i odrealnienia, po którym przez 2–3 minuty ma trudność ze znalezieniem słów',
      'Świadkowie opisują mlaskanie i automatyczne skubanie koszuli w trakcie napadu',
      'Wideo-EEG ujawniło iglice i fale wolne w lewej okolicy przednio-skroniowej; MRI 3T wykazało stwardnienie hipokampa (MTS)',
      'Przypadek stanowi klasyczny neurologiczny mimik zaburzeń dysocjacyjnych i lękowych',
    ],
    smoking: false,
    eGfr: 89,
  },

  'thread-kamil-psychosis': {
    threadId: 'thread-kamil-psychosis',
    patientName: 'Kamil W.',
    age: 19,
    sex: 'M',
    timelinePoint: 'Stopniowe wycofanie społeczne → głosy komentujące w ścianach → urojenia ksobne → leczenie przeciwpsychotyczne',
    establishedDiagnoses: ['Zaburzenie ze spektrum schizofrenii (pierwszy epizod psychotyczny)'],
    activeMedications: ['Olanzapina 10 mg/d'],
    knownSensitivities: ['Zespół metaboliczny, szybki przyrost masy ciała'],
    keyHistoryFacts: [
      'Od 6 miesięcy narastająca izolacja, spadek ocen na studiach, zaabsorbowanie ukrytymi znaczeniami audycji radiowych',
      'Głosy 2 osób lokalizowane w ścianie sąsiada, komentujące jego myśli w trzeciej osobie i rozkazujące nie wychodzić z pokoju',
      'Brak krytycyzmu (impaired reality testing): przekonanie, że sąsiedzi zamontowali podsłuch mikrofalowy',
      'Brak wywiadu ciężkiej traumy wczesnodziecięcej, brak amnezji autobiograficznej, brak odrębnych stanów tożsamości',
    ],
    smoking: true,
    eGfr: 110,
  },
};
