import type { WidgetPresetDefinition } from '../../content/preset-registry.ts';

export const TRAUMA_PRESETS: Record<string, WidgetPresetDefinition> = {
  'trauma-did-differential': {
    id: 'trauma-did-differential',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'did-tozsamosc-i-rozszczepienie',
    title: 'Różnicowanie DID: tożsamość i amnezja codzienna',
    initialState: {
      focusSection: 'differential',
      visibleControls: [
        'identityDiscontinuity',
        'amnesiaType',
        'realityTesting',
        'hallucinations',
      ],
      lockedFields: ['identityDiscontinuity', 'amnesiaType'],
      input: {
        identityDiscontinuity: 'distinct_personality_states',
        amnesiaType: 'recurrent_daily_activities',
        depersonalizationDerealization: true,
        realityTesting: 'intact',
        traumaIntrusions: 'distressing_memories',
        avoidanceHyperarousal: true,
        affectInstability: 'none',
        interpersonalPattern: 'stable',
        hallucinations: 'internal_dialogue_ego_dystonic',
        thoughtDisorder: false,
        symptomDuration: 'chronic_months',
        suicidalityRisk: 'none',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-dsm5-tr-2022', 'src-isstd-adult-did-2011'],
    claimIds: ['claim-trauma-did-core-criteria', 'claim-trauma-amnesia-everyday-did'],
  },

  'trauma-bpd-vs-did': {
    id: 'trauma-bpd-vs-did',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'did-roznicowanie-bpd-i-psychoza',
    title: 'Różnicowanie: niestabilność tożsamości w BPD a altery w DID',
    initialState: {
      focusSection: 'differential',
      visibleControls: [
        'identityDiscontinuity',
        'amnesiaType',
        'affectInstability',
        'interpersonalPattern',
        'suicidalityRisk',
      ],
      lockedFields: ['identityDiscontinuity', 'interpersonalPattern'],
      input: {
        identityDiscontinuity: 'disturbed_sense_of_self',
        amnesiaType: 'none',
        depersonalizationDerealization: true,
        realityTesting: 'transient_stress_induced',
        traumaIntrusions: 'none',
        avoidanceHyperarousal: false,
        affectInstability: 'rapid_reactive_hours',
        interpersonalPattern: 'intense_fear_of_abandonment',
        hallucinations: 'none',
        thoughtDisorder: false,
        symptomDuration: 'chronic_months',
        suicidalityRisk: 'recent_severe_self_harm',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-nice-cg78-bpd-2009', 'src-linehan-dbt-1993'],
    claimIds: ['claim-trauma-bpd-identity-vs-did', 'claim-trauma-bpd-abandonment-instability'],
  },

  'trauma-psychosis-vs-dissociation': {
    id: 'trauma-psychosis-vs-dissociation',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'did-roznicowanie-bpd-i-psychoza',
    title: 'Głosy wewnętrzne w DID a omamy w schizofrenii',
    initialState: {
      focusSection: 'differential',
      visibleControls: [
        'hallucinations',
        'realityTesting',
        'thoughtDisorder',
        'identityDiscontinuity',
      ],
      lockedFields: ['hallucinations', 'realityTesting'],
      input: {
        identityDiscontinuity: 'distinct_personality_states',
        amnesiaType: 'recurrent_daily_activities',
        depersonalizationDerealization: true,
        realityTesting: 'intact',
        traumaIntrusions: 'none',
        avoidanceHyperarousal: false,
        affectInstability: 'none',
        interpersonalPattern: 'stable',
        hallucinations: 'internal_dialogue_ego_dystonic',
        thoughtDisorder: false,
        symptomDuration: 'chronic_months',
        suicidalityRisk: 'none',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-dsm5-tr-2022'],
    claimIds: ['claim-trauma-did-voices-not-psychosis', 'claim-trauma-dpdr-intact-reality'],
  },

  'trauma-depersonalization-panic': {
    id: 'trauma-depersonalization-panic',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'depersonalizacja-i-derealizacja',
    title: 'Odrealnienie po kannabinoidach i w ataku paniki a psychoza',
    initialState: {
      focusSection: 'differential',
      visibleControls: [
        'depersonalizationDerealization',
        'realityTesting',
        'substanceContext',
        'thoughtDisorder',
      ],
      lockedFields: ['depersonalizationDerealization', 'realityTesting'],
      input: {
        identityDiscontinuity: 'none',
        amnesiaType: 'none',
        depersonalizationDerealization: true,
        realityTesting: 'intact',
        traumaIntrusions: 'none',
        avoidanceHyperarousal: true,
        affectInstability: 'none',
        interpersonalPattern: 'stable',
        hallucinations: 'none',
        thoughtDisorder: false,
        symptomDuration: 'days_under_30',
        substanceContext: {
          activeIntoxicationOrWithdrawal: false,
          onsetDirectlyTiedToSubstance: true,
          substanceDetails: 'Marihuana (epizod lękowy z derealizacją)',
        },
        suicidalityRisk: 'none',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-dsm5-tr-2022'],
    claimIds: ['claim-trauma-dpdr-intact-reality', 'claim-trauma-substance-dpdr-exclusion'],
  },

  'trauma-neuro-mimic': {
    id: 'trauma-neuro-mimic',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'trauma-somatyka-mimiki-i-bezpieczenstwo',
    title: 'Maska neurologiczna: padaczka płata skroniowego (TLE) a dysocjacja',
    initialState: {
      focusSection: 'safety_neurology',
      visibleControls: [
        'symptomDuration',
        'neurologicalFeatures',
        'amnesiaType',
        'depersonalizationDerealization',
      ],
      lockedFields: ['symptomDuration'],
      input: {
        identityDiscontinuity: 'none',
        amnesiaType: 'brief_paroxysmal',
        depersonalizationDerealization: true,
        realityTesting: 'intact',
        traumaIntrusions: 'none',
        avoidanceHyperarousal: false,
        affectInstability: 'none',
        interpersonalPattern: 'stable',
        hallucinations: 'none',
        thoughtDisorder: false,
        symptomDuration: 'brief_episodes_seconds',
        neurologicalFeatures: {
          hasAuraOrEpigastricRising: true,
          stereotypedSecondsDuration: true,
          postictalConfusion: true,
          focalDeficits: false,
        },
        suicidalityRisk: 'none',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-who-mhgap-2023'],
    claimIds: ['claim-trauma-tle-mimic-aura-stereotypy', 'claim-trauma-no-negative-test-confirmation'],
  },

  'trauma-cptsd-bpd': {
    id: 'trauma-cptsd-bpd',
    widgetType: 'trauma-dissociation-workbench',
    schemaVersion: 1,
    moduleId: 'psych-trauma-dysocjacja',
    lessonId: 'bpd-roznicowanie-cptsd-chad-adhd',
    title: 'Różnicowanie cPTSD a BPD: triada DSO i wzorzec więzi',
    initialState: {
      focusSection: 'differential',
      visibleControls: [
        'traumaIntrusions',
        'avoidanceHyperarousal',
        'affectInstability',
        'interpersonalPattern',
      ],
      lockedFields: ['traumaIntrusions', 'avoidanceHyperarousal'],
      input: {
        identityDiscontinuity: 'none',
        amnesiaType: 'trauma_specific',
        depersonalizationDerealization: false,
        realityTesting: 'intact',
        traumaIntrusions: 'distressing_memories',
        avoidanceHyperarousal: true,
        affectInstability: 'rapid_reactive_hours',
        interpersonalPattern: 'alienated_avoidant',
        hallucinations: 'none',
        thoughtDisorder: false,
        symptomDuration: 'chronic_months',
        suicidalityRisk: 'passive_ideation',
      },
    },
    sourceIds: ['src-icd11-cddr-2024', 'src-istss-guidelines-2019', 'src-nice-cg78-bpd-2009'],
    claimIds: ['claim-trauma-cptsd-dso-triad', 'claim-trauma-cptsd-vs-bpd-attachment'],
  },
};
